#!/usr/bin/env python
# encoding: utf-8

name = "Thion_DBE"
shortDesc = "The dibutyl ether submechanism of Thion et al. (2017), extracted and converted to an RMG reaction library."
longDesc = """
Sébastien Thion, Casimir Togbé, Zeynep Serinyel, Guillaume Dayma, Philippe Dagaut,
A chemical kinetic study of the oxidation of dibutyl-ether in a jet-stirred reactor,
Combustion and Flame,
Volume 185,
2017,
Pages 4-15,
ISSN 0010-2180,
https://doi.org/10.1016/j.combustflame.2017.06.019
"""
autoGenerated=False
entry(
    index = 0,
    label = "c4h9oc4h8-a + h <=> c4h9oc4h9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K'), comment="""DBE Unimol."""),
    longDesc = 
"""
Originally from reaction library: Unclassified
DBE Unimol.
""",
)

entry(
    index = 1,
    label = "c4h9oc4h8-b + h <=> c4h9oc4h9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 2,
    label = "c4h9oc4h8-c + h <=> c4h9oc4h9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 3,
    label = "c4h9oc4h8-d + h <=> c4h9oc4h9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 4,
    label = "c4h9oc4h9 <=> ch3 + c4h9oc3h6",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(3.79e+24,'s^-1'), n=-2.23, Ea=(88070,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.782e+60,'cm^3/(mol*s)'), n=-12.28, Ea=(83980,'cal/mol'), T0=(1,'K')), alpha=0.2352, T3=(724,'K'), T1=(5e+09,'K'), T2=(5e+09,'K'), efficiencies={}),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 5,
    label = "c4h9oc4h9 <=> c2h5 + c4h9oc2h4",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(5.53e+24,'s^-1'), n=-2.23, Ea=(89010,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(6.632e+59,'cm^3/(mol*s)'), n=-12.13, Ea=(84720,'cal/mol'), T0=(1,'K')), alpha=0.2438, T3=(744.06,'K'), T1=(5e+09,'K'), T2=(5e+09,'K'), efficiencies={}, comment="""troe fall-off reaction"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
troe fall-off reaction
""",
)

entry(
    index = 6,
    label = "c4h9oc4h9 <=> c4h9och2 + nc3h7",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(3.02e+23,'s^-1'), n=-1.88, Ea=(85710,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(1.416e+59,'cm^3/(mol*s)'), n=-11.93, Ea=(83980,'cal/mol'), T0=(1,'K')), alpha=0.7646, T3=(8.344e+09,'K'), T1=(724.8,'K'), T2=(8.214e+09,'K'), efficiencies={}, comment="""troe fall-off reaction"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
troe fall-off reaction
""",
)

entry(
    index = 7,
    label = "c4h9oc4h9 <=> pc4h9 + pc4h9o",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(6.33e+20,'s^-1'), n=-1.37, Ea=(89930,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(6.902e+51,'cm^3/(mol*s)'), n=-10.21, Ea=(84200,'cal/mol'), T0=(1,'K')), alpha=0.703, T3=(9.882e+09,'K'), T1=(634.68,'K'), T2=(1.786e+09,'K'), efficiencies={}, comment="""troe fall-off reaction"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
troe fall-off reaction
""",
)

entry(
    index = 8,
    label = "c4h9oc4h9 <=> pc4h9oh + c4h8-1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.3e+41,'s^-1'), n=-8.555, Ea=(77125,'cal/mol'), T0=(1,'K'), comment="""troe fall-off reaction"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
troe fall-off reaction
""",
)

entry(
    index = 9,
    label = "c4h9oc4h9 + h <=> c4h9oc4h8-a + h2",
    degeneracy = 1.0,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(6e+07,'cm^3/(mol*s)'), n=1.8, Ea=(3107,'cal/mol'), T0=(1,'K'), comment="""g3b3/rrkm almost no P dependence DBE H abstraction"""), Arrhenius(A=(7.8e+07,'cm^3/(mol*s)'), n=1.8, Ea=(3203,'cal/mol'), T0=(1,'K'), comment="""Al Rashidi""")]),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 10,
    label = "c4h9oc4h9 + h <=> c4h9oc4h8-b + h2",
    degeneracy = 1.0,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(3.2e+08,'cm^3/(mol*s)'), n=1.6, Ea=(6596,'cal/mol'), T0=(1,'K'), comment="""Al Rashidi"""), Arrhenius(A=(6.1e+07,'cm^3/(mol*s)'), n=1.8, Ea=(6095,'cal/mol'), T0=(1,'K'), comment="""Al Rashidi""")]),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 11,
    label = "c4h9oc4h9 + h <=> c4h9oc4h8-c + h2",
    degeneracy = 1.0,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(8.3e+07,'cm^3/(mol*s)'), n=1.8, Ea=(4995,'cal/mol'), T0=(1,'K'), comment="""Al Rashidi"""), Arrhenius(A=(7e+07,'cm^3/(mol*s)'), n=1.8, Ea=(5091,'cal/mol'), T0=(1,'K'), comment="""Al Rashidi""")]),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 12,
    label = "c4h9oc4h9 + h <=> c4h9oc4h8-d + h2",
    degeneracy = 1.0,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(3.3e+07,'cm^3/(mol*s)'), n=1.9, Ea=(7600,'cal/mol'), T0=(1,'K'), comment="""Al Rashidi"""), Arrhenius(A=(9.2e+07,'cm^3/(mol*s)'), n=1.8, Ea=(7791,'cal/mol'), T0=(1,'K'), comment="""Al Rashidi"""), Arrhenius(A=(9.4e+07,'cm^3/(mol*s)'), n=1.9, Ea=(8102,'cal/mol'), T0=(1,'K'), comment="""Al Rashidi""")]),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 13,
    label = "c4h9oc4h9 + oh <=> c4h9oc4h8-a + h2o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(720000,'cm^3/(mol*s)'), n=2.3, Ea=(-1800,'cal/mol'), T0=(1,'K'), comment="""Al Rashidi"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Al Rashidi
""",
)

entry(
    index = 14,
    label = "c4h9oc4h9 + oh <=> c4h9oc4h8-b + h2o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.08,'cm^3/(mol*s)'), n=3.7, Ea=(-3740,'cal/mol'), T0=(1,'K'), comment="""CALCULATION ZHOU ET AL.2010"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
CALCULATION ZHOU ET AL.2010
""",
)

entry(
    index = 15,
    label = "c4h9oc4h9 + oh <=> c4h9oc4h8-c + h2o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2280,'cm^3/(mol*s)'), n=2.87, Ea=(-2930,'cal/mol'), T0=(1,'K'), comment="""X2 BUTANOL SARATHY"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
X2 BUTANOL SARATHY
""",
)

entry(
    index = 16,
    label = "c4h9oc4h9 + oh <=> c4h9oc4h8-d + h2o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.73e+06,'cm^3/(mol*s)'), n=2.111, Ea=(774,'cal/mol'), T0=(1,'K'), comment="""X2 BUTANOL SARATHY"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
X2 BUTANOL SARATHY
""",
)

entry(
    index = 17,
    label = "c4h9oc4h9 + o <=> c4h9oc4h8-a + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(290000,'cm^3/(mol*s)'), n=2.41, Ea=(876,'cal/mol'), T0=(1,'K'), comment="""ANALOGY NC7H16+OH=NC7H15-1+H2O"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
ANALOGY NC7H16+OH=NC7H15-1+H2O
""",
)

entry(
    index = 18,
    label = "c4h9oc4h9 + o <=> c4h9oc4h8-b + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(95400,'cm^3/(mol*s)'), n=2.71, Ea=(2106,'cal/mol'), T0=(1,'K'), comment="""a*2 alpha butanol Guillaume"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 alpha butanol Guillaume
""",
)

entry(
    index = 19,
    label = "c4h9oc4h9 + o <=> c4h9oc4h8-c + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(95400,'cm^3/(mol*s)'), n=2.71, Ea=(2106,'cal/mol'), T0=(1,'K'), comment="""a*2 beta butanol Guillaume"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 beta butanol Guillaume
""",
)

entry(
    index = 20,
    label = "c4h9oc4h9 + o <=> c4h9oc4h8-d + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(386000,'cm^3/(mol*s)'), n=2.68, Ea=(3716,'cal/mol'), T0=(1,'K'), comment="""a*2 gamma butanol Guillaume"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 gamma butanol Guillaume
""",
)

entry(
    index = 21,
    label = "c4h9oc4h9 + ho2 <=> c4h9oc4h8-a + h2o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.000895,'cm^3/(mol*s)'), n=4.6, Ea=(4320,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol Guillaume"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol Guillaume
""",
)

entry(
    index = 22,
    label = "c4h9oc4h9 + ho2 <=> c4h9oc4h8-b + h2o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.0322,'cm^3/(mol*s)'), n=4.17, Ea=(12937,'cal/mol'), T0=(1,'K'), comment="""CURRAN ET AL. JPCA, 2014, 118, 1300-1308"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
CURRAN ET AL. JPCA, 2014, 118, 1300-1308
""",
)

entry(
    index = 23,
    label = "c4h9oc4h9 + ho2 <=> c4h9oc4h8-c + h2o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.22,'cm^3/(mol*s)'), n=3.74, Ea=(13622,'cal/mol'), T0=(1,'K'), comment="""CURRAN ET AL. JPCA, 2014, 118, 1300-1308"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
CURRAN ET AL. JPCA, 2014, 118, 1300-1308
""",
)

entry(
    index = 24,
    label = "c4h9oc4h9 + ho2 <=> c4h9oc4h8-d + h2o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(353,'cm^3/(mol*s)'), n=3.18, Ea=(17192,'cal/mol'), T0=(1,'K'), comment="""CURRAN ET AL. JPCA, 2014, 118, 1300-1308"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
CURRAN ET AL. JPCA, 2014, 118, 1300-1308
""",
)

entry(
    index = 25,
    label = "c4h9oc4h9 + ch3 <=> c4h9oc4h8-a + ch4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(39.86,'cm^3/(mol*s)'), n=3.37, Ea=(7634,'cal/mol'), T0=(1,'K'), comment="""CURRAN ET AL. JPCA, 2014, 118, 1300-1308"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
CURRAN ET AL. JPCA, 2014, 118, 1300-1308
""",
)

entry(
    index = 26,
    label = "c4h9oc4h9 + ch3 <=> c4h9oc4h8-b + ch4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.604,'cm^3/(mol*s)'), n=3.23, Ea=(6461,'cal/mol'), T0=(1,'K'), comment="""a*2 alpha butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 alpha butanol
""",
)

entry(
    index = 27,
    label = "c4h9oc4h9 + ch3 <=> c4h9oc4h8-c + ch4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.02,'cm^3/(mol*s)'), n=3.46, Ea=(5481,'cal/mol'), T0=(1,'K'), comment="""a*2 beta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 beta butanol
""",
)

entry(
    index = 28,
    label = "c4h9oc4h9 + ch3 <=> c4h9oc4h8-d + ch4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.906,'cm^3/(mol*s)'), n=3.65, Ea=(7154,'cal/mol'), T0=(1,'K'), comment="""a*2 gamma butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 gamma butanol
""",
)

entry(
    index = 29,
    label = "c4h9oc4h9 + o2 <=> c4h9oc4h8-a + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4e+13,'cm^3/(mol*s)'), n=0, Ea=(46800,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 30,
    label = "c4h9oc4h9 + o2 <=> c4h9oc4h8-b + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4e+13,'cm^3/(mol*s)'), n=0, Ea=(49800,'cal/mol'), T0=(1,'K'), comment="""a*2 alpha butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 alpha butanol
""",
)

entry(
    index = 31,
    label = "c4h9oc4h9 + o2 <=> c4h9oc4h8-c + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4e+13,'cm^3/(mol*s)'), n=0, Ea=(49800,'cal/mol'), T0=(1,'K'), comment="""a*2 beta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 beta butanol
""",
)

entry(
    index = 32,
    label = "c4h9oc4h9 + o2 <=> c4h9oc4h8-d + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6e+13,'cm^3/(mol*s)'), n=0, Ea=(52340,'cal/mol'), T0=(1,'K'), comment="""a*2 gamma butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 gamma butanol
""",
)

entry(
    index = 33,
    label = "c4h9oc4h9 + c2h5 <=> c4h9oc4h8-a + c2h6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.02e+11,'cm^3/(mol*s)'), n=0, Ea=(7900,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 34,
    label = "c4h9oc4h9 + c2h5 <=> c4h9oc4h8-b + c2h6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(10400,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 35,
    label = "c4h9oc4h9 + c2h5 <=> c4h9oc4h8-c + c2h6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(10400,'cal/mol'), T0=(1,'K'), comment="""a*2 gamma butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 gamma butanol
""",
)

entry(
    index = 36,
    label = "c4h9oc4h9 + c2h5 <=> c4h9oc4h8-d + c2h6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(13400,'cal/mol'), T0=(1,'K'), comment="""a*2 alpha butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 alpha butanol
""",
)

entry(
    index = 37,
    label = "c4h9oc4h9 + ch3o <=> c4h9oc4h8-a + ch3oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(4500,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 38,
    label = "c4h9oc4h9 + ch3o <=> c4h9oc4h8-b + ch3oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.04e+10,'cm^3/(mol*s)'), n=0.18, Ea=(4703,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 39,
    label = "c4h9oc4h9 + ch3o <=> c4h9oc4h8-c + ch3oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.9e+11,'cm^3/(mol*s)'), n=0, Ea=(4571,'cal/mol'), T0=(1,'K'), comment="""a*2 gamma butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 gamma butanol
""",
)

entry(
    index = 40,
    label = "c4h9oc4h9 + ch3o <=> c4h9oc4h8-d + ch3oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.34e+11,'cm^3/(mol*s)'), n=0, Ea=(6458,'cal/mol'), T0=(1,'K'), comment="""a*2 alpha butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 alpha butanol
""",
)

entry(
    index = 41,
    label = "c4h9oc4h9 + ch3o2 <=> c4h9oc4h8-a + ch3o2h",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6e+12,'cm^3/(mol*s)'), n=0, Ea=(17500,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 42,
    label = "c4h9oc4h9 + ch3o2 <=> c4h9oc4h8-b + ch3o2h",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3160,'cm^3/(mol*s)'), n=2.81, Ea=(14050,'cal/mol'), T0=(1,'K'), comment="""a*2 alpha butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 alpha butanol
""",
)

entry(
    index = 43,
    label = "c4h9oc4h9 + ch3o2 <=> c4h9oc4h8-c + ch3o2h",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(19280,'cm^3/(mol*s)'), n=2.6, Ea=(13910,'cal/mol'), T0=(1,'K'), comment="""a*2 beta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 beta butanol
""",
)

entry(
    index = 44,
    label = "c4h9oc4h9 + ch3o2 <=> c4h9oc4h8-d + ch3o2h",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(47600,'cm^3/(mol*s)'), n=2.55, Ea=(16490,'cal/mol'), T0=(1,'K'), comment="""a*2 gamma butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 gamma butanol
""",
)

entry(
    index = 45,
    label = "c4h9oc4h9 + hco <=> c4h9oc4h8-a + ch2o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+07,'cm^3/(mol*s)'), n=1.9, Ea=(17000,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 46,
    label = "c4h9oc4h9 + hco <=> c4h9oc4h8-b + ch2o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.032e+06,'cm^3/(mol*s)'), n=2.25, Ea=(16760,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 47,
    label = "c4h9oc4h9 + hco <=> c4h9oc4h8-c + ch2o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.18e+07,'cm^3/(mol*s)'), n=1.9, Ea=(17010,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 48,
    label = "c4h9oc4h9 + hco <=> c4h9oc4h8-d + ch2o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(204000,'cm^3/(mol*s)'), n=2.5, Ea=(18440,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 49,
    label = "c4h9oc4h9 + ocho <=> c4h9oc4h8-a + hocho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6e+12,'cm^3/(mol*s)'), n=0, Ea=(17500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 50,
    label = "c4h9oc4h9 + ocho <=> c4h9oc4h8-b + hocho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3160,'cm^3/(mol*s)'), n=2.81, Ea=(14050,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 51,
    label = "c4h9oc4h9 + ocho <=> c4h9oc4h8-c + hocho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(19280,'cm^3/(mol*s)'), n=2.6, Ea=(13910,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 52,
    label = "c4h9oc4h9 + ocho <=> c4h9oc4h8-d + hocho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(47600,'cm^3/(mol*s)'), n=2.55, Ea=(16490,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 53,
    label = "c4h9oc4h9 + o2cho <=> c4h9oc4h8-a + ho2cho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6e+12,'cm^3/(mol*s)'), n=0, Ea=(17500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 54,
    label = "c4h9oc4h9 + o2cho <=> c4h9oc4h8-b + ho2cho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3160,'cm^3/(mol*s)'), n=2.81, Ea=(14050,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 55,
    label = "c4h9oc4h9 + o2cho <=> c4h9oc4h8-c + ho2cho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(19280,'cm^3/(mol*s)'), n=2.6, Ea=(13910,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 56,
    label = "c4h9oc4h9 + o2cho <=> c4h9oc4h8-d + ho2cho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(47600,'cm^3/(mol*s)'), n=2.55, Ea=(16490,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 57,
    label = "c4h9oc4h9 + c2h5o <=> c4h9oc4h8-a + c2h5oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(4500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 58,
    label = "c4h9oc4h9 + c2h5o <=> c4h9oc4h8-b + c2h5oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.04e+10,'cm^3/(mol*s)'), n=0.18, Ea=(4703,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 59,
    label = "c4h9oc4h9 + c2h5o <=> c4h9oc4h8-c + c2h5oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.9e+11,'cm^3/(mol*s)'), n=0, Ea=(4571,'cal/mol'), T0=(1,'K'), comment="""a*2 gamma butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 gamma butanol
""",
)

entry(
    index = 60,
    label = "c4h9oc4h9 + c2h5o <=> c4h9oc4h8-d + c2h5oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.34e+11,'cm^3/(mol*s)'), n=0, Ea=(6458,'cal/mol'), T0=(1,'K'), comment="""a*2 alpha butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 alpha butanol
""",
)

entry(
    index = 61,
    label = "c4h9oc4h9 + c2h5o2 <=> c4h9oc4h8-a + c2h5o2h",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6e+12,'cm^3/(mol*s)'), n=0, Ea=(17500,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 62,
    label = "c4h9oc4h9 + c2h5o2 <=> c4h9oc4h8-b + c2h5o2h",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3160,'cm^3/(mol*s)'), n=2.81, Ea=(14050,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 63,
    label = "c4h9oc4h9 + c2h5o2 <=> c4h9oc4h8-c + c2h5o2h",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(19280,'cm^3/(mol*s)'), n=2.6, Ea=(13910,'cal/mol'), T0=(1,'K'), comment="""a*2 gamma butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 gamma butanol
""",
)

entry(
    index = 64,
    label = "c4h9oc4h9 + c2h5o2 <=> c4h9oc4h8-d + c2h5o2h",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(47600,'cm^3/(mol*s)'), n=2.55, Ea=(16490,'cal/mol'), T0=(1,'K'), comment="""a*2 alpha butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 alpha butanol
""",
)

entry(
    index = 65,
    label = "c4h9oc4h9 + ch3co <=> c4h9oc4h8-a + ch3cho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+07,'cm^3/(mol*s)'), n=1.9, Ea=(17000,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 66,
    label = "c4h9oc4h9 + ch3co <=> c4h9oc4h8-b + ch3cho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.032e+06,'cm^3/(mol*s)'), n=2.25, Ea=(16760,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 67,
    label = "c4h9oc4h9 + ch3co <=> c4h9oc4h8-c + ch3cho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.18e+07,'cm^3/(mol*s)'), n=1.9, Ea=(17010,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 68,
    label = "c4h9oc4h9 + ch3co <=> c4h9oc4h8-d + ch3cho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(204000,'cm^3/(mol*s)'), n=2.5, Ea=(18440,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 69,
    label = "c4h9oc4h9 + ch3co2 <=> c4h9oc4h8-a + ch3cooh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6e+12,'cm^3/(mol*s)'), n=0, Ea=(17500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 70,
    label = "c4h9oc4h9 + ch3co2 <=> c4h9oc4h8-b + ch3cooh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3160,'cm^3/(mol*s)'), n=2.81, Ea=(14050,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 71,
    label = "c4h9oc4h9 + ch3co2 <=> c4h9oc4h8-c + ch3cooh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(19280,'cm^3/(mol*s)'), n=2.6, Ea=(13910,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 72,
    label = "c4h9oc4h9 + ch3co2 <=> c4h9oc4h8-d + ch3cooh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(47600,'cm^3/(mol*s)'), n=2.55, Ea=(16490,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 73,
    label = "c4h9oc4h9 + ch3co3 <=> c4h9oc4h8-a + ch3co3h",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6e+12,'cm^3/(mol*s)'), n=0, Ea=(17500,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 74,
    label = "c4h9oc4h9 + ch3co3 <=> c4h9oc4h8-b + ch3co3h",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3160,'cm^3/(mol*s)'), n=2.81, Ea=(14050,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 75,
    label = "c4h9oc4h9 + ch3co3 <=> c4h9oc4h8-c + ch3co3h",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(19280,'cm^3/(mol*s)'), n=2.6, Ea=(13910,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 76,
    label = "c4h9oc4h9 + ch3co3 <=> c4h9oc4h8-d + ch3co3h",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(47600,'cm^3/(mol*s)'), n=2.55, Ea=(16490,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol
""",
)

entry(
    index = 77,
    label = "c4h9oc4h8-a <=> pc4h9 + nc3h7cho",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.142e+32,'s^-1'), n=-5.767, Ea=(29120.3,'cal/mol'), T0=(1,'K'), comment="""a*2 delta butanol R scission"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a*2 delta butanol R scission
""",
)

entry(
    index = 78,
    label = "c4h9oc4h8-a <=> c2h5 + c4h9oc2h3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.152e+32,'s^-1'), n=-5.59, Ea=(35793.1,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 79,
    label = "c4h9oc4h8-b <=> ch3 + c4h9oc3h5-3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.297e+20,'s^-1'), n=-2.217, Ea=(30468.3,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 80,
    label = "c4h9oc4h8-b <=> pc4h9o + c4h8-1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.267e+20,'s^-1'), n=-2.426, Ea=(25468.7,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 81,
    label = "c4h9oc4h8-c <=> c3h6 + c4h9och2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.262e+21,'s^-1'), n=-2.76, Ea=(28991.6,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 82,
    label = "c4h9oc4h8-d <=> c2h4 + c4h9oc2h4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.267e+21,'s^-1'), n=-2.786, Ea=(30991.2,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 83,
    label = "c4h9oc4h8-a <=> h + c4h9oc4h7-2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.85e+11,'s^-1'), n=0.34, Ea=(32520,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 84,
    label = "c4h9oc4h8-b <=> h + c4h9oc4h7-2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.85e+11,'s^-1'), n=0.34, Ea=(35520,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 85,
    label = "c4h9oc4h8-b <=> h + c4h9oc4h7-3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.85e+11,'s^-1'), n=0.34, Ea=(35520,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 86,
    label = "c4h9oc4h8-c <=> h + c4h9oc4h7-3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.85e+11,'s^-1'), n=0.34, Ea=(35520,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 87,
    label = "c4h9oc4h8-c <=> h + c4h9oc4h7-4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.85e+11,'s^-1'), n=0.34, Ea=(35520,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 88,
    label = "c4h9oc4h8-d <=> h + c4h9oc4h7-4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.85e+11,'s^-1'), n=0.34, Ea=(35520,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 89,
    label = "c4h9oc4h8-a <=> c4h9oc4h8-b",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.726e+17,'s^-1'), n=-2.103, Ea=(25068.8,'cal/mol'), T0=(1,'K'), comment="""R isomerisation"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
R isomerisation
""",
)

entry(
    index = 90,
    label = "c4h9oc4h8-a <=> c4h9oc4h8-c",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.253e+15,'s^-1'), n=-1.282, Ea=(18882.2,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 91,
    label = "c4h9oc4h8-a <=> c4h9oc4h8-d",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.33e+16,'s^-1'), n=-1.825, Ea=(26657.4,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 92,
    label = "c4h9oc4h8-a + o2 <=> c4oc4h8oo-a",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.641e+16,'cm^3/(mol*s)'), n=-0.99, Ea=(2765.58,'cal/mol'), T0=(1,'K'), comment="""R+O2=RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
R+O2=RO2
""",
)

entry(
    index = 93,
    label = "c4h9oc4h8-b + o2 <=> c4oc4h8oo-b",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.49e+14,'cm^3/(mol*s)'), n=-0.816, Ea=(-536.5,'cal/mol'), T0=(1,'K'), comment="""sakai"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
sakai
""",
)

entry(
    index = 94,
    label = "c4h9oc4h8-c + o2 <=> c4oc4h8oo-c",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.49e+14,'cm^3/(mol*s)'), n=-0.816, Ea=(-536.5,'cal/mol'), T0=(1,'K'), comment="""miyoshi"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
miyoshi
""",
)

entry(
    index = 95,
    label = "c4h9oc4h8-d + o2 <=> c4oc4h8oo-d",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.836e+16,'cm^3/(mol*s)'), n=-1.627, Ea=(199,'cal/mol'), T0=(1,'K'), comment="""miyoshi"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
miyoshi
""",
)

entry(
    index = 96,
    label = "c4h9oc4h8-a + o2 <=> ho2 + c4h9oc4h7-2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.703e+16,'cm^3/(mol*s)'), n=-1.63, Ea=(3418,'cal/mol'), T0=(1,'K'), comment="""sakai R+O2<=>ALKENE+HO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
sakai R+O2<=>ALKENE+HO2
""",
)

entry(
    index = 97,
    label = "c4h9oc4h8-b + o2 <=> ho2 + c4h9oc4h7-2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.703e+16,'cm^3/(mol*s)'), n=-1.63, Ea=(3418,'cal/mol'), T0=(1,'K'), comment="""desain et al., j.phys.chem.a, 107(2003)4415-4427"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
desain et al., j.phys.chem.a, 107(2003)4415-4427
""",
)

entry(
    index = 98,
    label = "c4h9oc4h8-b + o2 <=> ho2 + c4h9oc4h7-3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.703e+16,'cm^3/(mol*s)'), n=-1.63, Ea=(3418,'cal/mol'), T0=(1,'K'), comment="""desain et al., j.phys.chem.a, 107(2003)4415-4427"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
desain et al., j.phys.chem.a, 107(2003)4415-4427
""",
)

entry(
    index = 99,
    label = "c4h9oc4h8-c + o2 <=> ho2 + c4h9oc4h7-3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.703e+16,'cm^3/(mol*s)'), n=-1.63, Ea=(3418,'cal/mol'), T0=(1,'K'), comment="""desain et al., j.phys.chem.a, 107(2003)4415-4427"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
desain et al., j.phys.chem.a, 107(2003)4415-4427
""",
)

entry(
    index = 100,
    label = "c4h9oc4h8-c + o2 <=> ho2 + c4h9oc4h7-4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.349e+20,'cm^3/(mol*s)'), n=-3.02, Ea=(2504,'cal/mol'), T0=(1,'K'), comment="""desain et al., j.phys.chem.a, 107(2003)4415-4427"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
desain et al., j.phys.chem.a, 107(2003)4415-4427
""",
)

entry(
    index = 101,
    label = "c4h9oc4h8-d + o2 <=> ho2 + c4h9oc4h7-4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.703e+16,'cm^3/(mol*s)'), n=-1.63, Ea=(3418,'cal/mol'), T0=(1,'K'), comment="""desain et al., j.phys.chem.a, 107(2003)4415-4427"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
desain et al., j.phys.chem.a, 107(2003)4415-4427
""",
)

entry(
    index = 102,
    label = "c4h9oc4h8-a + c4oc4h8oo-a <=> c4h9oc4h8o-a + c4h9oc4h8o-a",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(-500,'cal/mol'), T0=(1,'K'), comment="""desain et al., j.phys.chem.a, 107(2003)4415-4427 R+ROO<=>RO+RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
desain et al., j.phys.chem.a, 107(2003)4415-4427 R+ROO<=>RO+RO
""",
)

entry(
    index = 103,
    label = "c4h9oc4h8-a + c4oc4h8oo-b <=> c4h9oc4h8o-a + c4h9oc4h8o-b",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 104,
    label = "c4h9oc4h8-a + c4oc4h8oo-c <=> c4h9oc4h8o-a + c4h9oc4h8o-c",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 105,
    label = "c4h9oc4h8-a + c4oc4h8oo-d <=> c4h9oc4h8o-a + c4h9oc4h8o-d",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 106,
    label = "c4h9oc4h8-b + c4oc4h8oo-a <=> c4h9oc4h8o-b + c4h9oc4h8o-a",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(-500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 107,
    label = "c4h9oc4h8-b + c4oc4h8oo-b <=> c4h9oc4h8o-b + c4h9oc4h8o-b",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 108,
    label = "c4h9oc4h8-b + c4oc4h8oo-c <=> c4h9oc4h8o-b + c4h9oc4h8o-c",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 109,
    label = "c4h9oc4h8-b + c4oc4h8oo-d <=> c4h9oc4h8o-b + c4h9oc4h8o-d",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 110,
    label = "c4h9oc4h8-c + c4oc4h8oo-a <=> c4h9oc4h8o-c + c4h9oc4h8o-a",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(-500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 111,
    label = "c4h9oc4h8-c + c4oc4h8oo-b <=> c4h9oc4h8o-c + c4h9oc4h8o-b",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 112,
    label = "c4h9oc4h8-c + c4oc4h8oo-c <=> c4h9oc4h8o-c + c4h9oc4h8o-c",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 113,
    label = "c4h9oc4h8-c + c4oc4h8oo-d <=> c4h9oc4h8o-c + c4h9oc4h8o-d",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 114,
    label = "c4h9oc4h8-d + c4oc4h8oo-a <=> c4h9oc4h8o-c + c4h9oc4h8o-a",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(-500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 115,
    label = "c4h9oc4h8-d + c4oc4h8oo-b <=> c4h9oc4h8o-c + c4h9oc4h8o-b",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 116,
    label = "c4h9oc4h8-d + c4oc4h8oo-c <=> c4h9oc4h8o-c + c4h9oc4h8o-c",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 117,
    label = "c4h9oc4h8-d + c4oc4h8oo-d <=> c4h9oc4h8o-c + c4h9oc4h8o-d",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 118,
    label = "c4h9oc4h8-a + ho2 <=> c4h9oc4h8o-a + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""R+HO2<=>RO+OH"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
R+HO2<=>RO+OH
""",
)

entry(
    index = 119,
    label = "c4h9oc4h8-b + ho2 <=> c4h9oc4h8o-b + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 120,
    label = "c4h9oc4h8-c + ho2 <=> c4h9oc4h8o-c + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 121,
    label = "c4h9oc4h8-d + ho2 <=> c4h9oc4h8o-d + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 122,
    label = "c4h9oc4h8-a + ch3o2 <=> c4h9oc4h8o-a + ch3o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K'), comment="""R+CH3O2<=>RO+CH3O"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
R+CH3O2<=>RO+CH3O
""",
)

entry(
    index = 123,
    label = "c4h9oc4h8-b + ch3o2 <=> c4h9oc4h8o-b + ch3o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 124,
    label = "c4h9oc4h8-c + ch3o2 <=> c4h9oc4h8o-c + ch3o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 125,
    label = "c4h9oc4h8-d + ch3o2 <=> c4h9oc4h8o-d + ch3o",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 126,
    label = "c4oc4h8oo-a + ho2 <=> c4oc4h8ooh-a + o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+11,'cm^3/(mol*s)'), n=0, Ea=(650,'cal/mol'), T0=(1,'K'), comment="""ROO+HO2<=>ROOH+O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
ROO+HO2<=>ROOH+O2
""",
)

entry(
    index = 127,
    label = "c4oc4h8oo-b + ho2 <=> c4oc4h8ooh-b + o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+11,'cm^3/(mol*s)'), n=0, Ea=(650,'cal/mol'), T0=(1,'K'), comment="""battin leclerc pecs 2008 440-498"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
battin leclerc pecs 2008 440-498
""",
)

entry(
    index = 128,
    label = "c4oc4h8oo-c + ho2 <=> c4oc4h8ooh-c + o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+11,'cm^3/(mol*s)'), n=0, Ea=(650,'cal/mol'), T0=(1,'K'), comment="""battin leclerc pecs 2008 440-498"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
battin leclerc pecs 2008 440-498
""",
)

entry(
    index = 129,
    label = "c4oc4h8oo-d + ho2 <=> c4oc4h8ooh-d + o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+11,'cm^3/(mol*s)'), n=0, Ea=(650,'cal/mol'), T0=(1,'K'), comment="""battin leclerc pecs 2008 440-498"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
battin leclerc pecs 2008 440-498
""",
)

entry(
    index = 130,
    label = "c4oc4h8oo-a + c4oc4h8oo-a => c4h9oc4h8o-a + c4h9oc4h8o-a + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.8e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(2000,'cal/mol'), T0=(1,'K'), comment="""battin leclerc pecs 2008 440-498 ROO+ROO=>RO+RO+O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
battin leclerc pecs 2008 440-498 ROO+ROO=>RO+RO+O2
""",
)

entry(
    index = 131,
    label = "c4oc4h8oo-a + c4oc4h8oo-b => c4h9oc4h8o-a + c4h9oc4h8o-b + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.8e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(2500,'cal/mol'), T0=(1,'K'), comment="""-1000"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
-1000
""",
)

entry(
    index = 132,
    label = "c4oc4h8oo-a + c4oc4h8oo-c => c4h9oc4h8o-a + c4h9oc4h8o-c + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.8e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(2500,'cal/mol'), T0=(1,'K'), comment="""-500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
-500
""",
)

entry(
    index = 133,
    label = "c4oc4h8oo-a + c4oc4h8oo-d => c4h9oc4h8o-a + c4h9oc4h8o-d + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.8e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(2500,'cal/mol'), T0=(1,'K'), comment="""-500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
-500
""",
)

entry(
    index = 134,
    label = "c4oc4h8oo-b + c4oc4h8oo-b => c4h9oc4h8o-b + c4h9oc4h8o-b + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.8e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(3000,'cal/mol'), T0=(1,'K'), comment="""-500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
-500
""",
)

entry(
    index = 135,
    label = "c4oc4h8oo-b + c4oc4h8oo-c => c4h9oc4h8o-b + c4h9oc4h8o-c + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.8e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(3000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 136,
    label = "c4oc4h8oo-b + c4oc4h8oo-d => c4h9oc4h8o-b + c4h9oc4h8o-d + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.8e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(3000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 137,
    label = "c4oc4h8oo-c + c4oc4h8oo-c => c4h9oc4h8o-c + c4h9oc4h8o-c + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.8e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(3000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 138,
    label = "c4oc4h8oo-c + c4oc4h8oo-d => c4h9oc4h8o-c + c4h9oc4h8o-d + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.8e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(3000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 139,
    label = "c4oc4h8oo-d + c4oc4h8oo-d => c4h9oc4h8o-d + c4h9oc4h8o-d + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.8e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(3000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 140,
    label = "c4oc4h8oo-a + ch3o2 => c4h9oc4h8o-a + ch3o + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1500,'cal/mol'), T0=(1,'K'), comment="""ROO+CH3O2=>RO+CH3O+O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
ROO+CH3O2=>RO+CH3O+O2
""",
)

entry(
    index = 141,
    label = "c4oc4h8oo-b + ch3o2 => c4h9oc4h8o-b + ch3o + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(2000,'cal/mol'), T0=(1,'K'), comment="""-500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
-500
""",
)

entry(
    index = 142,
    label = "c4oc4h8oo-c + ch3o2 => c4h9oc4h8o-c + ch3o + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(2000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 143,
    label = "c4oc4h8oo-d + ch3o2 => c4h9oc4h8o-d + ch3o + o2",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(2000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 144,
    label = "c4oc4h8oo-a + h2o2 <=> c4oc4h8ooh-a + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.4e+12,'cm^3/(mol*s)'), n=0, Ea=(5000,'cal/mol'), T0=(1,'K'), comment="""ROO+H2O2<=>ROOH+HO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
ROO+H2O2<=>ROOH+HO2
""",
)

entry(
    index = 145,
    label = "c4oc4h8oo-b + h2o2 <=> c4oc4h8ooh-b + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.4e+12,'cm^3/(mol*s)'), n=0, Ea=(5000,'cal/mol'), T0=(1,'K'), comment="""was 10000"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
was 10000
""",
)

entry(
    index = 146,
    label = "c4oc4h8oo-c + h2o2 <=> c4oc4h8ooh-c + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.4e+12,'cm^3/(mol*s)'), n=0, Ea=(5000,'cal/mol'), T0=(1,'K'), comment="""was 10000"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
was 10000
""",
)

entry(
    index = 147,
    label = "c4oc4h8oo-d + h2o2 <=> c4oc4h8ooh-d + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.4e+12,'cm^3/(mol*s)'), n=0, Ea=(5000,'cal/mol'), T0=(1,'K'), comment="""was 10000"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
was 10000
""",
)

entry(
    index = 148,
    label = "c4oc4h8oo-a <=> c4h9oc4h7-2 + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.168e+09,'s^-1'), n=1.01, Ea=(29362,'cal/mol'), T0=(1,'K'), comment="""was 10000 ROO<=>ALKENE+HO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
was 10000 ROO<=>ALKENE+HO2
""",
)

entry(
    index = 149,
    label = "c4oc4h8oo-b <=> c4h9oc4h7-2 + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.168e+09,'s^-1'), n=1.01, Ea=(26362,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 150,
    label = "c4oc4h8oo-b <=> c4h9oc4h7-3 + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.168e+09,'s^-1'), n=1.01, Ea=(29362,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 151,
    label = "c4oc4h8oo-c <=> c4h9oc4h7-3 + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.168e+09,'s^-1'), n=1.01, Ea=(29362,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 152,
    label = "c4oc4h8oo-c <=> c4h9oc4h7-4 + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.606e+09,'s^-1'), n=1.13, Ea=(30600,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 153,
    label = "c4oc4h8oo-d <=> c4h9oc4h7-4 + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.87e+07,'s^-1'), n=1.58, Ea=(28500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 154,
    label = "c4oc4h8oo-a <=> c4oc4-ao2h-b",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.32e+08,'s^-1'), n=1.26, Ea=(28600,'cal/mol'), T0=(1,'K'), comment="""RO2 isomerisation (QOOH)"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
RO2 isomerisation (QOOH)
""",
)

entry(
    index = 155,
    label = "c4oc4h8oo-a <=> c4oc4-ao2h-c",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.18e+08,'s^-1'), n=0.93, Ea=(18400,'cal/mol'), T0=(1,'K'), comment="""1-4s"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-4s
""",
)

entry(
    index = 156,
    label = "c4oc4h8oo-a <=> c4oc4-ao2h-d",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.83e+06,'s^-1'), n=1.27, Ea=(20800,'cal/mol'), T0=(1,'K'), comment="""1-5s"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-5s
""",
)

entry(
    index = 157,
    label = "c4oc4h8oo-a <=> c4oc4-ao2h-1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.18e+08,'s^-1'), n=0.93, Ea=(15400,'cal/mol'), T0=(1,'K'), comment="""1-6p"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-6p
""",
)

entry(
    index = 158,
    label = "c4oc4h8oo-a <=> c4oc4-ao2h-2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86e+06,'s^-1'), n=1.27, Ea=(17000,'cal/mol'), T0=(1,'K'), comment="""1-5s -3kcal"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-5s -3kcal
""",
)

entry(
    index = 159,
    label = "c4oc4h8oo-a <=> c4oc4-ao2h-3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(534000,'s^-1'), n=1.12, Ea=(15700,'cal/mol'), T0=(1,'K'), comment="""1-6s"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-6s
""",
)

entry(
    index = 160,
    label = "c4oc4h8oo-b <=> c4oc4-bo2h-a",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.15e+08,'s^-1'), n=1.05, Ea=(25600,'cal/mol'), T0=(1,'K'), comment="""1-7s"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-7s
""",
)

entry(
    index = 161,
    label = "c4oc4h8oo-b <=> c4oc4-bo2h-c",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.15e+08,'s^-1'), n=1.05, Ea=(28600,'cal/mol'), T0=(1,'K'), comment="""1-4s -3kcal"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-4s -3kcal
""",
)

entry(
    index = 162,
    label = "c4oc4h8oo-b <=> c4oc4-bo2h-d",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.494e+08,'s^-1'), n=1.12, Ea=(21500,'cal/mol'), T0=(1,'K'), comment="""1-4s"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-4s
""",
)

entry(
    index = 163,
    label = "c4oc4h8oo-b <=> c4oc4-bo2h-1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86e+06,'s^-1'), n=1.27, Ea=(14000,'cal/mol'), T0=(1,'K'), comment="""1-5p"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-5p
""",
)

entry(
    index = 164,
    label = "c4oc4h8oo-b <=> c4oc4-bo2h-2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(534000,'s^-1'), n=1.12, Ea=(15700,'cal/mol'), T0=(1,'K'), comment="""1-6s -3kcal"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-6s -3kcal
""",
)

entry(
    index = 165,
    label = "c4oc4h8oo-c <=> c4oc4-co2h-a",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.18e+08,'s^-1'), n=0.93, Ea=(15400,'cal/mol'), T0=(1,'K'), comment="""1-7s"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-7s
""",
)

entry(
    index = 166,
    label = "c4oc4h8oo-c <=> c4oc4-co2h-b",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.32e+08,'s^-1'), n=1.26, Ea=(28600,'cal/mol'), T0=(1,'K'), comment="""1-5s -3kcal"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-5s -3kcal
""",
)

entry(
    index = 167,
    label = "c4oc4h8oo-c <=> c4oc4-co2h-d",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.236e+07,'s^-1'), n=1.61, Ea=(32200,'cal/mol'), T0=(1,'K'), comment="""1-4s"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-4s
""",
)

entry(
    index = 168,
    label = "c4oc4h8oo-c <=> c4oc4-co2h-1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(534000,'s^-1'), n=1.12, Ea=(12700,'cal/mol'), T0=(1,'K'), comment="""1-4p"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-4p
""",
)

entry(
    index = 169,
    label = "c4oc4h8oo-d <=> c4oc4-do2h-a",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86e+06,'s^-1'), n=1.27, Ea=(14000,'cal/mol'), T0=(1,'K'), comment="""1-7s -3kcal"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-7s -3kcal
""",
)

entry(
    index = 170,
    label = "c4oc4h8oo-d <=> c4oc4-do2h-b",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.52e+06,'s^-1'), n=1.37, Ea=(17900,'cal/mol'), T0=(1,'K'), comment="""1-6s -3kcal"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-6s -3kcal
""",
)

entry(
    index = 171,
    label = "c4oc4h8oo-d <=> c4oc4-do2h-c",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.32e+08,'s^-1'), n=1.26, Ea=(28600,'cal/mol'), T0=(1,'K'), comment="""1-5s"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-5s
""",
)

entry(
    index = 172,
    label = "c4oc4h8ooh-a <=> c4h9oc4h8o-a + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+16,'s^-1'), n=0, Ea=(37000,'cal/mol'), T0=(1,'K'), comment="""1-4s ROOH<=>RO+OH"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-4s ROOH<=>RO+OH
""",
)

entry(
    index = 173,
    label = "c4oc4h8ooh-b <=> c4h9oc4h8o-b + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4e+15,'s^-1'), n=0, Ea=(43000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 174,
    label = "c4oc4h8ooh-c <=> c4h9oc4h8o-c + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4e+15,'s^-1'), n=0, Ea=(43000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 175,
    label = "c4oc4h8ooh-d <=> c4h9oc4h8o-d + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4e+15,'s^-1'), n=0, Ea=(43000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 176,
    label = "c4oc4-ao2h-b <=> c4oc4oa-b + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+12,'s^-1'), n=0, Ea=(14541.8,'cal/mol'), T0=(1,'K'), comment="""QOOH<=>CYCLIC ETHER+OH"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
QOOH<=>CYCLIC ETHER+OH
""",
)

entry(
    index = 177,
    label = "c4oc4-bo2h-a <=> c4oc4oa-b + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+12,'s^-1'), n=0, Ea=(12714.7,'cal/mol'), T0=(1,'K'), comment="""s./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./s-ooh
""",
)

entry(
    index = 178,
    label = "c4oc4-bo2h-c <=> c4oc4ob-c + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+12,'s^-1'), n=0, Ea=(15363.4,'cal/mol'), T0=(1,'K'), comment="""s./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./s-ooh
""",
)

entry(
    index = 179,
    label = "c4oc4-co2h-b <=> c4oc4ob-c + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+12,'s^-1'), n=0, Ea=(15363.4,'cal/mol'), T0=(1,'K'), comment="""s./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./s-ooh
""",
)

entry(
    index = 180,
    label = "c4oc4-co2h-d <=> c4oc4oc-d + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.55e+12,'s^-1'), n=0, Ea=(15445.8,'cal/mol'), T0=(1,'K'), comment="""s./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./s-ooh
""",
)

entry(
    index = 181,
    label = "c4oc4-do2h-c <=> c4oc4oc-d + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.55e+12,'s^-1'), n=0, Ea=(14465.7,'cal/mol'), T0=(1,'K'), comment="""p./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
p./s-ooh
""",
)

entry(
    index = 182,
    label = "c4oc4-ao2h-c <=> c4oc4oa-c + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.34e+11,'s^-1'), n=0, Ea=(18479.1,'cal/mol'), T0=(1,'K'), comment="""s./p-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./p-ooh
""",
)

entry(
    index = 183,
    label = "c4oc4-ao2h-1 <=> c4oc4oa-1 + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.34e+11,'s^-1'), n=0, Ea=(15217.9,'cal/mol'), T0=(1,'K'), comment="""s./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./s-ooh
""",
)

entry(
    index = 184,
    label = "c4oc4-bo2h-d <=> c4oc4ob-d + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.34e+10,'s^-1'), n=0, Ea=(19303.1,'cal/mol'), T0=(1,'K'), comment="""s./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./s-ooh
""",
)

entry(
    index = 185,
    label = "c4oc4-co2h-a <=> c4oc4oa-c + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.34e+11,'s^-1'), n=0, Ea=(17331.5,'cal/mol'), T0=(1,'K'), comment="""p./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
p./s-ooh
""",
)

entry(
    index = 186,
    label = "c4oc4-do2h-b <=> c4oc4ob-d + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.51e+11,'s^-1'), n=0, Ea=(18687.5,'cal/mol'), T0=(1,'K'), comment="""s./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./s-ooh
""",
)

entry(
    index = 187,
    label = "c4oc4-ao2h-d <=> c4oc4oa-d + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.77e+10,'s^-1'), n=0, Ea=(13752.1,'cal/mol'), T0=(1,'K'), comment="""s./p-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./p-ooh
""",
)

entry(
    index = 188,
    label = "c4oc4-ao2h-2 <=> c4oc4oa-2 + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.77e+10,'s^-1'), n=0, Ea=(14557.1,'cal/mol'), T0=(1,'K'), comment="""p./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
p./s-ooh
""",
)

entry(
    index = 189,
    label = "c4oc4-bo2h-1 <=> c4oc4oa-2 + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.77e+10,'s^-1'), n=0, Ea=(12835.7,'cal/mol'), T0=(1,'K'), comment="""s./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./s-ooh
""",
)

entry(
    index = 190,
    label = "c4oc4-do2h-a <=> c4oc4oa-d + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.77e+10,'s^-1'), n=0, Ea=(11106.1,'cal/mol'), T0=(1,'K'), comment="""s./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./s-ooh
""",
)

entry(
    index = 191,
    label = "c4oc4-ao2h-3 <=> c4oc4oa-3 + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.04e+10,'s^-1'), n=0, Ea=(12187.6,'cal/mol'), T0=(1,'K'), comment="""s./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./s-ooh
""",
)

entry(
    index = 192,
    label = "c4oc4-bo2h-2 <=> c4oc4ob-2 + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.04e+10,'s^-1'), n=0, Ea=(14687.8,'cal/mol'), T0=(1,'K'), comment="""s./p-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./p-ooh
""",
)

entry(
    index = 193,
    label = "c4oc4-co2h-1 <=> c4oc4oa-3 + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.04e+10,'s^-1'), n=0, Ea=(10949.4,'cal/mol'), T0=(1,'K'), comment="""s./p-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./p-ooh
""",
)

entry(
    index = 194,
    label = "c4oc4-ao2h-b <=> c4h9oc4h7-2 + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.01e+11,'s^-1'), n=0.35, Ea=(15200,'cal/mol'), T0=(1,'K'), comment="""s./p-ooh QOOH<=>ALKENE+HO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./p-ooh QOOH<=>ALKENE+HO2
""",
)

entry(
    index = 195,
    label = "c4oc4-bo2h-a <=> c4h9oc4h7-2 + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.82e+09,'s^-1'), n=0.9, Ea=(14900,'cal/mol'), T0=(1,'K'), comment="""s./t-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./t-ooh
""",
)

entry(
    index = 196,
    label = "c4oc4-bo2h-c <=> c4h9oc4h7-3 + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.5e+11,'s^-1'), n=0.37, Ea=(14900,'cal/mol'), T0=(1,'K'), comment="""t./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
t./s-ooh
""",
)

entry(
    index = 197,
    label = "c4oc4-co2h-b <=> c4h9oc4h7-3 + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.5e+11,'s^-1'), n=0.37, Ea=(14900,'cal/mol'), T0=(1,'K'), comment="""s./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./s-ooh
""",
)

entry(
    index = 198,
    label = "c4oc4-co2h-d <=> c4h9oc4h7-4 + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.21e+12,'s^-1'), n=0.23, Ea=(15600,'cal/mol'), T0=(1,'K'), comment="""s./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./s-ooh
""",
)

entry(
    index = 199,
    label = "c4oc4-do2h-c <=> c4h9oc4h7-4 + ho2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.04e+10,'s^-1'), n=0.94, Ea=(15100,'cal/mol'), T0=(1,'K'), comment="""p./s-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
p./s-ooh
""",
)

entry(
    index = 200,
    label = "c4oc4-ao2h-1 => nc3h7cho + nc3h7cho + oh",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3.081e+13,'s^-1'), n=0, Ea=(19469,'cal/mol'), T0=(1,'K'), comment="""s./p-ooh QOOH DECOMPOSITION"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
s./p-ooh QOOH DECOMPOSITION
""",
)

entry(
    index = 201,
    label = "c4oc4-ao2h-c => c3h6 + oh + c4h9ocho",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3.081e+13,'s^-1'), n=0, Ea=(18486,'cal/mol'), T0=(1,'K'), comment="""dpe"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
dpe
""",
)

entry(
    index = 202,
    label = "c4oc4-bo2h-d => c2h4 + oh + c4h9och2cho",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3.081e+13,'s^-1'), n=0, Ea=(25744,'cal/mol'), T0=(1,'K'), comment="""villano"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
villano
""",
)

entry(
    index = 203,
    label = "c4oc4-co2h-a => c4h9oc2h3 + ch3cho + oh",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3.081e+13,'s^-1'), n=0, Ea=(25428,'cal/mol'), T0=(1,'K'), comment="""villano"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
villano
""",
)

entry(
    index = 204,
    label = "c4oc4-do2h-b => c4h9oc3h5-3 + ch2o + oh",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3.081e+13,'s^-1'), n=0, Ea=(29169,'cal/mol'), T0=(1,'K'), comment="""villano"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
villano
""",
)

entry(
    index = 205,
    label = "c4oc4-ao2h-b + o2 <=> c8o-ao2h-bo2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.745e+14,'cm^3/(mol*s)'), n=-0.816, Ea=(-536.5,'cal/mol'), T0=(1,'K'), comment="""villano QOOH+O2=O2QOOH"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
villano QOOH+O2=O2QOOH
""",
)

entry(
    index = 206,
    label = "c4oc4-ao2h-c + o2 <=> c8o-ao2h-co2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.745e+14,'cm^3/(mol*s)'), n=-0.816, Ea=(-536.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 207,
    label = "c4oc4-ao2h-d + o2 <=> c8o-ao2h-do2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.418e+16,'cm^3/(mol*s)'), n=-1.627, Ea=(199,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 208,
    label = "c4oc4-ao2h-1 + o2 <=> c8o-ao2h-1o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.205e+15,'cm^3/(mol*s)'), n=-0.99, Ea=(2765.58,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 209,
    label = "c4oc4-ao2h-2 + o2 <=> c8o-ao2h-2o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.745e+14,'cm^3/(mol*s)'), n=-0.816, Ea=(-536.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 210,
    label = "c4oc4-ao2h-3 + o2 <=> c8o-ao2h-3o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.745e+14,'cm^3/(mol*s)'), n=-0.816, Ea=(-536.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 211,
    label = "c4oc4-bo2h-a + o2 <=> c8o-bo2h-ao2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.205e+15,'cm^3/(mol*s)'), n=-0.99, Ea=(2765.58,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 212,
    label = "c4oc4-bo2h-c + o2 <=> c8o-bo2h-co2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.745e+14,'cm^3/(mol*s)'), n=-0.816, Ea=(-536.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 213,
    label = "c4oc4-bo2h-d + o2 <=> c8o-bo2h-do2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.418e+16,'cm^3/(mol*s)'), n=-1.627, Ea=(199,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 214,
    label = "c4oc4-bo2h-1 + o2 <=> c8o-bo2h-1o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.205e+15,'cm^3/(mol*s)'), n=-0.99, Ea=(2765.58,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 215,
    label = "c4oc4-bo2h-2 + o2 <=> c8o-bo2h-2o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.745e+14,'cm^3/(mol*s)'), n=-0.816, Ea=(-536.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 216,
    label = "c4oc4-co2h-a + o2 <=> c8o-co2h-ao2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.205e+15,'cm^3/(mol*s)'), n=-0.99, Ea=(2765.58,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 217,
    label = "c4oc4-co2h-b + o2 <=> c8o-co2h-bo2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.745e+14,'cm^3/(mol*s)'), n=-0.816, Ea=(-536.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 218,
    label = "c4oc4-co2h-d + o2 <=> c8o-co2h-do2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.418e+16,'cm^3/(mol*s)'), n=-1.627, Ea=(199,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 219,
    label = "c4oc4-co2h-1 + o2 <=> c8o-co2h-1o2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.205e+15,'cm^3/(mol*s)'), n=-0.99, Ea=(2765.58,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 220,
    label = "c4oc4-do2h-a + o2 <=> c8o-do2h-ao2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.205e+15,'cm^3/(mol*s)'), n=-0.99, Ea=(2765.58,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 221,
    label = "c4oc4-do2h-b + o2 <=> c8o-do2h-bo2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.745e+14,'cm^3/(mol*s)'), n=-0.816, Ea=(-536.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 222,
    label = "c4oc4-do2h-c + o2 <=> c8o-do2h-co2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.745e+14,'cm^3/(mol*s)'), n=-0.816, Ea=(-536.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 223,
    label = "c8o-ao2h-bo2 <=> c4oc4keta-b + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86e+07,'s^-1'), n=1.38, Ea=(22600,'cal/mol'), T0=(1,'K'), comment="""O2QOOH=KET+OH"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
O2QOOH=KET+OH
""",
)

entry(
    index = 224,
    label = "c8o-ao2h-co2 <=> c4oc4keta-c + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.79e+07,'s^-1'), n=1.13, Ea=(12400,'cal/mol'), T0=(1,'K'), comment="""1-4t -3kcal"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-4t -3kcal
""",
)

entry(
    index = 225,
    label = "c8o-ao2h-do2 <=> c4oc4keta-d + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.63e+07,'s^-1'), n=0.91, Ea=(11700,'cal/mol'), T0=(1,'K'), comment="""1-5t -3kcal"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-5t -3kcal
""",
)

entry(
    index = 226,
    label = "c8o-ao2h-1o2 <=> c4oc4keta-1 + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.79e+07,'s^-1'), n=1.13, Ea=(12400,'cal/mol'), T0=(1,'K'), comment="""1-6t -3kcal"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-6t -3kcal
""",
)

entry(
    index = 227,
    label = "c8o-ao2h-2o2 <=> c4oc4keta-2 + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.49e+08,'s^-1'), n=0.71, Ea=(12000,'cal/mol'), T0=(1,'K'), comment="""1-5t -3kcal"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-5t -3kcal
""",
)

entry(
    index = 228,
    label = "c8o-ao2h-3o2 <=> c4oc4keta-3 + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.13e+06,'s^-1'), n=0.82, Ea=(10800,'cal/mol'), T0=(1,'K'), comment="""1-6t -3kcal"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-6t -3kcal
""",
)

entry(
    index = 229,
    label = "c8o-bo2h-ao2 <=> c4oc4ketb-a + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86e+07,'s^-1'), n=1.38, Ea=(25600,'cal/mol'), T0=(1,'K'), comment="""1-7t -3kcal"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-7t -3kcal
""",
)

entry(
    index = 230,
    label = "c8o-bo2h-co2 <=> c4oc4ketb-c + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86e+07,'s^-1'), n=1.38, Ea=(25600,'cal/mol'), T0=(1,'K'), comment="""1-4t"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-4t
""",
)

entry(
    index = 231,
    label = "c8o-bo2h-do2 <=> c4oc4ketb-d + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.79e+07,'s^-1'), n=1.13, Ea=(15400,'cal/mol'), T0=(1,'K'), comment="""1-4t"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-4t
""",
)

entry(
    index = 232,
    label = "c8o-bo2h-1o2 <=> c4oc4ketb-1 + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.49e+08,'s^-1'), n=0.71, Ea=(15000,'cal/mol'), T0=(1,'K'), comment="""1-5t"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-5t
""",
)

entry(
    index = 233,
    label = "c8o-bo2h-2o2 <=> c4oc4ketb-2 + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.13e+06,'s^-1'), n=0.82, Ea=(13800,'cal/mol'), T0=(1,'K'), comment="""1-6t"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-6t
""",
)

entry(
    index = 234,
    label = "c8o-co2h-ao2 <=> c4oc4ketc-a + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.79e+07,'s^-1'), n=1.13, Ea=(15400,'cal/mol'), T0=(1,'K'), comment="""1-7t"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-7t
""",
)

entry(
    index = 235,
    label = "c8o-co2h-bo2 <=> c4oc4ketc-b + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86e+07,'s^-1'), n=1.38, Ea=(25600,'cal/mol'), T0=(1,'K'), comment="""1-5t"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-5t
""",
)

entry(
    index = 236,
    label = "c8o-co2h-do2 <=> c4oc4ketc-d + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86e+07,'s^-1'), n=1.38, Ea=(25600,'cal/mol'), T0=(1,'K'), comment="""1-4t"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-4t
""",
)

entry(
    index = 237,
    label = "c8o-co2h-1o2 <=> c4oc4ketc-1 + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.13e+06,'s^-1'), n=0.82, Ea=(13800,'cal/mol'), T0=(1,'K'), comment="""1-4t"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-4t
""",
)

entry(
    index = 238,
    label = "c8o-do2h-ao2 <=> c4oc4ketd-a + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.63e+07,'s^-1'), n=0.91, Ea=(14700,'cal/mol'), T0=(1,'K'), comment="""1-7t"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-7t
""",
)

entry(
    index = 239,
    label = "c8o-do2h-bo2 <=> c4oc4ketd-b + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.79e+07,'s^-1'), n=1.13, Ea=(15400,'cal/mol'), T0=(1,'K'), comment="""1-6t"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-6t
""",
)

entry(
    index = 240,
    label = "c8o-do2h-co2 <=> c4oc4ketd-c + oh",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86e+07,'s^-1'), n=1.38, Ea=(25600,'cal/mol'), T0=(1,'K'), comment="""1-5t"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-5t
""",
)

entry(
    index = 241,
    label = "c4oc4keta-b => c4h9oco + c2h5cho + oh",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(4e+15,'s^-1'), n=0, Ea=(43000,'cal/mol'), T0=(1,'K'), comment="""1-4t KHP DECOMPOSITION"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
1-4t KHP DECOMPOSITION
""",
)

entry(
    index = 242,
    label = "c4oc4ketb-a => c4h9ocho + c2h5co + oh",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(4e+15,'s^-1'), n=0, Ea=(35000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 243,
    label = "c4oc4ketc-a => ch3coch2 + c4h9ocho + oh",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(4e+15,'s^-1'), n=0, Ea=(35000,'cal/mol'), T0=(1,'K'), comment="""a-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a-ooh
""",
)

entry(
    index = 244,
    label = "c4oc4ketc-b => ch3co + c4h9och2cho + oh",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(4e+15,'s^-1'), n=0, Ea=(43000,'cal/mol'), T0=(1,'K'), comment="""a-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a-ooh
""",
)

entry(
    index = 245,
    label = "c4oc4ketd-a => ch2ch2cho + c4h9ocho + oh",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(4e+15,'s^-1'), n=0, Ea=(35000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 246,
    label = "c4oc4ketd-b => ch2cho + c4h9och2cho + oh",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(4e+15,'s^-1'), n=0, Ea=(43000,'cal/mol'), T0=(1,'K'), comment="""a-ooh"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
a-ooh
""",
)

entry(
    index = 247,
    label = "c4oc4ketd-c => hco + c4h9oc2h4cho + oh",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(4e+15,'s^-1'), n=0, Ea=(43000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 248,
    label = "c4oc4keta-1 => c3h7cooh + c3h7cooh",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(2.1e+08,'s^-1'), n=0, Ea=(20000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 249,
    label = "c4oc4keta-c => co2 + ch3coch3 + pc4h9oh",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(2.1e+08,'s^-1'), n=0, Ea=(20000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

