#!/usr/bin/env python
# encoding: utf-8

name = "Michelbach_EL"
shortDesc = "RMG version of michelbach_EL_submech.inp - see the original file for sources."
longDesc = """

"""
autoGenerated=False
# entry(
#     index = 0,
#     label = "[CH2]C(=O)CCC(=O)OCC + H <=> CCOC(=O)CCC(C)=O",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(9.17499e+13,'cm^3/(mol*s)'), n=0.12, Ea=(0,'kcal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 1,
#     label = "CCOC(=O)C[CH]C(C)=O + H <=> CCOC(=O)CCC(C)=O",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1.76637e+13,'cm^3/(mol*s)'), n=0.15, Ea=(0,'kcal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 2,
#     label = "CCOC(=O)[CH]CC(C)=O + H <=> CCOC(=O)CCC(C)=O",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1.76637e+13,'cm^3/(mol*s)'), n=0.15, Ea=(0,'kcal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 3,
#     label = "C[CH]OC(=O)CCC(C)=O + H <=> CCOC(=O)CCC(C)=O",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(7.82867e+13,'cm^3/(mol*s)'), n=0.06, Ea=(0,'kcal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 4,
#     label = "[CH2]COC(=O)CCC(C)=O + H <=> CCOC(=O)CCC(C)=O",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(7.82867e+13,'cm^3/(mol*s)'), n=0.06, Ea=(0,'kcal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

entry(
    index = 5,
    label = "CCOC(=O)CCC(C)=O <=> C=C + CC(=O)CCC(=O)O",
    degeneracy = 1.0,
    kinetics = PDepArrhenius(pressures=([0.0001,0.0013,0.0133,0.1333,1.0133,1.1999,100],'bar'), arrhenius=[Arrhenius(A=(1.38038e+78,'s^-1'), n=-20.18, Ea=(72.57,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(1.58489e+85,'s^-1'), n=-21.73, Ea=(81.67,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(2.75422e+85,'s^-1'), n=-21.33, Ea=(87.2,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(1.20226e+85,'s^-1'), n=-20.82, Ea=(92.07,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(6.16595e+41,'s^-1'), n=-8.2, Ea=(67.12,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(6.16595e+39,'s^-1'), n=-7.62, Ea=(66.01,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(2.08929e+13,'s^-1'), n=0, Ea=(49.52,'kcal/mol'), T0=(1,'K'))]),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

# entry(
#     index = 6,
#     label = "CCOC(=O)CCC(C)=O <=> C[CH2] + CC(=O)CCC([O])=O",
#     degeneracy = 1.0,
#     kinetics = PDepArrhenius(pressures=([0.01,0.1,1,10,100],'bar'), arrhenius=[Arrhenius(A=(4.003e+83,'s^-1'), n=-20.748, Ea=(112.2,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(1.363e+73,'s^-1'), n=-17.08, Ea=(110.9,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(2.16e+55,'s^-1'), n=-11.482, Ea=(104.7,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(1.845e+38,'s^-1'), n=-6.282, Ea=(97.66,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(8.326e+26,'s^-1'), n=-2.871, Ea=(92.6,'kcal/mol'), T0=(1,'K'))]),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 7,
#     label = "CCOC(=O)CCC(C)=O <=> CC[O] + CC(=O)CC[C]=O",
#     degeneracy = 1.0,
#     kinetics = PDepArrhenius(pressures=([0.01,0.1,1,10,100],'bar'), arrhenius=[Arrhenius(A=(6.116e+84,'s^-1'), n=-21.657, Ea=(120.6,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(1.931e+79,'s^-1'), n=-19.291, Ea=(122.2,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(3.957e+62,'s^-1'), n=-13.904, Ea=(117.3,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(4.131e+43,'s^-1'), n=-8.077, Ea=(109.7,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(5.511e+29,'s^-1'), n=-3.893, Ea=(103.6,'kcal/mol'), T0=(1,'K'))]),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 8,
#     label = "CCOC(=O)CCC(C)=O <=> CCO[C]=O + [CH2]CC(C)=O",
#     degeneracy = 1.0,
#     kinetics = PDepArrhenius(pressures=([0.01,0.1,1,10,100],'bar'), arrhenius=[Arrhenius(A=(3.762e+84,'s^-1'), n=-21.199, Ea=(115,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(2.416e+75,'s^-1'), n=-17.863, Ea=(114.5,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(6.164e+57,'s^-1'), n=-12.296, Ea=(108.6,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(1.547e+40,'s^-1'), n=-6.923, Ea=(101.4,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(1.619e+28,'s^-1'), n=-3.319, Ea=(96.07,'kcal/mol'), T0=(1,'K'))]),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 9,
#     label = "CCOC(=O)CCC(C)=O <=> [CH3] + CCOC(=O)CC[C]=O",
#     degeneracy = 1.0,
#     kinetics = Troe(arrheniusHigh=Arrhenius(A=(2.243e+24,'s^-1'), n=-2.477, Ea=(87.6462,'kcal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(4.417e+69,'cm^3/(mol*s)'), n=-14.656, Ea=(94.7557,'kcal/mol'), T0=(1,'K')), alpha=0.1244, T3=(1057.9,'K'), T1=(1.04303e+06,'K'), T2=(6112.9,'K'), efficiencies={'C': 2.0, 'CC': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 10,
#     label = "CCOC(=O)CCC(C)=O <=> C[C]=O + [CH2]CC(=O)OCC",
#     degeneracy = 1.0,
#     kinetics = Troe(arrheniusHigh=Arrhenius(A=(3.557e+27,'s^-1'), n=-3.184, Ea=(85.7481,'kcal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(2.578e+79,'cm^3/(mol*s)'), n=-17.02, Ea=(96.8754,'kcal/mol'), T0=(1,'K')), alpha=0.0002, T3=(910.7,'K'), T1=(22707.2,'K'), T2=(5635.5,'K'), efficiencies={'C': 2.0, 'CC': 3.0, 'O': 6.0, 'O=C=O': 2.0, '[C-]#[O+]': 1.5, '[H][H]': 2.0}),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 11,
#     label = "CCOC(=O)CCC(C)=O <=> [CH2]C(C)=O + [CH2]C(=O)OCC",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(4.03e+15,'s^-1'), n=-0.1844, Ea=(77.7,'kcal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 12,
#     label = "CCOC(=O)CCC(C)=O <=> [CH3] + [CH2]OC(=O)CCC(C)=O",
#     degeneracy = 1.0,
#     kinetics = PDepArrhenius(pressures=([0.01,0.1,1,10,100],'bar'), arrhenius=[Arrhenius(A=(1.506e+83,'s^-1'), n=-20.738, Ea=(112.6,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(1.16e+73,'s^-1'), n=-17.162, Ea=(111.6,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(2.051e+55,'s^-1'), n=-11.569, Ea=(105.5,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(1.276e+38,'s^-1'), n=-6.324, Ea=(98.37,'kcal/mol'), T0=(1,'K')), Arrhenius(A=(4.029e+26,'s^-1'), n=-2.866, Ea=(93.25,'kcal/mol'), T0=(1,'K'))]),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

entry(
    index = 13,
    label = "[CH2]C(=O)CCC(=O)OCC <=> C=C=O + [CH2]CC(=O)OCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.5e+11,'s^-1'), n=0.58, Ea=(35.2,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 14,
    label = "CCOC(=O)C[CH]C(C)=O <=> [CH3] + CCOC(=O)CC=C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.15e+12,'s^-1'), n=0.3, Ea=(41.5,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 15,
    label = "CCOC(=O)C[CH]C(C)=O <=> CCO[C]=O + C=CC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.29e+12,'s^-1'), n=0.3, Ea=(35.4,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 16,
    label = "CCOC(=O)[CH]CC(C)=O <=> C[C]=O + C=CC(=O)OCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.78e+12,'s^-1'), n=0.22, Ea=(23.8,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 17,
    label = "CCOC(=O)[CH]CC(C)=O <=> CC[O] + CC(=O)CC=C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.45e+11,'s^-1'), n=0.51, Ea=(48.9,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 18,
    label = "[CH2]C(=O)CCC(=O)OCC <=> CCOC(=O)[CH]CC(C)=O",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(4.39e+10,'s^-1'), n=0.58, Ea=(22.31,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 19,
    label = "CCOC(=O)C[CH]C(C)=O <=> C[CH]OC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.22e+09,'s^-1'), n=0.52, Ea=(22.59,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 20,
    label = "CCOC(=O)[CH]CC(C)=O <=> C[CH]OC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.13e+10,'s^-1'), n=0.6, Ea=(28.03,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 21,
    label = "CCOC(=O)[CH]CC(C)=O <=> [CH2]C(=O)CCC(=O)OCC",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(3.54e+10,'s^-1'), n=0.54, Ea=(23.37,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 22,
    label = "CCOC(=O)CCC(C)=O + H <=> [CH2]C(=O)CCC(=O)OCC + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.205e+07,'cm^3/(mol*s)'), n=2.225, Ea=(6.9378,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 23,
    label = "CCOC(=O)CCC(C)=O + H <=> CCOC(=O)C[CH]C(C)=O + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.988e+06,'cm^3/(mol*s)'), n=2.256, Ea=(4.0838,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 24,
    label = "CCOC(=O)CCC(C)=O + H <=> CCOC(=O)[CH]CC(C)=O + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.12e+09,'cm^3/(mol*s)'), n=1.22, Ea=(4.77,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 25,
    label = "CCOC(=O)CCC(C)=O + H <=> C[CH]OC(=O)CCC(C)=O + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.44e+10,'cm^3/(mol*s)'), n=1.25, Ea=(5.97,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 26,
    label = "CCOC(=O)CCC(C)=O + H <=> [CH2]COC(=O)CCC(C)=O + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.83e+10,'cm^3/(mol*s)'), n=1.22, Ea=(9.86,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 27,
    label = "CCOC(=O)CCC(C)=O + OH <=> [CH2]C(=O)CCC(=O)OCC + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4060,'cm^3/(mol*s)'), n=2.84, Ea=(0.065,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 28,
    label = "CCOC(=O)CCC(C)=O + OH <=> CCOC(=O)C[CH]C(C)=O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3250,'cm^3/(mol*s)'), n=2.89, Ea=(-1.5,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 29,
    label = "CCOC(=O)CCC(C)=O + OH <=> CCOC(=O)[CH]CC(C)=O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(287,'cm^3/(mol*s)'), n=3.06, Ea=(-2.32,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 30,
    label = "CCOC(=O)CCC(C)=O + OH <=> C[CH]OC(=O)CCC(C)=O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.04631,'cm^3/(mol*s)'), n=4.32, Ea=(-1.64,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 31,
    label = "CCOC(=O)CCC(C)=O + OH <=> [CH2]COC(=O)CCC(C)=O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(41.92,'cm^3/(mol*s)'), n=3.72, Ea=(-0.019,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 32,
    label = "CCOC(=O)CCC(C)=O + HO2 <=> [CH2]C(=O)CCC(=O)OCC + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.00558,'cm^3/(mol*s)'), n=4.32, Ea=(13.4,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 33,
    label = "CCOC(=O)CCC(C)=O + HO2 <=> CCOC(=O)C[CH]C(C)=O + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.0842,'cm^3/(mol*s)'), n=3.93, Ea=(10.4,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 34,
    label = "CCOC(=O)CCC(C)=O + HO2 <=> CCOC(=O)[CH]CC(C)=O + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.00153,'cm^3/(mol*s)'), n=4.22, Ea=(11.05,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 35,
    label = "CCOC(=O)CCC(C)=O + HO2 <=> C[CH]OC(=O)CCC(C)=O + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.26e-05,'cm^3/(mol*s)'), n=4.86, Ea=(11.09,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 36,
    label = "CCOC(=O)CCC(C)=O + HO2 <=> [CH2]COC(=O)CCC(C)=O + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.0123,'cm^3/(mol*s)'), n=4.31, Ea=(18.72,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 37,
    label = "CCOC(=O)CCC(C)=O + [CH3] <=> [CH2]C(=O)CCC(=O)OCC + C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(37.1,'cm^3/(mol*s)'), n=3.12, Ea=(9.98,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 38,
    label = "CCOC(=O)CCC(C)=O + [CH3] <=> CCOC(=O)C[CH]C(C)=O + C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(14.1,'cm^3/(mol*s)'), n=3.29, Ea=(8.33,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 39,
    label = "CCOC(=O)CCC(C)=O + [CH3] <=> CCOC(=O)[CH]CC(C)=O + C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(54.6,'cm^3/(mol*s)'), n=3.13, Ea=(8.68,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 40,
    label = "CCOC(=O)CCC(C)=O + [CH3] <=> C[CH]OC(=O)CCC(C)=O + C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.7e-25,'cm^3/(mol*s)'), n=11.28, Ea=(-3.624,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 41,
    label = "CCOC(=O)CCC(C)=O + [CH3] <=> [CH2]COC(=O)CCC(C)=O + C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.771e-16,'cm^3/(mol*s)'), n=8.57, Ea=(2.637,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 42,
    label = "CCOC(=O)CCC(C)=O + O <=> CCOC(=O)[CH]CC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(45.5,'cm^3/(mol*s)'), n=3.6, Ea=(1.967,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 43,
    label = "CCOC(=O)CCC(C)=O + O <=> C[CH]OC(=O)CCC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(290.6,'cm^3/(mol*s)'), n=3.6, Ea=(3.887,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 44,
    label = "CCOC(=O)CCC(C)=O + O <=> [CH2]COC(=O)CCC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1065,'cm^3/(mol*s)'), n=3.6, Ea=(6.562,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 45,
    label = "[CH2]C(=O)CCC(=O)OCC + O2 <=> C(O[O])C(=O)CCC(=O)OCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 46,
    label = "CCOC(=O)C[CH]C(C)=O + O2 <=> CC(=O)C(O[O])CC(=O)OCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 47,
    label = "CCOC(=O)[CH]CC(C)=O + O2 <=> CC(=O)CC(O[O])C(=O)OCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.48e+12,'cm^3/(mol*s)'), n=0, Ea=(-0.61,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 48,
    label = "CC(=O)CCC(=O)OC(O[O])C <=> C[CH]OC(=O)CCC(C)=O + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.45e+18,'s^-1'), n=-0.99, Ea=(38.5956,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 49,
    label = "CC(=O)CCC(=O)OCCO[O] <=> [CH2]COC(=O)CCC(C)=O + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.97e+25,'s^-1'), n=-3.36, Ea=(36.0678,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 50,
    label = "CC(=O)C(O[O])CC(=O)OCC <=> CCOC(=O)C=CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 51,
    label = "CC(=O)CC(O[O])C(=O)OCC <=> CCOC(=O)C=CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 52,
    label = "CC(=O)CCC(=O)OC(O[O])C <=> C=COC(=O)CCC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(36900,'s^-1'), n=2.61, Ea=(29.01,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 53,
    label = "CC(=O)CCC(=O)OCCO[O] <=> C=COC(=O)CCC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.24e+06,'s^-1'), n=1.95, Ea=(30.13,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 54,
    label = "C(O[O])C(=O)CCC(=O)OCC <=> C(=O)C(=O)CCC(=O)OCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.25e+17,'s^-1'), n=-3.58, Ea=(44.55,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 55,
    label = "C(O[O])C(=O)CCC(=O)OCC <=> C([O])C(=O)CCC(=O)OCC + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.42e+16,'s^-1'), n=-2.97, Ea=(47.78,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 56,
    label = "C(O[O])C(=O)CCC(=O)OCC <=> [O]C(=O)CCC(=O)OCC + C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.34e+16,'s^-1'), n=-3.34, Ea=(34.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 57,
    label = "CC(=O)C(O[O])CC(=O)OCC <=> CC(=O)C(=O)CC(=O)OCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.69e+12,'s^-1'), n=-0.08, Ea=(39.2,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 58,
    label = "CC(=O)C(O[O])CC(=O)OCC <=> CC(=O)C([O])CC(=O)OCC + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.02e+14,'s^-1'), n=0, Ea=(58.5,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 59,
    label = "CC(=O)C(O[O])CC(=O)OCC <=> CC(=O)C1CC(=O)OO1 + CC[O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.16e+10,'s^-1'), n=0.47, Ea=(47.9,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 60,
    label = "CC(=O)CC(O[O])C(=O)OCC <=> CCOC(=O)C(=O)CC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.11e-09,'s^-1'), n=6.19, Ea=(27.2,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 61,
    label = "CC(=O)CC(O[O])C(=O)OCC <=> CC(=O)CC1OOC1=O + CC[O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.41e+10,'s^-1'), n=0.52, Ea=(55.1,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 62,
    label = "CC(=O)CCC(=O)OC(O[O])C <=> CC(=O)OC(=O)CCC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.44e+07,'s^-1'), n=1.46, Ea=(33.83,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 63,
    label = "CC(=O)CCC(=O)OCCO[O] <=> CC(=O)OC(=O)CCCC=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+06,'s^-1'), n=1.96, Ea=(38.06,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 64,
    label = "C(O[O])C(=O)CCC(=O)OCC <=> CCOC(=O)C[CH]C(=O)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.7e+11,'s^-1'), n=0, Ea=(17.717,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 65,
    label = "C(O[O])C(=O)CCC(=O)OCC <=> CCOC(=O)[CH]CC(=O)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.18e+11,'s^-1'), n=0, Ea=(11.256,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 66,
    label = "CC(=O)C(O[O])CC(=O)OCC <=> [CH2]C(=O)C(CC(=O)OCC)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.83e+11,'s^-1'), n=0, Ea=(33.378,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 67,
    label = "CC(=O)C(O[O])CC(=O)OCC <=> CCOC(=O)[CH]C(OO)C(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.19e+11,'s^-1'), n=0, Ea=(19.866,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 68,
    label = "CC(=O)CC(O[O])C(=O)OCC <=> [CH2]C(=O)CC(OO)C(=O)OCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.09e+11,'s^-1'), n=0, Ea=(11.287,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 69,
    label = "CC(=O)CC(O[O])C(=O)OCC <=> CCOC(=O)C([CH]C(C)=O)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.9e-06,'s^-1'), n=5, Ea=(21.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 70,
    label = "CC(=O)CC(O[O])C(=O)OCC <=> C[CH]OC(=O)C(CC(C)=O)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.878,'s^-1'), n=3.39, Ea=(24.1,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 71,
    label = "CC(=O)CCC(=O)OC(O[O])C <=> CC(=O)[CH]CC(=O)OC(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(52.5,'s^-1'), n=2.64, Ea=(17.6,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 72,
    label = "CC(=O)CCC(=O)OC(O[O])C <=> CC(=O)C[CH]C(=O)OC(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.68,'s^-1'), n=3.33, Ea=(20.4,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 73,
    label = "CC(=O)CCC(=O)OC(O[O])C <=> [CH2]C(OO)OC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3430,'s^-1'), n=2.68, Ea=(30.38,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 74,
    label = "CC(=O)CCC(=O)OCCO[O] <=> CC(=O)CCC(=O)O[CH]COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.19,'s^-1'), n=3.34, Ea=(20.36,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 75,
    label = "CCOC(=O)[CH]C(OO)C(C)=O <=> CCOC(=O)C=CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 76,
    label = "CCOC(=O)C([CH]C(C)=O)OO <=> CCOC(=O)C=CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 77,
    label = "C[CH]OC(=O)C(CC(C)=O)OO <=> CC(=O)CC1C(=O)OC1C + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.88e+09,'s^-1'), n=0.74, Ea=(48.8,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 78,
    label = "CC(=O)[CH]CC(=O)OC(C)OO <=> CC(=O)C1CC(=O)OC1C + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.38e+08,'s^-1'), n=0.91, Ea=(43.6,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 79,
    label = "CC(=O)C[CH]C(=O)OC(C)OO <=> CC(=O)CC1C(=O)OC1C + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.41e+09,'s^-1'), n=1.18, Ea=(59.1,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 80,
    label = "[CH2]C(OO)OC(=O)CCC(C)=O <=> C=COC(=O)CCC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(36900,'s^-1'), n=2.61, Ea=(29.01,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 81,
    label = "CC(=O)CCC(=O)O[CH]COO <=> C=COC(=O)CCC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.24e+06,'s^-1'), n=1.95, Ea=(30.13,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 82,
    label = "CCOC(=O)C[CH]C(=O)COO <=> CCOC(=O)CC=C=O + C=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+08,'s^-1'), n=1.23, Ea=(28.11,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 83,
    label = "CCOC(=O)[CH]CC(=O)COO <=> O=[C]COO + C=CC(=O)OCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.41e+10,'s^-1'), n=0.71, Ea=(25.52,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 84,
    label = "[CH2]C(=O)C(CC(=O)OCC)OO <=> CCOC(=O)CC=O + C=C=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.06e+38,'s^-1'), n=-8.34, Ea=(31.14,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 85,
    label = "CCOC(=O)C([CH]C(C)=O)OO <=> CCOC(=O)C(=O)CC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.27e+10,'s^-1'), n=0.87, Ea=(29.5,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 86,
    label = "C[CH]OC(=O)C(CC(C)=O)OO <=> CCOC(=O)C(=O)CC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.686,'s^-1'), n=3.63, Ea=(17.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 87,
    label = "C[CH]OC(=O)C(CC(C)=O)OO <=> CC(=O)CC([C]=O)OO + CC=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.98e+12,'s^-1'), n=0.25, Ea=(32,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 88,
    label = "CC(=O)[CH]CC(=O)OC(C)OO <=> CC(=O)OC(=O)CCC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(138,'s^-1'), n=2.66, Ea=(12.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 89,
    label = "CC(=O)[CH]CC(=O)OC(C)OO <=> CC(=O)C1CC1=O + CC([O])OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.7e+11,'s^-1'), n=0.7, Ea=(68.9,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 90,
    label = "CC(=O)C[CH]C(=O)OC(C)OO <=> CC(=O)OC(=O)CCC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.0021,'s^-1'), n=4.67, Ea=(22,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 91,
    label = "CC(=O)C[CH]C(=O)OC(C)OO <=> CC(=O)CC=C=O + CC([O])OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.43e+13,'s^-1'), n=0.46, Ea=(46.2,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 92,
    label = "[CH2]C(OO)OC(=O)CCC(C)=O <=> CC(=O)OC(=O)CCC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.69e+09,'s^-1'), n=1.02, Ea=(33.18,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 93,
    label = "CC(=O)CCC(=O)O[CH]COO <=> CC(=O)OC(=O)CCCC=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.01e+09,'s^-1'), n=1.1, Ea=(18.77,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 94,
    label = "CCOC(=O)C[CH]C(=O)COO <=> CCOC(=O)CC1OCC1=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.14e+09,'s^-1'), n=0.76, Ea=(30.39,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 95,
    label = "CCOC(=O)[CH]CC(=O)COO <=> CCOC(=O)C1CC(=O)CO1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.22e+12,'s^-1'), n=-0.08, Ea=(17.72,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 96,
    label = "[CH2]C(=O)C(CC(=O)OCC)OO <=> CCOC(=O)CC1OCC1=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.37e+39,'s^-1'), n=-8.55, Ea=(35.68,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 97,
    label = "CCOC(=O)[CH]C(OO)C(C)=O <=> CCOC(=O)C1OC1C(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.29e+32,'s^-1'), n=-6.6, Ea=(20.39,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 98,
    label = "[CH2]C(=O)CC(OO)C(=O)OCC <=> CCOC(=O)C1CC(=O)CO1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.22e+12,'s^-1'), n=-0.08, Ea=(17.72,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 99,
    label = "CCOC(=O)C([CH]C(C)=O)OO <=> CCOC(=O)C1OC1C(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.23e+11,'s^-1'), n=0.45, Ea=(14.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 100,
    label = "C[CH]OC(=O)C(CC(C)=O)OO <=> CC(=O)CC1OC(C)OC1=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.62e+11,'s^-1'), n=0.4, Ea=(25.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 101,
    label = "CC(=O)[CH]CC(=O)OC(C)OO <=> CC(=O)C1CC(=O)OC(C)O1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.59e+10,'s^-1'), n=0.35, Ea=(19.9,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 102,
    label = "CC(=O)C[CH]C(=O)OC(C)OO <=> CC(=O)CC1OC(C)OC1=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.17e+11,'s^-1'), n=0.6, Ea=(25.4,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 103,
    label = "[CH2]C(OO)OC(=O)CCC(C)=O <=> CC(=O)CCC(=O)OC1CO1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.07e+10,'s^-1'), n=0.63, Ea=(12.04,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 104,
    label = "CC(=O)CCC(=O)O[CH]COO <=> CC(=O)CCC(=O)OC1CO1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.12e+10,'s^-1'), n=0.6, Ea=(10,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 105,
    label = "CCOC(=O)C[CH]C(=O)COO <=> CCOC(=O)C=CC(=O)C[O] + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.56e+06,'s^-1'), n=1.34, Ea=(23.6,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 106,
    label = "CCOC(=O)C[CH]C(=O)COO + O2 <=> CCOC(=O)CC(O[O])C(=O)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 107,
    label = "CCOC(=O)[CH]CC(=O)COO + O2 <=> CCOC(=O)C(O[O])CC(=O)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.48e+12,'cm^3/(mol*s)'), n=0, Ea=(-0.61,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 108,
    label = "[CH2]C(=O)C(CC(=O)OCC)OO + O2 <=> C(O[O])C(=O)C(CC(=O)OCC)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 109,
    label = "CCOC(=O)[CH]C(OO)C(C)=O + O2 <=> CCOC(=O)C(O[O])C(OO)C(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.48e+12,'cm^3/(mol*s)'), n=0, Ea=(-0.61,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 110,
    label = "[CH2]C(=O)CC(OO)C(=O)OCC + O2 <=> C(O[O])C(=O)CC(OO)C(=O)OCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 111,
    label = "CCOC(=O)C([CH]C(C)=O)OO + O2 <=> CCOC(=O)C(C(O[O])C(C)=O)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 112,
    label = "CC(O[O])OC(=O)C(CC(C)=O)OO <=> C[CH]OC(=O)C(CC(C)=O)OO + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.45e+18,'s^-1'), n=-0.99, Ea=(38.5956,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 113,
    label = "CC(=O)[CH]CC(=O)OC(C)OO + O2 <=> CC(=O)C(O[O])CC(=O)OC(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 114,
    label = "CC(=O)C[CH]C(=O)OC(C)OO + O2 <=> CC(=O)CC(O[O])C(=O)OC(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.48e+12,'cm^3/(mol*s)'), n=0, Ea=(-0.61,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 115,
    label = "C(O[O])C(OO)OC(=O)CCC(C)=O <=> [CH2]C(OO)OC(=O)CCC(C)=O + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.97e+25,'s^-1'), n=-3.36, Ea=(36.0678,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 116,
    label = "CC(=O)CCC(=O)OC(O[O])COO <=> CC(=O)CCC(=O)O[CH]COO + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.45e+18,'s^-1'), n=-0.99, Ea=(38.5956,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 117,
    label = "CCOC(=O)CC(O[O])C(=O)COO <=> CCOC(=O)C=CC(=O)COO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

# entry(
#     index = 118,
#     label = "CCOC(=O)C(C(O[O])C(C)=O)OO <=> CCOC(=O)C(OO)=CC(=O)C + HO2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

entry(
    index = 119,
    label = "CC(=O)C(O[O])CC(=O)OC(C)OO <=> CC(OO)OC(=O)C=CC(=O)C + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 120,
    label = "CCOC(=O)C(O[O])CC(=O)COO <=> CCOC(=O)C=CC(=O)COO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 121,
    label = "CCOC(=O)C(O[O])C(OO)C(C)=O <=> CCOC(=O)C=C(OO)C(=O)C + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 122,
    label = "CC(=O)CC(O[O])C(=O)OC(C)OO <=> CC(OO)OC(=O)C=CC(=O)C + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 123,
    label = "CC(O[O])OC(=O)C(CC(C)=O)OO <=> C=COC(=O)C(CC(C)=O)OO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(36900,'s^-1'), n=2.61, Ea=(29.01,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 124,
    label = "CC(=O)CCC(=O)OC(O[O])COO <=> C(OO)=COC(=O)CCC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(36900,'s^-1'), n=2.61, Ea=(29.01,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 125,
    label = "C(O[O])C(OO)OC(=O)CCC(C)=O <=> C=C(OO)OC(=O)CCC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.24e+06,'s^-1'), n=1.95, Ea=(30.13,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 126,
    label = "C(O[O])C(=O)C(CC(=O)OCC)OO <=> C(=O)C(=O)C(CC(=O)OCC)OO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.25e+17,'s^-1'), n=-3.58, Ea=(44.55,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 127,
    label = "C(O[O])C(=O)CC(OO)C(=O)OCC <=> C(=O)C(=O)CC(OO)C(=O)OCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.25e+17,'s^-1'), n=-3.58, Ea=(44.55,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 128,
    label = "CCOC(=O)CC(O[O])C(=O)COO <=> C(OO)C(=O)C(=O)CC(=O)OCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.69e+12,'s^-1'), n=-0.08, Ea=(39.2,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 129,
    label = "CCOC(=O)C(C(O[O])C(C)=O)OO <=> CC(=O)C(=O)C(OO)C(=O)OCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.69e+12,'s^-1'), n=-0.08, Ea=(39.2,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 130,
    label = "CC(=O)C(O[O])CC(=O)OC(C)OO <=> CC(=O)C(=O)CC(=O)OC(OO)C + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.69e+12,'s^-1'), n=-0.08, Ea=(39.2,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 131,
    label = "CCOC(=O)C(O[O])CC(=O)COO <=> C(OO)C(=O)CC(=O)C(=O)OCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.11e-09,'s^-1'), n=6.19, Ea=(27.2,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 132,
    label = "CCOC(=O)C(O[O])C(OO)C(C)=O <=> CC(=O)C(OO)C(=O)C(=O)OCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.11e-09,'s^-1'), n=6.19, Ea=(27.2,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 133,
    label = "CC(=O)CC(O[O])C(=O)OC(C)OO <=> CC(=O)CC(=O)C(=O)OC(OO)C + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.11e-09,'s^-1'), n=6.19, Ea=(27.2,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 134,
    label = "CC(O[O])OC(=O)C(CC(C)=O)OO <=> CC(=O)CC(OO)C(=O)OC(=O)C + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.44e+07,'s^-1'), n=1.46, Ea=(33.83,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 135,
    label = "CC(=O)CCC(=O)OC(O[O])COO <=> CC(=O)CCC(=O)OC(=O)C(OO) + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.44e+07,'s^-1'), n=1.46, Ea=(33.83,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 136,
    label = "C(O[O])C(OO)OC(=O)CCC(C)=O <=> CC(=O)CCC(=O)OC(OO)C(=O) + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+06,'s^-1'), n=1.96, Ea=(38.06,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 137,
    label = "CCOC(=O)CC(O[O])C(=O)COO <=> CCOC(=O)[CH]C(OO)C(=O)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.19e+11,'s^-1'), n=0, Ea=(19.866,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 138,
    label = "CCOC(=O)CC(O[O])C(=O)COO <=> CCOC(=O)CC(OO)C(=O)[CH]OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.83e+11,'s^-1'), n=0, Ea=(33.378,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 139,
    label = "CCOC(=O)C(O[O])CC(=O)COO <=> CCOC(=O)C([CH]C(=O)COO)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.9e-06,'s^-1'), n=5, Ea=(21.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 140,
    label = "CCOC(=O)C(O[O])CC(=O)COO <=> C[CH]OC(=O)C(CC(=O)COO)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.878,'s^-1'), n=3.39, Ea=(24.1,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 141,
    label = "CCOC(=O)C(O[O])CC(=O)COO <=> CCOC(=O)C(CC(=O)[CH]OO)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.09e+11,'s^-1'), n=0, Ea=(11.287,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 142,
    label = "C(O[O])C(=O)C(CC(=O)OCC)OO <=> CCOC(=O)C[C](OO)C(=O)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.7e+11,'s^-1'), n=0, Ea=(17.717,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 143,
    label = "C(O[O])C(=O)C(CC(=O)OCC)OO <=> CCOC(=O)[CH]C(OO)C(=O)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.18e+11,'s^-1'), n=0, Ea=(11.256,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 144,
    label = "CCOC(=O)C(O[O])C(OO)C(C)=O <=> CCOC(=O)C(OO)[C](OO)C(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.9e-06,'s^-1'), n=5, Ea=(21.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 145,
    label = "CCOC(=O)C(O[O])C(OO)C(C)=O <=> C[CH]OC(=O)C(OO)C(OO)C(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.878,'s^-1'), n=3.39, Ea=(24.1,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 146,
    label = "CCOC(=O)C(O[O])C(OO)C(C)=O <=> [CH2]C(=O)C(OO)C(OO)C(=O)OCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.09e+11,'s^-1'), n=0, Ea=(11.287,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 147,
    label = "C(O[O])C(=O)CC(OO)C(=O)OCC <=> CCOC(=O)C([CH]C(=O)COO)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.7e+11,'s^-1'), n=0, Ea=(17.717,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 148,
    label = "C(O[O])C(=O)CC(OO)C(=O)OCC <=> CCOC(=O)[C](CC(=O)COO)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.18e+11,'s^-1'), n=0, Ea=(11.256,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 149,
    label = "CCOC(=O)C(C(O[O])C(C)=O)OO <=> CCOC(=O)[C](OO)C(OO)C(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.19e+11,'s^-1'), n=0, Ea=(19.866,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 150,
    label = "CCOC(=O)C(C(O[O])C(C)=O)OO <=> [CH2]C(=O)C(OO)C(OO)C(=O)OCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.83e+11,'s^-1'), n=0, Ea=(33.378,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 151,
    label = "CC(O[O])OC(=O)C(CC(C)=O)OO <=> [CH2]C(OO)OC(=O)C(CC(C)=O)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3430,'s^-1'), n=2.68, Ea=(30.38,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 152,
    label = "CC(O[O])OC(=O)C(CC(C)=O)OO <=> CC(=O)C[C](OO)C(=O)OC(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.68,'s^-1'), n=3.33, Ea=(20.4,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 153,
    label = "CC(O[O])OC(=O)C(CC(C)=O)OO <=> CC(=O)[CH]C(OO)C(=O)OC(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(52.5,'s^-1'), n=2.64, Ea=(17.6,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 154,
    label = "CC(=O)C(O[O])CC(=O)OC(C)OO <=> CC(=O)C([CH]C(=O)OC(C)OO)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.19e+11,'s^-1'), n=0, Ea=(19.866,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 155,
    label = "CC(=O)C(O[O])CC(=O)OC(C)OO <=> [CH2]C(=O)C(CC(=O)OC(C)OO)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.83e+11,'s^-1'), n=0, Ea=(33.378,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 156,
    label = "CC(=O)CC(O[O])C(=O)OC(C)OO <=> CC(=O)[CH]C(OO)C(=O)OC(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.9e-06,'s^-1'), n=5, Ea=(21.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 157,
    label = "CC(=O)CC(O[O])C(=O)OC(C)OO <=> C[C](OO)OC(=O)C(CC(C)=O)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.878,'s^-1'), n=3.39, Ea=(24.1,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 158,
    label = "CC(=O)CC(O[O])C(=O)OC(C)OO <=> [CH2]C(=O)CC(OO)C(=O)OC(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.09e+11,'s^-1'), n=0, Ea=(11.287,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 159,
    label = "C(O[O])C(OO)OC(=O)CCC(C)=O <=> CC(=O)CCC(=O)O[C](COO)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.19,'s^-1'), n=3.34, Ea=(20.36,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 160,
    label = "CC(=O)CCC(=O)OC(O[O])COO <=> CC(=O)CCC(=O)OC([CH]OO)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3430,'s^-1'), n=2.68, Ea=(30.38,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 161,
    label = "CC(=O)CCC(=O)OC(O[O])COO <=> CC(=O)C[CH]C(=O)OC(COO)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.68,'s^-1'), n=3.33, Ea=(20.4,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 162,
    label = "CC(=O)CCC(=O)OC(O[O])COO <=> CC(=O)[CH]CC(=O)OC(COO)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(52.5,'s^-1'), n=2.64, Ea=(17.6,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 163,
    label = "CCOC(=O)[CH]C(OO)C(=O)COO <=> CCOC(=O)C=CC(=O)COO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 164,
    label = "CCOC(=O)[C](OO)C(OO)C(C)=O <=> CCOC(=O)C(OO)=CC(=O)C + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 165,
    label = "CC(=O)C([CH]C(=O)OC(C)OO)OO <=> CC(OO)OC(=O)C=CC(=O)C + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 166,
    label = "CCOC(=O)C([CH]C(=O)COO)OO <=> CCOC(=O)C=CC(=O)COO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 167,
    label = "CCOC(=O)C(OO)[C](OO)C(C)=O <=> CCOC(=O)C=C(OO)C(=O)C + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 168,
    label = "CC(=O)[CH]C(OO)C(=O)OC(C)OO <=> CC(OO)OC(=O)C=CC(=O)C + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 169,
    label = "[CH2]C(OO)OC(=O)C(CC(C)=O)OO <=> C=COC(=O)C(CC(C)=O)OO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(36900,'s^-1'), n=2.61, Ea=(29.01,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 170,
    label = "CC(=O)CCC(=O)OC([CH]OO)OO <=> C(OO)=COC(=O)CCC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(36900,'s^-1'), n=2.61, Ea=(29.01,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 171,
    label = "CC(=O)CCC(=O)O[C](COO)OO <=> C=C(OO)OC(=O)CCC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.24e+06,'s^-1'), n=1.95, Ea=(30.13,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 172,
    label = "C[CH]OC(=O)C(CC(=O)COO)OO <=> CC1OC(=O)C1CC(=O)COO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.88e+09,'s^-1'), n=0.74, Ea=(48.8,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 173,
    label = "C[CH]OC(=O)C(OO)C(OO)C(C)=O <=> CC(=O)C(OO)C1C(=O)OC1C + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.88e+09,'s^-1'), n=0.74, Ea=(48.8,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 174,
    label = "C[C](OO)OC(=O)C(CC(C)=O)OO <=> CC(=O)CC1C(=O)OC1(C)OO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.88e+09,'s^-1'), n=0.74, Ea=(48.8,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 175,
    label = "CC(=O)[CH]C(OO)C(=O)OC(C)OO <=> CC(=O)C1C(C)OC(=O)C1OO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.38e+08,'s^-1'), n=0.91, Ea=(43.6,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 176,
    label = "CC(=O)[CH]CC(=O)OC(COO)OO <=> CC(=O)C1CC(=O)OC1COO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.38e+08,'s^-1'), n=0.91, Ea=(43.6,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 177,
    label = "CC(=O)C[C](OO)C(=O)OC(C)OO <=> CC(=O)CC1(OO)C(=O)OC1C + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.41e+09,'s^-1'), n=1.18, Ea=(59.1,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 178,
    label = "CC(=O)C([CH]C(=O)OC(C)OO)OO <=> CC(=O)CC1C(=O)OC1(C)OO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.41e+09,'s^-1'), n=1.18, Ea=(59.1,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 179,
    label = "CC(=O)C[CH]C(=O)OC(COO)OO <=> CC(=O)CC1C(=O)OC1COO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.41e+09,'s^-1'), n=1.18, Ea=(59.1,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 180,
    label = "CCOC(=O)C([CH]C(=O)COO)OO <=> CCOC(=O)C(OO)C1OCC1=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.14e+09,'s^-1'), n=0.76, Ea=(30.39,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 181,
    label = "CCOC(=O)C[C](OO)C(=O)COO <=> CCOC(=O)CC1(OO)OCC1=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.14e+09,'s^-1'), n=0.76, Ea=(30.39,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 182,
    label = "CCOC(=O)[CH]C(OO)C(=O)COO <=> CCOC(=O)C1OCC(=O)C1OO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.22e+12,'s^-1'), n=-0.08, Ea=(17.72,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 183,
    label = "CCOC(=O)[C](CC(=O)COO)OO <=> CCOC(=O)C1(OO)CC(=O)CO1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.22e+12,'s^-1'), n=-0.08, Ea=(17.72,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 184,
    label = "CCOC(=O)CC(OO)C(=O)[CH]OO <=> CCOC(=O)CC1OC(OO)C1=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.37e+39,'s^-1'), n=-8.55, Ea=(35.68,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 185,
    label = "[CH2]C(=O)C(OO)C(OO)C(=O)OCC <=> CCOC(=O)C(OO)C1OCC1=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.37e+39,'s^-1'), n=-8.55, Ea=(35.68,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 186,
    label = "[CH2]C(=O)C(CC(=O)OC(C)OO)OO <=> CC(OO)OC(=O)CC1OCC1=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.37e+39,'s^-1'), n=-8.55, Ea=(35.68,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 187,
    label = "CCOC(=O)[CH]C(OO)C(=O)COO <=> CCOC(=O)C1OC1C(=O)COO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.29e+32,'s^-1'), n=-6.6, Ea=(20.39,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 188,
    label = "CCOC(=O)[C](OO)C(OO)C(C)=O <=> CCOC(=O)C(OO)1OC1C(=O)C + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.29e+32,'s^-1'), n=-6.6, Ea=(20.39,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 189,
    label = "CC(=O)C([CH]C(=O)OC(C)OO)OO <=> CC(OO)OC(=O)C1OC1C(=O)C + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.29e+32,'s^-1'), n=-6.6, Ea=(20.39,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 190,
    label = "CCOC(=O)C(CC(=O)[CH]OO)OO <=> CCOC(=O)C1CC(=O)C(OO)O1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.22e+12,'s^-1'), n=-0.08, Ea=(17.72,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 191,
    label = "[CH2]C(=O)C(OO)C(OO)C(=O)OCC <=> CCOC(=O)C1OCC(=O)C1OO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.22e+12,'s^-1'), n=-0.08, Ea=(17.72,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 192,
    label = "[CH2]C(=O)CC(OO)C(=O)OC(C)OO <=> CC(OO)OC(=O)C1CC(=O)CO1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.22e+12,'s^-1'), n=-0.08, Ea=(17.72,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 193,
    label = "CCOC(=O)C([CH]C(=O)COO)OO <=> CCOC(=O)C1OC1C(=O)COO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.23e+11,'s^-1'), n=0.45, Ea=(14.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 194,
    label = "CCOC(=O)C(OO)[C](OO)C(C)=O <=> CCOC(=O)C1OC(OO)1C(=O)C + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.23e+11,'s^-1'), n=0.45, Ea=(14.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 195,
    label = "CC(=O)[CH]C(OO)C(=O)OC(C)OO <=> CCOC(=O)C(OO)1OC1C(=O)C + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.23e+11,'s^-1'), n=0.45, Ea=(14.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 196,
    label = "CCOC(=O)C([CH]C(=O)COO)OO <=> C(OO)C(=O)CC(=O)C(=O)OCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.27e+10,'s^-1'), n=0.87, Ea=(29.5,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 197,
    label = "CCOC(=O)C(OO)[C](OO)C(C)=O <=> CC(=O)C(OO)C(=O)C(=O)OCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.27e+10,'s^-1'), n=0.87, Ea=(29.5,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 198,
    label = "CC(=O)[CH]C(OO)C(=O)OC(C)OO <=> CC(=O)CC(=O)C(=O)OC(OO)C + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.27e+10,'s^-1'), n=0.87, Ea=(29.5,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 199,
    label = "C[CH]OC(=O)C(CC(=O)COO)OO <=> C(OO)C(=O)CC(=O)C(=O)OCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.686,'s^-1'), n=3.63, Ea=(17.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 200,
    label = "C[CH]OC(=O)C(OO)C(OO)C(C)=O <=> CC(=O)C(OO)C(=O)C(=O)OCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.686,'s^-1'), n=3.63, Ea=(17.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 201,
    label = "C[C](OO)OC(=O)C(CC(C)=O)OO <=> CC(=O)CC(=O)C(=O)OC(OO)C + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.686,'s^-1'), n=3.63, Ea=(17.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 202,
    label = "CC(=O)[CH]C(OO)C(=O)OC(C)OO <=> CC(=O)CC(OO)C(=O)OC(=O)C + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(138,'s^-1'), n=2.66, Ea=(12.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 203,
    label = "CC(=O)[CH]CC(=O)OC(COO)OO <=> CC(=O)CCC(=O)OC(=O)C(OO) + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(138,'s^-1'), n=2.66, Ea=(12.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 204,
    label = "CC(=O)C[C](OO)C(=O)OC(C)OO <=> CC(=O)CC(OO)C(=O)OC(=O)C + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.0021,'s^-1'), n=4.67, Ea=(22,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 205,
    label = "CC(=O)C([CH]C(=O)OC(C)OO)OO <=> CC(=O)C(OO)CC(=O)OC(=O)C + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.0021,'s^-1'), n=4.67, Ea=(22,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 206,
    label = "CC(=O)C[CH]C(=O)OC(COO)OO <=> CC(=O)CCC(=O)OC(=O)C(OO) + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.0021,'s^-1'), n=4.67, Ea=(22,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 207,
    label = "CC(=O)CCC(=O)O[C](COO)OO <=> CC(=O)CCC(=O)OC(OO)C(=O) + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.01e+09,'s^-1'), n=1.1, Ea=(18.77,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

