#!/usr/bin/env python
# encoding: utf-8

name = "Sakai_DEE_submech"
shortDesc = ""
longDesc = """

"""
autoGenerated=False
entry(
    index = 0,
    label = "C4H10O <=> C2H5 + C2H5O",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(1.24e+25,'s^-1'), n=-2.29, Ea=(85330,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.553e+83,'cm^3/(mol*s)'), n=-18.724, Ea=(96839,'cal/mol'), T0=(1,'K')), alpha=9.0353e-06, T3=(505.71,'K'), T1=(1.4142e+10,'K'), T2=(2471.3,'K'), efficiencies={}, comment="""Yasunaga:JPCA114(2010)9098-9109"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Yasunaga:JPCA114(2010)9098-9109
""",
)

entry(
    index = 1,
    label = "C4H10O <=> C3H7Oa + CH3",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(2.81e+22,'s^-1'), n=-1.59, Ea=(88408,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(7.95e+78,'cm^3/(mol*s)'), n=-17.506, Ea=(99510,'cal/mol'), T0=(1,'K')), alpha=0.09413, T3=(436.65,'K'), T1=(2.6334e+07,'K'), T2=(2833.3,'K'), efficiencies={}, comment="""Yasunaga:JPCA114(2010)9098-9109"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Yasunaga:JPCA114(2010)9098-9109
""",
)

entry(
    index = 2,
    label = "C4H10O <=> C2H5OH + C2H4",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(1e+14,'s^-1'), n=0, Ea=(65200,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(5.72e+96,'cm^3/(mol*s)'), n=-23.04, Ea=(80813,'cal/mol'), T0=(1,'K')), alpha=0.0011757, T3=(379.12,'K'), T1=(1.5812e+07,'K'), T2=(4727.9,'K'), efficiencies={}, comment="""Yasunaga:JPCA114(2010)9098-9109"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Yasunaga:JPCA114(2010)9098-9109
""",
)

entry(
    index = 3,
    label = "C4H10O + H <=> C4H9Oa + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(304000,'cm^3/(mol*s)'), n=2.76, Ea=(7200,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-H/Prim:site*2, Curran:Combust.Flame129(2002)253-280"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-H/Prim:site*2, Curran:Combust.Flame129(2002)253-280
""",
)

entry(
    index = 4,
    label = "C4H10O + OH <=> C4H9Oa + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.766e+07,'cm^3/(mol*s)'), n=1.8, Ea=(855,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-OH/Prim:site*2, Curran:Combust.Flame129(2002)253-280"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-OH/Prim:site*2, Curran:Combust.Flame129(2002)253-280
""",
)

entry(
    index = 5,
    label = "C4H10O + O <=> C4H9Oa + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(40400,'cm^3/(mol*s)'), n=2.78, Ea=(3380,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-O/Prim:site*2, Curran:Combust.Flame129(2002)253-280"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-O/Prim:site*2, Curran:Combust.Flame129(2002)253-280
""",
)

entry(
    index = 6,
    label = "C4H10O + CH3 <=> C4H9Oa + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.46e-08,'cm^3/(mol*s)'), n=5.97, Ea=(5480,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-CH3/Prim:site*2, Curran:Combust.Flame129(2002)253-280"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-CH3/Prim:site*2, Curran:Combust.Flame129(2002)253-280
""",
)

entry(
    index = 7,
    label = "C4H10O + HO2 <=> C4H9Oa + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.000138,'cm^3/(mol*s)'), n=4.95, Ea=(15343,'cal/mol'), T0=(1,'K'), comment="""Mendes:JPCA118(2014)1300-1308:atom*6"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Mendes:JPCA118(2014)1300-1308:atom*6
""",
)

entry(
    index = 8,
    label = "C4H10O + CH3O <=> C4H9Oa + CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.2e+11,'cm^3/(mol*s)'), n=0, Ea=(7000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-CH3O/Prim:site*2, Curran:Combust.Flame129(2002)253-280"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-CH3O/Prim:site*2, Curran:Combust.Flame129(2002)253-280
""",
)

entry(
    index = 9,
    label = "C4H10O + C2H5O <=> C4H9Oa + C2H5OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.2e+11,'cm^3/(mol*s)'), n=0, Ea=(7000,'cal/mol'), T0=(1,'K'), comment="""C4H10O+CH3O=C4H9Oa+CH3OH"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+CH3O=C4H9Oa+CH3OH
""",
)

entry(
    index = 10,
    label = "C4H10O + O2 <=> C4H9Oa + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.2e+13,'cm^3/(mol*s)'), n=0, Ea=(50760,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-O2/Prim:site*2, Curran:Combust.Flame129(2002)253-280"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-O2/Prim:site*2, Curran:Combust.Flame129(2002)253-280
""",
)

entry(
    index = 11,
    label = "C4H10O + C2H5 <=> C4H9Oa + C2H6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(13400,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-C2H5/Prim:site*2, Curran:Combust.Flame129(2002)253-280"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-C2H5/Prim:site*2, Curran:Combust.Flame129(2002)253-280
""",
)

entry(
    index = 12,
    label = "C4H10O + C2H3 <=> C4H9Oa + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(18000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-C2H3/Prim:site*2, Curran:Combust.Flame129(2002)253-280"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-C2H3/Prim:site*2, Curran:Combust.Flame129(2002)253-280
""",
)

entry(
    index = 13,
    label = "C4H10O + CH3O2 <=> C4H9Oa + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.68e+13,'cm^3/(mol*s)'), n=0, Ea=(20440,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-CH3OO/Prim:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-CH3OO/Prim:site*2
""",
)

entry(
    index = 14,
    label = "C4H10O + C2H5O2 <=> C4H9Oa + C2H5O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.21e+13,'cm^3/(mol*s)'), n=0, Ea=(20430,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-RO2/Prim:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-RO2/Prim:site*2
""",
)

entry(
    index = 15,
    label = "C4H10O + CH3CO3 <=> C4H9Oa + CH3CO3H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.21e+13,'cm^3/(mol*s)'), n=0, Ea=(20430,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-RO2/Prim:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-RO2/Prim:site*2
""",
)

entry(
    index = 16,
    label = "C4H10O + O2CHO <=> C4H9Oa + HO2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.21e+13,'cm^3/(mol*s)'), n=0, Ea=(20430,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-RO2/Prim:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-RO2/Prim:site*2
""",
)

entry(
    index = 17,
    label = "C4H10O + C4H9OaOO <=> C4H9Oa + C4H9OaOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.21e+13,'cm^3/(mol*s)'), n=0, Ea=(20430,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-RO2/Prim:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-RO2/Prim:site*2
""",
)

entry(
    index = 18,
    label = "C4H10O + C4H9ObOO <=> C4H9Oa + C4H9ObOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.21e+13,'cm^3/(mol*s)'), n=0, Ea=(20430,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-RO2/Prim:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-RO2/Prim:site*2
""",
)

entry(
    index = 19,
    label = "C4H10O + H <=> C4H9Ob + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.148e+06,'cm^3/(mol*s)'), n=2.49, Ea=(2300,'cal/mol'), T0=(1,'K'), comment="""Ogura:PCCP9(2007)5133-5142:atom*4"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Ogura:PCCP9(2007)5133-5142:atom*4
""",
)

entry(
    index = 20,
    label = "C4H10O + OH <=> C4H9Ob + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(360000,'cm^3/(mol*s)'), n=2.3, Ea=(-1800,'cal/mol'), T0=(1,'K'), comment="""Ogura:PCCP9(2007)5133-5142:atom*4, A/2 C4H10O+OH=C4H9Ob+H2O                             7.200E+05   2.300   -1800.0 !Ogura:PCCP9(2007)5133-5142:atom*4"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Ogura:PCCP9(2007)5133-5142:atom*4, A/2 C4H10O+OH=C4H9Ob+H2O                             7.200E+05   2.300   -1800.0 !Ogura:PCCP9(2007)5133-5142:atom*4
""",
)

entry(
    index = 21,
    label = "C4H10O + O <=> C4H9Ob + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(119000,'cm^3/(mol*s)'), n=2.71, Ea=(756,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-O/CH2-C|O:site*2, Zhou:Combust.Flame158(2011)726-731"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-O/CH2-C|O:site*2, Zhou:Combust.Flame158(2011)726-731
""",
)

entry(
    index = 22,
    label = "C4H10O + CH3 <=> C4H9Ob + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(67800,'cm^3/(mol*s)'), n=2.26, Ea=(5937,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-CH3/CH2-C|O:site*2, Zhou:Combust.Flame158(2011)726-731"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-CH3/CH2-C|O:site*2, Zhou:Combust.Flame158(2011)726-731
""",
)

entry(
    index = 23,
    label = "C4H10O + HO2 <=> C4H9Ob + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.724,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""Mendes:JPCA118(2014)1300-1308:atom*4, A*2 C4H10O+HO2=C4H9Ob+H2O2                           3.620E-01   3.980    9058.0 !Mendes:JPCA118(2014)1300-1308:atom*4"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Mendes:JPCA118(2014)1300-1308:atom*4, A*2 C4H10O+HO2=C4H9Ob+H2O2                           3.620E-01   3.980    9058.0 !Mendes:JPCA118(2014)1300-1308:atom*4
""",
)

entry(
    index = 24,
    label = "C4H10O + CH3O <=> C4H9Ob + CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.25e+11,'cm^3/(mol*s)'), n=0, Ea=(3650,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-CH3O/CH2-C|O:site*2, Zhou:Combust.Flame158(2011)726-731"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-CH3O/CH2-C|O:site*2, Zhou:Combust.Flame158(2011)726-731
""",
)

entry(
    index = 25,
    label = "C4H10O + C2H5O <=> C4H9Ob + C2H5OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.25e+11,'cm^3/(mol*s)'), n=0, Ea=(3650,'cal/mol'), T0=(1,'K'), comment="""C4H10O+CH3O=C4H9Ob+CH3OH"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+CH3O=C4H9Ob+CH3OH
""",
)

entry(
    index = 26,
    label = "C4H10O + O2 <=> C4H9Ob + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(38500,'cal/mol'), T0=(1,'K'), comment="""Abou-Rachid:J.Mol.Struct.(Theochem)621(2003)293-304"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Abou-Rachid:J.Mol.Struct.(Theochem)621(2003)293-304
""",
)

entry(
    index = 27,
    label = "C4H10O + C2H5 <=> C4H9Ob + C2H6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.25e+11,'cm^3/(mol*s)'), n=0, Ea=(9050,'cal/mol'), T0=(1,'K'), comment="""KUCRS:O-neighbor site:site*2, Zhou:Combust.Flame158(2011)726-731"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:O-neighbor site:site*2, Zhou:Combust.Flame158(2011)726-731
""",
)

entry(
    index = 28,
    label = "C4H10O + C2H3 <=> C4H9Ob + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(15450,'cal/mol'), T0=(1,'K'), comment="""KUCRS:O-neighbor site:site*2, Zhou:Combust.Flame158(2011)726-731"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:O-neighbor site:site*2, Zhou:Combust.Flame158(2011)726-731
""",
)

entry(
    index = 29,
    label = "C4H10O + CH3O2 <=> C4H9Ob + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.724,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2
""",
)

entry(
    index = 30,
    label = "C4H10O + C2H5O2 <=> C4H9Ob + C2H5O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.724,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2
""",
)

entry(
    index = 31,
    label = "C4H10O + CH3CO3 <=> C4H9Ob + CH3CO3H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.724,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2
""",
)

entry(
    index = 32,
    label = "C4H10O + O2CHO <=> C4H9Ob + HO2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.724,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2
""",
)

entry(
    index = 33,
    label = "C4H10O + C4H9OaOO <=> C4H9Ob + C4H9OaOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.724,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2
""",
)

entry(
    index = 34,
    label = "C4H10O + C4H9ObOO <=> C4H9Ob + C4H9ObOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.724,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2
""",
)

entry(
    index = 35,
    label = "C4H9Oa <=> C2H4 + C2H5O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.408e+12,'s^-1'), n=0.17, Ea=(24236.7,'cal/mol'), T0=(1,'K'), comment="""CBSQB3:TST"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
CBSQB3:TST
""",
)

entry(
    index = 36,
    label = "C4H9Ob <=> CH3CHO + C2H5",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.923e+15,'s^-1'), n=-0.504, Ea=(23346.1,'cal/mol'), T0=(1,'K'), comment="""CBSQB3:TST"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
CBSQB3:TST
""",
)

entry(
    index = 37,
    label = "C4H9Oa <=> C4H9Ob",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(10.93,'s^-1'), n=2.927, Ea=(12135.7,'cal/mol'), T0=(1,'K'), comment="""CBSQB3:TST"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
CBSQB3:TST
""",
)

entry(
    index = 38,
    label = "C4H9OaOO <=> C4H9Oa + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.394e+26,'s^-1'), n=-3.36, Ea=(36067.8,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pRO2:*dis, A*2 C4H9OaOO=C4H9Oa+O2                               6.970E+25  -3.360   36067.8 !Sakai:PCI35(2015)161-169:pRO2:*dis"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pRO2:*dis, A*2 C4H9OaOO=C4H9Oa+O2                               6.970E+25  -3.360   36067.8 !Sakai:PCI35(2015)161-169:pRO2:*dis
""",
)

entry(
    index = 39,
    label = "C4H9ObOO <=> C4H9Ob + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.9e+18,'s^-1'), n=-0.99, Ea=(38595.5,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:sRO2:*dis, A*2 C4H9ObOO=C4H9Ob+O2                               2.450E+18  -0.990   38595.5 !Sakai:PCI35(2015)161-169:sRO2:*dis"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:sRO2:*dis, A*2 C4H9ObOO=C4H9Ob+O2                               2.450E+18  -0.990   38595.5 !Sakai:PCI35(2015)161-169:sRO2:*dis
""",
)

entry(
    index = 40,
    label = "C4H9OaOO <=> C4H8O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.15e+09,'s^-1'), n=1.06, Ea=(31276.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pRO2:*ho2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pRO2:*ho2
""",
)

entry(
    index = 41,
    label = "C4H9OaOO <=> C4H8OaOOHb",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(668000,'s^-1'), n=1.69, Ea=(22886.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pRO2:*14hs"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pRO2:*14hs
""",
)

entry(
    index = 42,
    label = "C4H9OaOO <=> C4H8OaOOHc",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.24e+06,'s^-1'), n=1.28, Ea=(14623.8,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pRO2:*16hs"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pRO2:*16hs
""",
)

entry(
    index = 43,
    label = "C4H9OaOO <=> C4H8OaOOHd",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(208000,'s^-1'), n=1.42, Ea=(20871.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pRO2:*17hs"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pRO2:*17hs
""",
)

entry(
    index = 44,
    label = "C4H9ObOO <=> C4H8O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.46e+11,'s^-1'), n=0.56, Ea=(29573.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:sRO2:*ho2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:sRO2:*ho2
""",
)

entry(
    index = 45,
    label = "C4H9ObOO <=> C4H8ObOOHc",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.83e+06,'s^-1'), n=1.38, Ea=(13882.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:sRO2:*15hs"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:sRO2:*15hs
""",
)

entry(
    index = 46,
    label = "C4H9ObOO <=> C4H8ObOOHd",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.14e+06,'s^-1'), n=1.4, Ea=(20164.2,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:sRO2:*16hs"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:sRO2:*16hs
""",
)

entry(
    index = 47,
    label = "C4H9ObOO <=> C4H8ObOOHa",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(481000,'s^-1'), n=1.92, Ea=(30857.3,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:sRO2:*14hs"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:sRO2:*14hs
""",
)

entry(
    index = 48,
    label = "C4H8OaOOHb <=> C4H8OcyOab + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.12e+10,'s^-1'), n=0.6, Ea=(10003.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pQOOH14hs:*rc"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pQOOH14hs:*rc
""",
)

entry(
    index = 49,
    label = "C4H8OaOOHc <=> C4H8OcyOac + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.97e+09,'s^-1'), n=0.73, Ea=(9377.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pQOOH16hs:*rc"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pQOOH16hs:*rc
""",
)

entry(
    index = 50,
    label = "C4H8OaOOHd <=> C4H8OcyOad + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.59e+08,'s^-1'), n=0.68, Ea=(12213.4,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pQOOH17hs:*rc"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pQOOH17hs:*rc
""",
)

entry(
    index = 51,
    label = "C4H8ObOOHc <=> CH3CHO + CH3CHO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.3e+08,'s^-1'), n=1.3, Ea=(14091.3,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:sQOOH15hs:*co"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:sQOOH15hs:*co
""",
)

entry(
    index = 52,
    label = "C4H8ObOOHc <=> C4H8OcyObc + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.14e+11,'s^-1'), n=0.2, Ea=(19927.7,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:sQOOH15hs:rc"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:sQOOH15hs:rc
""",
)

entry(
    index = 53,
    label = "C4H8ObOOHd <=> C4H8OcyOac + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.68e+10,'s^-1'), n=0.27, Ea=(14927.9,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:sQOOH16hs:*rc"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:sQOOH16hs:*rc
""",
)

entry(
    index = 54,
    label = "C4H8ObOOHa <=> C4H8OcyOab + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.07e+10,'s^-1'), n=0.63, Ea=(12036.5,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:sQOOH14hs:*rc"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:sQOOH14hs:*rc
""",
)

entry(
    index = 55,
    label = "C4H8OaOOHbOO <=> C4H8OaOOHb + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.9e+18,'s^-1'), n=-0.99, Ea=(38595.5,'cal/mol'), T0=(1,'K'), comment="""C4H9ObOO=C4H9Ob+O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9ObOO=C4H9Ob+O2
""",
)

entry(
    index = 56,
    label = "C4H8OaOOHcOO <=> C4H8OaOOHc + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.9e+18,'s^-1'), n=-0.99, Ea=(38595.5,'cal/mol'), T0=(1,'K'), comment="""C4H9ObOO=C4H9Ob+O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9ObOO=C4H9Ob+O2
""",
)

entry(
    index = 57,
    label = "C4H8OaOOHdOO <=> C4H8OaOOHd + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.394e+26,'s^-1'), n=-3.36, Ea=(36067.8,'cal/mol'), T0=(1,'K'), comment="""C4H9OaOO=C4H9Oa+O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9OaOO=C4H9Oa+O2
""",
)

entry(
    index = 58,
    label = "C4H8ObOOHcOO <=> C4H8ObOOHc + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.9e+18,'s^-1'), n=-0.99, Ea=(38595.5,'cal/mol'), T0=(1,'K'), comment="""C4H9ObOO=C4H9Ob+O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9ObOO=C4H9Ob+O2
""",
)

entry(
    index = 59,
    label = "C4H8ObOOHdOO <=> C4H8ObOOHd + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.394e+26,'s^-1'), n=-3.36, Ea=(36067.8,'cal/mol'), T0=(1,'K'), comment="""C4H9OaOO=C4H9Oa+O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9OaOO=C4H9Oa+O2
""",
)

entry(
    index = 60,
    label = "C4H8ObOOHaOO <=> C4H8ObOOHa + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.394e+26,'s^-1'), n=-3.36, Ea=(36067.8,'cal/mol'), T0=(1,'K'), comment="""C4H9OaOO=C4H9Oa+O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9OaOO=C4H9Oa+O2
""",
)

entry(
    index = 61,
    label = "C4H8OcyOab + OH <=> H2O + CH3CHO + CH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(360000,'cm^3/(mol*s)'), n=2.3, Ea=(-1800,'cal/mol'), T0=(1,'K'), comment="""C4H10O+OH=C4H9Ob+H2O"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+OH=C4H9Ob+H2O
""",
)

entry(
    index = 62,
    label = "C4H8OcyOab + HO2 <=> H2O2 + CH3CHO + CH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.724,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2
""",
)

entry(
    index = 63,
    label = "C4H8OcyOab + OH <=> H2O + CH2CO + C2H5O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.25e+06,'cm^3/(mol*s)'), n=1.9, Ea=(-2801,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-OH/CH-C2|O"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-OH/CH-C2|O
""",
)

entry(
    index = 64,
    label = "C4H8OcyOab + HO2 <=> H2O2 + CH2CO + C2H5O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(14660,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-HO2/CH-C2|O"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-HO2/CH-C2|O
""",
)

entry(
    index = 65,
    label = "C4H8OcyOac + OH <=> H2O + CH3CHO + CH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(360000,'cm^3/(mol*s)'), n=2.3, Ea=(-1800,'cal/mol'), T0=(1,'K'), comment="""C4H10O+OH=C4H9Ob+H2O"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+OH=C4H9Ob+H2O
""",
)

entry(
    index = 66,
    label = "C4H8OcyOac + HO2 <=> H2O2 + CH3CHO + CH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.724,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2
""",
)

entry(
    index = 67,
    label = "C4H8OcyOac + OH <=> H2O + C2H4 + CH3CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.25e+06,'cm^3/(mol*s)'), n=1.9, Ea=(-2801,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-OH/CH-C2|O"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-OH/CH-C2|O
""",
)

entry(
    index = 68,
    label = "C4H8OcyOac + HO2 <=> H2O2 + C2H4 + CH3CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(14660,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-HO2/CH-C2|O"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-HO2/CH-C2|O
""",
)

entry(
    index = 69,
    label = "C4H8OcyOad + OH <=> H2O + C2H4 + OCH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(720000,'cm^3/(mol*s)'), n=2.3, Ea=(-1800,'cal/mol'), T0=(1,'K'), comment="""C4H10O+OH=C4H9Ob+H2O:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+OH=C4H9Ob+H2O:site*2
""",
)

entry(
    index = 70,
    label = "C4H8OcyOad + HO2 <=> H2O2 + C2H4 + OCH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.448,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2:site*2
""",
)

entry(
    index = 71,
    label = "C4H8OcyObc + OH <=> H2O + CH3CHO + CH3CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.5e+06,'cm^3/(mol*s)'), n=1.9, Ea=(-2801,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-OH/CH-C2|O:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-OH/CH-C2|O:site*2
""",
)

entry(
    index = 72,
    label = "C4H8OcyObc + HO2 <=> H2O2 + CH3CHO + CH3CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+13,'cm^3/(mol*s)'), n=0, Ea=(14660,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-HO2/CH-C2|O:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-HO2/CH-C2|O:site*2
""",
)

entry(
    index = 73,
    label = "C4H8OaOOHbOO <=> bC4H7OcdOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.83e+06,'s^-1'), n=1.38, Ea=(13882.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:sRO2:*15hs"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:sRO2:*15hs
""",
)

entry(
    index = 74,
    label = "C4H8OaOOHbOO <=> C4H8ObOOHaOO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.34e+09,'s^-1'), n=0, Ea=(14129.1,'cal/mol'), T0=(1,'K'), comment="""Miyoshi:JPCA115(2011)3301-3325:*ho-beta-sp"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Miyoshi:JPCA115(2011)3301-3325:*ho-beta-sp
""",
)

entry(
    index = 75,
    label = "C4H8OaOOHcOO <=> aCHOC3H6OcOOH + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.48e+10,'s^-1'), n=0, Ea=(17884.9,'cal/mol'), T0=(1,'K'), comment="""Miyoshi:JPCA115(2011)3301-3325:*h4-delta-sp"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Miyoshi:JPCA115(2011)3301-3325:*h4-delta-sp
""",
)

entry(
    index = 76,
    label = "C4H8OaOOHcOO <=> bC4H7OacOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.83e+06,'s^-1'), n=1.38, Ea=(13882.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:sRO2:*15hs"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:sRO2:*15hs
""",
)

entry(
    index = 77,
    label = "C4H8ObOOHcOO <=> bCOC3H7OcOOH + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.83e+06,'s^-1'), n=1.38, Ea=(13882.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:sRO2:*15hs"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:sRO2:*15hs
""",
)

entry(
    index = 78,
    label = "C4H8ObOOHaOO <=> bC4H7OcdOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.24e+06,'s^-1'), n=1.28, Ea=(14623.8,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pRO2:*16hs"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pRO2:*16hs
""",
)

entry(
    index = 79,
    label = "C4H8OaOOHdOO <=> aCHOC3H6OdOOH + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.19e+10,'s^-1'), n=0, Ea=(19275.9,'cal/mol'), T0=(1,'K'), comment="""Miyoshi:JPCA115(2011)3301-3325:*h5-ipsiron-pp"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Miyoshi:JPCA115(2011)3301-3325:*h5-ipsiron-pp
""",
)

entry(
    index = 80,
    label = "C4H8OaOOHdOO <=> bC4H7OadOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.24e+06,'s^-1'), n=1.28, Ea=(14623.8,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pRO2:*16hs"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pRO2:*16hs
""",
)

entry(
    index = 81,
    label = "C4H8ObOOHdOO <=> bCOC3H7OdOOH + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.24e+06,'s^-1'), n=1.28, Ea=(14623.8,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pRO2:*16hs"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pRO2:*16hs
""",
)

entry(
    index = 82,
    label = "C4H8ObOOHdOO <=> C4H8OaOOHcOO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.22e+08,'s^-1'), n=0, Ea=(14844.5,'cal/mol'), T0=(1,'K'), comment="""Miyoshi:JPCA115(2011)3301-3325:*ho-delta-ps"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Miyoshi:JPCA115(2011)3301-3325:*ho-delta-ps
""",
)

entry(
    index = 83,
    label = "aCHOC3H6OcOOH <=> OH + aCHOC3H6OcO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+16,'s^-1'), n=0, Ea=(39000,'cal/mol'), T0=(1,'K'), comment="""base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500
""",
)

entry(
    index = 84,
    label = "aCHOC3H6OdOOH <=> OH + aCHOC3H6OdO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+16,'s^-1'), n=0, Ea=(39000,'cal/mol'), T0=(1,'K'), comment="""base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500
""",
)

entry(
    index = 85,
    label = "bCOC3H7OcOOH <=> OH + bCOC3H7OcO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+16,'s^-1'), n=0, Ea=(39000,'cal/mol'), T0=(1,'K'), comment="""base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500
""",
)

entry(
    index = 86,
    label = "bCOC3H7OdOOH <=> OH + bCOC3H7OdO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+16,'s^-1'), n=0, Ea=(39000,'cal/mol'), T0=(1,'K'), comment="""base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500
""",
)

entry(
    index = 87,
    label = "aCHOC3H6OcO <=> HCOCH2OCHO + CH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Dcmp/RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Dcmp/RO
""",
)

entry(
    index = 88,
    label = "aCHOC3H6OcO <=> CH3CHO + OCH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Dcmp/RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Dcmp/RO
""",
)

entry(
    index = 89,
    label = "aCHOC3H6OdO <=> CH2O + CH2OCH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Dcmp/RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Dcmp/RO
""",
)

entry(
    index = 90,
    label = "bCOC3H7OcO <=> CH3CHO + CH3CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Dcmp/RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Dcmp/RO
""",
)

entry(
    index = 91,
    label = "bCOC3H7OdO <=> CH2O + CH2OCOCH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Dcmp/RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Dcmp/RO
""",
)

entry(
    index = 92,
    label = "bC4H7OcdOOH <=> C4H8ObOOHcyOac + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.97e+09,'s^-1'), n=0.73, Ea=(9377.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pQOOH16hs:*rc"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pQOOH16hs:*rc
""",
)

entry(
    index = 93,
    label = "C4H8ObOOHcyOac <=> OCH2CHO + CH3CHO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+16,'s^-1'), n=0, Ea=(39000,'cal/mol'), T0=(1,'K'), comment="""base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500
""",
)

entry(
    index = 94,
    label = "bC4H7OacOOH <=> C4H8OcOOHcyOab + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.12e+10,'s^-1'), n=0.6, Ea=(10003.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pQOOH14hs:*rc"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pQOOH14hs:*rc
""",
)

entry(
    index = 95,
    label = "C4H8OcOOHcyOab <=> CH3CHO + OCH2CHO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+16,'s^-1'), n=0, Ea=(39000,'cal/mol'), T0=(1,'K'), comment="""base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500
""",
)

entry(
    index = 96,
    label = "bC4H7OadOOH <=> C4H8OdOOHcyOab + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.12e+10,'s^-1'), n=0.6, Ea=(10003.6,'cal/mol'), T0=(1,'K'), comment="""Sakai:PCI35(2015)161-169:pQOOH14hs:*rc"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Sakai:PCI35(2015)161-169:pQOOH14hs:*rc
""",
)

# entry(
#     index = 97,
#     label = "C4H8OdOOHcyOab <=> CH2CHO + CH2O + CH2O + OH",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(2e+16,'s^-1'), n=0, Ea=(39000,'cal/mol'), T0=(1,'K'), comment="""base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500"""),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500
# """,
# )

entry(
    index = 98,
    label = "CH3 + C4H9OaOO <=> C4H9OaO + CH3O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 99,
    label = "CH3 + C4H9ObOO <=> C4H9ObO + CH3O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 100,
    label = "C4H9Oa + HO2 <=> C4H9OaO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 101,
    label = "C4H9Oa + CH3O2 <=> C4H9OaO + CH3O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 102,
    label = "C4H9Oa + C4H9OaOO <=> C4H9OaO + C4H9OaO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 103,
    label = "C4H9Oa + C4H9ObOO <=> C4H9ObO + C4H9OaO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 104,
    label = "C4H9Ob + HO2 <=> C4H9ObO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 105,
    label = "C4H9Ob + CH3O2 <=> C4H9ObO + CH3O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 106,
    label = "C4H9Ob + C4H9OaOO <=> C4H9OaO + C4H9ObO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 107,
    label = "C4H9Ob + C4H9ObOO <=> C4H9ObO + C4H9ObO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 108,
    label = "C4H9OaOO + CH3O2 <=> C4H9OaO + CH3O + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1860,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Cplx/RO2/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Cplx/RO2/RO2
""",
)

entry(
    index = 109,
    label = "C4H9OaOO + C4H9OaOO <=> C4H9OaO + C4H9OaO + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1860,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Cplx/RO2/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Cplx/RO2/RO2
""",
)

entry(
    index = 110,
    label = "C4H9OaOO + C4H9ObOO <=> C4H9OaO + C4H9ObO + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1860,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Cplx/RO2/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Cplx/RO2/RO2
""",
)

entry(
    index = 111,
    label = "C4H9OaOO + C2H5O2 <=> C4H9OaO + C2H5O + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1860,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Cplx/RO2/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Cplx/RO2/RO2
""",
)

entry(
    index = 112,
    label = "C4H9OaOO + CH3CO3 <=> C4H9OaO + CH3CO2 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1860,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Cplx/RO2/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Cplx/RO2/RO2
""",
)

entry(
    index = 113,
    label = "C4H9OaOO + O2CHO <=> C4H9OaO + OCHO + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1860,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Cplx/RO2/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Cplx/RO2/RO2
""",
)

entry(
    index = 114,
    label = "C4H9ObOO + CH3O2 <=> C4H9ObO + CH3O + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1860,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Cplx/RO2/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Cplx/RO2/RO2
""",
)

entry(
    index = 115,
    label = "C4H9ObOO + C4H9ObOO <=> C4H9ObO + C4H9ObO + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1860,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Cplx/RO2/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Cplx/RO2/RO2
""",
)

entry(
    index = 116,
    label = "C4H9ObOO + C2H5O2 <=> C4H9ObO + C2H5O + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1860,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Cplx/RO2/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Cplx/RO2/RO2
""",
)

entry(
    index = 117,
    label = "C4H9ObOO + CH3CO3 <=> C4H9ObO + CH3CO2 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1860,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Cplx/RO2/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Cplx/RO2/RO2
""",
)

entry(
    index = 118,
    label = "C4H9ObOO + O2CHO <=> C4H9ObO + OCHO + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1860,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Cplx/RO2/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Cplx/RO2/RO2
""",
)

entry(
    index = 119,
    label = "HO2 + C4H9OaOO <=> O2 + C4H9OaOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.75e+10,'cm^3/(mol*s)'), n=0, Ea=(-3275,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-RO2/HO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-RO2/HO2
""",
)

entry(
    index = 120,
    label = "HO2 + C4H9ObOO <=> O2 + C4H9ObOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.75e+10,'cm^3/(mol*s)'), n=0, Ea=(-3275,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-RO2/HO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-RO2/HO2
""",
)

entry(
    index = 121,
    label = "H2O2 + C4H9OaOO <=> HO2 + C4H9OaOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.4e+12,'cm^3/(mol*s)'), n=0, Ea=(10000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-RO2/H2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-RO2/H2O2
""",
)

entry(
    index = 122,
    label = "H2O2 + C4H9ObOO <=> HO2 + C4H9ObOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.4e+12,'cm^3/(mol*s)'), n=0, Ea=(10000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-RO2/H2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-RO2/H2O2
""",
)

entry(
    index = 123,
    label = "C4H9OaOOH <=> OH + C4H9OaO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+16,'s^-1'), n=0, Ea=(39000,'cal/mol'), T0=(1,'K'), comment="""base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500
""",
)

entry(
    index = 124,
    label = "C4H9ObOOH <=> OH + C4H9ObO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+16,'s^-1'), n=0, Ea=(39000,'cal/mol'), T0=(1,'K'), comment="""base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500
""",
)

entry(
    index = 125,
    label = "C4H9OaO <=> CH2O + C3H7Oa",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Dcmp/RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Dcmp/RO
""",
)

entry(
    index = 126,
    label = "C4H9ObO <=> CH3CH2OCHO + CH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Dcmp/RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Dcmp/RO
""",
)

entry(
    index = 127,
    label = "C4H9ObO <=> CH3CHO + C2H5O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Dcmp/RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Dcmp/RO
""",
)

entry(
    index = 128,
    label = "C4H8O + H <=> C4H7Od + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(574000,'cm^3/(mol*s)'), n=2.49, Ea=(2300,'cal/mol'), T0=(1,'K'), comment="""C4H10O+H=C4H9Ob+H2:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+H=C4H9Ob+H2:site/2
""",
)

entry(
    index = 129,
    label = "C4H8O + OH <=> C4H7Od + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(180000,'cm^3/(mol*s)'), n=2.3, Ea=(-1800,'cal/mol'), T0=(1,'K'), comment="""C4H10O+OH=C4H9Ob+H2O:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+OH=C4H9Ob+H2O:site/2
""",
)

entry(
    index = 130,
    label = "C4H8O + O <=> C3H7Oa + HCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.3e+12,'cm^3/(mol*s)'), n=0, Ea=(1710,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Adtn/O/DB/nosb"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Adtn/O/DB/nosb
""",
)

entry(
    index = 131,
    label = "C4H8O + O <=> C4H7Od + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(59500,'cm^3/(mol*s)'), n=2.71, Ea=(756,'cal/mol'), T0=(1,'K'), comment="""C4H10O+O=C4H9Ob+OH:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+O=C4H9Ob+OH:site/2
""",
)

entry(
    index = 132,
    label = "C4H8O + CH3 <=> C4H7Od + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(33900,'cm^3/(mol*s)'), n=2.26, Ea=(5937,'cal/mol'), T0=(1,'K'), comment="""C4H10O+CH3=C4H9Ob+CH4:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+CH3=C4H9Ob+CH4:site/2
""",
)

entry(
    index = 133,
    label = "C4H8O + HO2 <=> C4H7Od + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.362,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2:site/2
""",
)

entry(
    index = 134,
    label = "C4H8O + CH3O <=> C4H7Od + CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.125e+11,'cm^3/(mol*s)'), n=0, Ea=(3650,'cal/mol'), T0=(1,'K'), comment="""C4H10O+CH3O=C4H9Ob+CH3OH:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+CH3O=C4H9Ob+CH3OH:site/2
""",
)

entry(
    index = 135,
    label = "C4H8O + C2H5O <=> C4H7Od + C2H5OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.125e+11,'cm^3/(mol*s)'), n=0, Ea=(3650,'cal/mol'), T0=(1,'K'), comment="""C4H10O+C2H5O=C4H9Ob+C2H5OH:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+C2H5O=C4H9Ob+C2H5OH:site/2
""",
)

entry(
    index = 136,
    label = "C4H8O + O2 <=> C4H7Od + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(38500,'cal/mol'), T0=(1,'K'), comment="""C4H10O+O2=C4H9Ob+HO2:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+O2=C4H9Ob+HO2:site/2
""",
)

entry(
    index = 137,
    label = "C4H8O + C2H5 <=> C4H7Od + C2H6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.25e+10,'cm^3/(mol*s)'), n=0, Ea=(9050,'cal/mol'), T0=(1,'K'), comment="""C4H10O+C2H5=C4H9Ob+C2H6:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+C2H5=C4H9Ob+C2H6:site/2
""",
)

entry(
    index = 138,
    label = "C4H8O + C2H3 <=> C4H7Od + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+11,'cm^3/(mol*s)'), n=0, Ea=(15450,'cal/mol'), T0=(1,'K'), comment="""C4H10O+C2H3=C4H9Ob+C2H4:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+C2H3=C4H9Ob+C2H4:site/2
""",
)

entry(
    index = 139,
    label = "C4H8O + CH3O2 <=> C4H7Od + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.362,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+CH3O2=C4H9Ob+CH3O2H:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+CH3O2=C4H9Ob+CH3O2H:site/2
""",
)

entry(
    index = 140,
    label = "C4H8O + C2H5O2 <=> C4H7Od + C2H5O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.362,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+C2H5O2=C4H9Ob+C2H5O2H:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+C2H5O2=C4H9Ob+C2H5O2H:site/2
""",
)

entry(
    index = 141,
    label = "C4H8O + CH3CO3 <=> C4H7Od + CH3CO3H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.362,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+CH3CO3=C4H9Ob+CH3CO3H:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+CH3CO3=C4H9Ob+CH3CO3H:site/2
""",
)

entry(
    index = 142,
    label = "C4H8O + O2CHO <=> C4H7Od + HO2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.362,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+O2CHO=C4H9Ob+HO2CHO:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+O2CHO=C4H9Ob+HO2CHO:site/2
""",
)

entry(
    index = 143,
    label = "C4H8O + C4H9OaOO <=> C4H7Od + C4H9OaOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.362,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+C4H9OaOO=C4H9Ob+C4H9OaOOH:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+C4H9OaOO=C4H9Ob+C4H9OaOOH:site/2
""",
)

entry(
    index = 144,
    label = "C4H8O + C4H9ObOO <=> C4H7Od + C4H9ObOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.362,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+C4H9ObOO=C4H9Ob+C4H9ObOOH:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+C4H9ObOO=C4H9Ob+C4H9ObOOH:site/2
""",
)

entry(
    index = 145,
    label = "C2H3 + CH3CHO <=> C4H7Od",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(5000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/.CO-C"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/.CO-C
""",
)

entry(
    index = 146,
    label = "CH2O + C2H5 <=> C3H7Oa",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.641e+15,'cm^3/(mol*s)'), n=-0.504, Ea=(23346.1,'cal/mol'), T0=(1,'K'), comment="""C4H9Ob=CH3CHO+C2H5"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9Ob=CH3CHO+C2H5
""",
)

entry(
    index = 147,
    label = "C3H7Oa + HO2 <=> C3H7OaO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 148,
    label = "C3H7Oa + CH3O2 <=> C3H7OaO + CH3O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 149,
    label = "C3H7Oa + O2 <=> C3H7OaOO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K'), comment="""base mechanism:CH3OCH2+O2<=>CH3OCH2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
base mechanism:CH3OCH2+O2<=>CH3OCH2O2
""",
)

entry(
    index = 150,
    label = "C3H7OaOO <=> C3H6OaOOHb",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.83e+06,'s^-1'), n=1.38, Ea=(13882.6,'cal/mol'), T0=(1,'K'), comment="""C4H9ObOO=C4H8ObOOHc"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9ObOO=C4H8ObOOHc
""",
)

entry(
    index = 151,
    label = "C3H7OaOO <=> C3H6OaOOHc",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.14e+06,'s^-1'), n=1.4, Ea=(20164.2,'cal/mol'), T0=(1,'K'), comment="""C4H9ObOO=C4H8ObOOHd"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9ObOO=C4H8ObOOHd
""",
)

entry(
    index = 152,
    label = "HO2 + C3H7OaOO <=> O2 + C3H7OaOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.75e+10,'cm^3/(mol*s)'), n=0, Ea=(-3275,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-RO2/HO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-RO2/HO2
""",
)

entry(
    index = 153,
    label = "H2O2 + C3H7OaOO <=> HO2 + C3H7OaOOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.4e+12,'cm^3/(mol*s)'), n=0, Ea=(10000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-RO2/H2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-RO2/H2O2
""",
)

entry(
    index = 154,
    label = "C3H7OaOO + CH3 <=> C3H7OaO + CH3O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(-1000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Oabs/by-R/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Oabs/by-R/RO2
""",
)

entry(
    index = 155,
    label = "C3H7OaOO + CH3O2 <=> C3H7OaO + CH3O + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+16,'cm^3/(mol*s)'), n=-1.61, Ea=(1860,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Cplx/RO2/RO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Cplx/RO2/RO2
""",
)

entry(
    index = 156,
    label = "C3H7OaOOH <=> OH + C3H7OaO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+16,'s^-1'), n=0, Ea=(39000,'cal/mol'), T0=(1,'K'), comment="""DME, E-1050"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
DME, E-1050
""",
)

entry(
    index = 157,
    label = "C3H7OaO <=> CH2O + C2H5O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Dcmp/RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Dcmp/RO
""",
)

entry(
    index = 158,
    label = "C3H6OaOOHb <=> CH3CHO + CH2O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.3e+08,'s^-1'), n=1.3, Ea=(14091.3,'cal/mol'), T0=(1,'K'), comment="""C4H8ObOOHc=CH3CHO+CH3CHO+OH"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H8ObOOHc=CH3CHO+CH3CHO+OH
""",
)

entry(
    index = 159,
    label = "C3H6OaOOHb <=> C3H6OcyOab + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.14e+11,'s^-1'), n=0.2, Ea=(19927.7,'cal/mol'), T0=(1,'K'), comment="""C4H8ObOOHc=C4H8OcyObc+OH"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H8ObOOHc=C4H8OcyObc+OH
""",
)

entry(
    index = 160,
    label = "C3H6OaOOHbOO <=> C3H6OaOOHb + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.9e+18,'s^-1'), n=-0.99, Ea=(38595.5,'cal/mol'), T0=(1,'K'), comment="""C4H9ObOO=C4H9Ob+O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9ObOO=C4H9Ob+O2
""",
)

entry(
    index = 161,
    label = "C3H6OaOOHc <=> C3H6OcyOac + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.68e+10,'s^-1'), n=0.27, Ea=(14927.9,'cal/mol'), T0=(1,'K'), comment="""C4H8ObOOHd=C4H8OcyOac+OH"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H8ObOOHd=C4H8OcyOac+OH
""",
)

entry(
    index = 162,
    label = "C3H6OaOOHcOO <=> C3H6OaOOHc + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.394e+26,'s^-1'), n=-3.36, Ea=(36067.8,'cal/mol'), T0=(1,'K'), comment="""C4H9OaOO=C4H9Oa+O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9OaOO=C4H9Oa+O2
""",
)

entry(
    index = 163,
    label = "C3H6OcyOab + OH <=> H2O + CH3CHO + HCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(180000,'cm^3/(mol*s)'), n=2.3, Ea=(-1800,'cal/mol'), T0=(1,'K'), comment="""C4H10O+OH=C4H9Ob+H2O:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+OH=C4H9Ob+H2O:site/2
""",
)

entry(
    index = 164,
    label = "C3H6OcyOab + HO2 <=> H2O2 + CH3CHO + HCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.362,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2:site/2
""",
)

entry(
    index = 165,
    label = "C3H6OcyOab + OH <=> H2O + CH2O + CH3CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.25e+06,'cm^3/(mol*s)'), n=1.9, Ea=(-2801,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-OH/CH-C2|O"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-OH/CH-C2|O
""",
)

entry(
    index = 166,
    label = "C3H6OcyOab + HO2 <=> H2O2 + CH2O + CH3CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+12,'cm^3/(mol*s)'), n=0, Ea=(14660,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-HO2/CH-C2|O"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-HO2/CH-C2|O
""",
)

entry(
    index = 167,
    label = "C3H6OcyOac + OH <=> H2O + C2H4 + OCHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(180000,'cm^3/(mol*s)'), n=2.3, Ea=(-1800,'cal/mol'), T0=(1,'K'), comment="""C4H10O+OH=C4H9Ob+H2O:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+OH=C4H9Ob+H2O:site/2
""",
)

entry(
    index = 168,
    label = "C3H6OcyOac + HO2 <=> H2O2 + C2H4 + OCHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.362,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2:site/2
""",
)

entry(
    index = 169,
    label = "C3H6OcyOac + OH <=> H2O + CH2O + CH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(360000,'cm^3/(mol*s)'), n=2.3, Ea=(-1800,'cal/mol'), T0=(1,'K'), comment="""C4H10O+OH=C4H9Ob+H2O"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+OH=C4H9Ob+H2O
""",
)

entry(
    index = 170,
    label = "C3H6OcyOac + HO2 <=> H2O2 + CH2O + CH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.724,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2
""",
)

entry(
    index = 171,
    label = "C3H6OaOOHbOO <=> aCHOC2H4ObOOH + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.83e+06,'s^-1'), n=1.38, Ea=(13882.6,'cal/mol'), T0=(1,'K'), comment="""C4H9ObOO=C4H8ObOOHc"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9ObOO=C4H8ObOOHc
""",
)

entry(
    index = 172,
    label = "C3H6OaOOHcOO <=> aCHOC2H4OcOOH + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.14e+06,'s^-1'), n=1.4, Ea=(20164.2,'cal/mol'), T0=(1,'K'), comment="""C4H9ObOO=C4H8ObOOHd"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H9ObOO=C4H8ObOOHd
""",
)

entry(
    index = 173,
    label = "aCHOC2H4ObOOH <=> OH + aCHOC2H4ObO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+16,'s^-1'), n=0, Ea=(39000,'cal/mol'), T0=(1,'K'), comment="""base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500
""",
)

entry(
    index = 174,
    label = "aCHOC2H4OcOOH <=> OH + aCHOC2H4OcO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+16,'s^-1'), n=0, Ea=(39000,'cal/mol'), T0=(1,'K'), comment="""base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
base mechanism:HO2CH2OCHO<=>OCH2OCHO+OH, E-1500
""",
)

entry(
    index = 175,
    label = "aCHOC2H4ObO <=> CH3CHO + OCHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Dcmp/RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Dcmp/RO
""",
)

entry(
    index = 176,
    label = "aCHOC2H4OcO <=> CH2O + CH2OCHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Dcmp/RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Dcmp/RO
""",
)

entry(
    index = 177,
    label = "CH3CH2OCHO + H <=> CH3CH2OCO + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.3e+06,'cm^3/(mol*s)'), n=2.49, Ea=(3274,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-H/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-H/CHO
""",
)

entry(
    index = 178,
    label = "CH3CH2OCHO + OH <=> CH3CH2OCO + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.6e+06,'cm^3/(mol*s)'), n=2, Ea=(-1983,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-OH/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-OH/CHO
""",
)

entry(
    index = 179,
    label = "CH3CH2OCHO + HO2 <=> CH3CH2OCO + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.24e+13,'cm^3/(mol*s)'), n=0, Ea=(16840,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-HO2/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-HO2/CHO
""",
)

entry(
    index = 180,
    label = "CH3CH2OCHO + CH3O2 <=> CH3CH2OCO + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.24e+13,'cm^3/(mol*s)'), n=0, Ea=(16840,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-CH3OO/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-CH3OO/CHO
""",
)

entry(
    index = 181,
    label = "CH3CH2OCHO <=> C2H5O + HCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.688e+22,'s^-1'), n=-1.912, Ea=(84005.7,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/C-C 8.00E+12 0.0 0.0"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/C-C 8.00E+12 0.0 0.0
""",
)

entry(
    index = 182,
    label = "CH3CH2OCO <=> C2H5O + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.158e+18,'s^-1'), n=-1.775, Ea=(15246.5,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/RCOp 1.50E+11 0.0 4810."""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/RCOp 1.50E+11 0.0 4810.
""",
)

entry(
    index = 183,
    label = "OCH2CHO <=> CH2O + HCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Dcmp/RO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Dcmp/RO
""",
)

entry(
    index = 184,
    label = "CH2OCH2CHO <=> CH2O + CH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.866e+18,'s^-1'), n=-1.941, Ea=(23934,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/.CC-C 8.50E+10 0.0 7800."""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/.CC-C 8.50E+10 0.0 7800.
""",
)

entry(
    index = 185,
    label = "CH2OCH2CHO <=> CO + CH3OCH2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.27e+09,'s^-1'), n=0.35, Ea=(19040,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Isom/R/5pt"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Isom/R/5pt
""",
)

entry(
    index = 186,
    label = "CH2OCH2CHO + O2 <=> CH2OCH2O2H + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(380,'cm^3/(mol*s)'), n=1.629, Ea=(-8350,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Adtn/O2/HCOQ/ts7"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Adtn/O2/HCOQ/ts7
""",
)

entry(
    index = 187,
    label = "CH2OCOCH3 <=> CH2O + CH3CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.182e+19,'s^-1'), n=-2.04, Ea=(23573,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/.CC-C 8.50E+10 0.0 7800."""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/.CC-C 8.50E+10 0.0 7800.
""",
)

entry(
    index = 188,
    label = "CH2OCOCH3 + O2 <=> CH2CO + CH2O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(760,'cm^3/(mol*s)'), n=1.629, Ea=(-6350,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Adtn/O2/RCOQ/ts7"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Adtn/O2/RCOQ/ts7
""",
)

entry(
    index = 189,
    label = "HCOCH2OCHO <=> OCH2CHO + HCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.302e+23,'s^-1'), n=-2.007, Ea=(84107.2,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/C-C 8.00E+12 0.0 0.0"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/C-C 8.00E+12 0.0 0.0
""",
)

entry(
    index = 190,
    label = "HCOCH2OCHO <=> CH2OCHO + HCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.302e+23,'s^-1'), n=-2.007, Ea=(84107.2,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/C-C 8.00E+12 0.0 0.0"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/C-C 8.00E+12 0.0 0.0
""",
)

entry(
    index = 191,
    label = "HCOCH2OCHO + H <=> HCOCH2OCO + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.3e+06,'cm^3/(mol*s)'), n=2.49, Ea=(3274,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-H/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-H/CHO
""",
)

entry(
    index = 192,
    label = "HCOCH2OCHO + OH <=> HCOCH2OCO + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.6e+06,'cm^3/(mol*s)'), n=2, Ea=(-1983,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-OH/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-OH/CHO
""",
)

entry(
    index = 193,
    label = "HCOCH2OCHO + HO2 <=> HCOCH2OCO + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.24e+13,'cm^3/(mol*s)'), n=0, Ea=(16840,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-HO2/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-HO2/CHO
""",
)

entry(
    index = 194,
    label = "HCOCH2OCHO + CH3O2 <=> HCOCH2OCO + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.24e+13,'cm^3/(mol*s)'), n=0, Ea=(16840,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-CH3OO/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-CH3OO/CHO
""",
)

entry(
    index = 195,
    label = "HCOCH2OCHO + H <=> COCH2OCHO + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.3e+06,'cm^3/(mol*s)'), n=2.49, Ea=(3274,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-H/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-H/CHO
""",
)

entry(
    index = 196,
    label = "HCOCH2OCHO + OH <=> COCH2OCHO + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.6e+06,'cm^3/(mol*s)'), n=2, Ea=(-1983,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-OH/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-OH/CHO
""",
)

entry(
    index = 197,
    label = "HCOCH2OCHO + HO2 <=> COCH2OCHO + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.24e+13,'cm^3/(mol*s)'), n=0, Ea=(16840,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-HO2/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-HO2/CHO
""",
)

entry(
    index = 198,
    label = "HCOCH2OCHO + CH3O2 <=> COCH2OCHO + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.24e+13,'cm^3/(mol*s)'), n=0, Ea=(16840,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-CH3OO/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-CH3OO/CHO
""",
)

entry(
    index = 199,
    label = "HCOCH2OCHO + H <=> HCOCHOCHO + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(574000,'cm^3/(mol*s)'), n=2.49, Ea=(2300,'cal/mol'), T0=(1,'K'), comment="""C4H10O+H=C4H9Ob+H2:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+H=C4H9Ob+H2:site/2
""",
)

entry(
    index = 200,
    label = "HCOCH2OCHO + OH <=> HCOCHOCHO + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(180000,'cm^3/(mol*s)'), n=2.3, Ea=(-1800,'cal/mol'), T0=(1,'K'), comment="""C4H10O+OH=C4H9Ob+H2O:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+OH=C4H9Ob+H2O:site/2
""",
)

entry(
    index = 201,
    label = "HCOCH2OCHO + HO2 <=> HCOCHOCHO + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.362,'cm^3/(mol*s)'), n=3.98, Ea=(9058,'cal/mol'), T0=(1,'K'), comment="""C4H10O+HO2=C4H9Ob+H2O2:site/2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
C4H10O+HO2=C4H9Ob+H2O2:site/2
""",
)

entry(
    index = 202,
    label = "HCOCH2OCO <=> OCH2CHO + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.564e+19,'s^-1'), n=-1.864, Ea=(15339.1,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/RCOp 1.50E+11 0.0 4810."""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/RCOp 1.50E+11 0.0 4810.
""",
)

entry(
    index = 203,
    label = "COCH2OCHO <=> CH2OCHO + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.564e+19,'s^-1'), n=-1.864, Ea=(15339.1,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/RCOp 1.50E+11 0.0 4810."""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/RCOp 1.50E+11 0.0 4810.
""",
)

entry(
    index = 204,
    label = "OCCHOCHO + H <=> HCOCHOCHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(2900,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/.CC(-H)C"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/.CC(-H)C
""",
)

entry(
    index = 205,
    label = "HCOCHOCHO + O2 <=> OCCHOCHO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.12e+11,'cm^3/(mol*s)'), n=0, Ea=(9000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Adtn/O2/aHvin/HO2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Adtn/O2/aHvin/HO2
""",
)

entry(
    index = 206,
    label = "HCOCHOCHO + O2 <=> CO + HCOOCHO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.2e+10,'cm^3/(mol*s)'), n=0, Ea=(9000,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Adtn/O2/aHvin/OH"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Adtn/O2/aHvin/OH
""",
)

entry(
    index = 207,
    label = "OCCHOCHO + H <=> OCCHOCO + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.3e+06,'cm^3/(mol*s)'), n=2.49, Ea=(3274,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-H/CHO-CO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-H/CHO-CO
""",
)

entry(
    index = 208,
    label = "OCCHOCHO + OH <=> OCCHOCO + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.6e+06,'cm^3/(mol*s)'), n=2, Ea=(-1983,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-OH/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-OH/CHO
""",
)

entry(
    index = 209,
    label = "OCCHOCHO + HO2 <=> OCCHOCO + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.24e+13,'cm^3/(mol*s)'), n=0, Ea=(16840,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-HO2/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-HO2/CHO
""",
)

entry(
    index = 210,
    label = "OCCHOCHO + CH3O2 <=> OCCHOCO + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.24e+13,'cm^3/(mol*s)'), n=0, Ea=(16840,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-CH3OO/CHO"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-CH3OO/CHO
""",
)

entry(
    index = 211,
    label = "OCCHOCO <=> OCCHO + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.856e+16,'s^-1'), n=-1.405, Ea=(904.8,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/RCOp 1.50E+11 0.0 4810."""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/RCOp 1.50E+11 0.0 4810.
""",
)

entry(
    index = 212,
    label = "OCCHO <=> HCO + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.856e+16,'s^-1'), n=-1.405, Ea=(904.8,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/RCOp 1.50E+11 0.0 4810."""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/RCOp 1.50E+11 0.0 4810.
""",
)

entry(
    index = 213,
    label = "HCOOCHO + H <=> COOCHO + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.6e+06,'cm^3/(mol*s)'), n=2.49, Ea=(3274,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-H/CHO:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-H/CHO:site*2
""",
)

entry(
    index = 214,
    label = "HCOOCHO + OH <=> COOCHO + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.2e+06,'cm^3/(mol*s)'), n=2, Ea=(-1983,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-OH/CHO:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-OH/CHO:site*2
""",
)

entry(
    index = 215,
    label = "HCOOCHO + HO2 <=> COOCHO + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.48e+13,'cm^3/(mol*s)'), n=0, Ea=(16840,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-HO2/CHO:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-HO2/CHO:site*2
""",
)

entry(
    index = 216,
    label = "HCOOCHO + CH3O2 <=> COOCHO + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.48e+13,'cm^3/(mol*s)'), n=0, Ea=(16840,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Habs/by-CH3OO/CHO:site*2"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Habs/by-CH3OO/CHO:site*2
""",
)

entry(
    index = 217,
    label = "HCOOCHO <=> OCHO + HCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.206e+22,'s^-1'), n=-1.916, Ea=(79114.1,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/C-C 8.00E+12 0.0 0.0"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/C-C 8.00E+12 0.0 0.0
""",
)

entry(
    index = 218,
    label = "COOCHO <=> OCHO + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.786e+18,'s^-1'), n=-1.773, Ea=(10345.7,'cal/mol'), T0=(1,'K'), comment="""KUCRS:Rv/Dcmp/RCOp 1.50E+11 0.0 4810."""),
    longDesc = 
"""
Originally from reaction library: Unclassified
KUCRS:Rv/Dcmp/RCOp 1.50E+11 0.0 4810.
""",
)

entry(
    index = 219,
    label = "C4H9Oa <=> H + C4H8O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.5e+07,'s^-1'), n=1.78, Ea=(30.7,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
""",
)

entry(
    index = 220,
    label = "C4H9Ob <=> H + C4H8O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.8e+07,'s^-1'), n=1.77, Ea=(35.7,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
""",
)

entry(
    index = 221,
    label = "C4H8OaOOHb <=> HO2 + C4H8O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.13e+10,'s^-1'), n=0.69, Ea=(14.6044,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
""",
)

entry(
    index = 222,
    label = "C4H8ObOOHa <=> HO2 + C4H8O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.02e+11,'s^-1'), n=0.48, Ea=(16.81,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
""",
)