#!/usr/bin/env python
# encoding: utf-8

name = "Ghosh_EL"
shortDesc = "The ethyl levulinate submechanism of Ghosh et al. (2018), extracted and converted to an RMG reaction library. Only validated against high-temperature data."
longDesc = """
Manik Kumer Ghosh, Mícheál Séamus Howard, Yingjia Zhang, Khalil Djebbi, Gianluca Capriolo, Aamir Farooq, Henry J. Curran, Stephen Dooley,
The combustion kinetics of the lignocellulosic biofuel, ethyl levulinate,
Combustion and Flame,
Volume 193,
2018,
Pages 157-169,
ISSN 0010-2180,
https://doi.org/10.1016/j.combustflame.2018.02.028
"""
autoGenerated=False
entry(
    index = 0,
    label = "EL1J + H <=> EL",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 1,
    label = "EL3J + H <=> EL",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 2,
    label = "EL4J + H <=> EL",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 3,
    label = "EL6J + H <=> EL",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 4,
    label = "EL7J + H <=> EL",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 5,
    label = "ELCOJ + CH3 <=> EL",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 6,
    label = "CH2CH2COCH3 + EFF <=> EL",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 7,
    label = "CH3COCH2CH2COJ + C2H5O <=> EL",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 8,
    label = "C5H7O3-OJ + C2H5 <=> EL",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 9,
    label = "EL <=> C5H8O3 + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8e+12,'s^-1'), n=0, Ea=(49950,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

# entry(
#     index = 10,
#     label = "EL + H <=> EL1J + H2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1.81e+06,'cm^3/(mol*s)'), n=2.4, Ea=(2583,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 11,
#     label = "EL + H <=> EL3J + H2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1.2e+06,'cm^3/(mol*s)'), n=2.4, Ea=(2583,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 12,
#     label = "EL + H <=> EL4J + H2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1.2e+06,'cm^3/(mol*s)'), n=2.4, Ea=(2583,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 13,
#     label = "EL + H <=> EL6J + H2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1.2e+06,'cm^3/(mol*s)'), n=2.4, Ea=(2583,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 14,
#     label = "EL + H <=> EL7J + H2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(603000,'cm^3/(mol*s)'), n=2.54, Ea=(6756,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 15,
#     label = "EL + OH <=> EL1J + H2O",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(87800,'cm^3/(mol*s)'), n=2.53, Ea=(-1659,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 16,
#     label = "EL + OH <=> EL3J + H2O",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(58500,'cm^3/(mol*s)'), n=2.53, Ea=(-1659,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 17,
#     label = "EL + OH <=> EL4J + H2O",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(58500,'cm^3/(mol*s)'), n=2.53, Ea=(-1659,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 18,
#     label = "EL + OH <=> EL6J + H2O",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(58500,'cm^3/(mol*s)'), n=2.53, Ea=(-1659,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 19,
#     label = "EL + OH <=> EL7J + H2O",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(22200,'cm^3/(mol*s)'), n=2.67, Ea=(-168.9,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 20,
#     label = "EL + CH3 <=> EL1J + CH4",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(2.71,'cm^3/(mol*s)'), n=3.46, Ea=(4598,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 21,
#     label = "EL + CH3 <=> EL3J + CH4",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1.81,'cm^3/(mol*s)'), n=3.46, Ea=(4598,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 22,
#     label = "EL + CH3 <=> EL4J + CH4",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1.81,'cm^3/(mol*s)'), n=3.46, Ea=(4598,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 23,
#     label = "EL + CH3 <=> EL6J + CH4",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1.81,'cm^3/(mol*s)'), n=3.46, Ea=(4598,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 24,
#     label = "EL + CH3 <=> EL7J + CH4",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(2.71,'cm^3/(mol*s)'), n=3.65, Ea=(7154,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 25,
#     label = "EL + CH3O <=> EL1J + CH3OH",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(5.7e+10,'cm^3/(mol*s)'), n=0, Ea=(2800,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 26,
#     label = "EL + CH3O <=> EL3J + CH3OH",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(3.8e+10,'cm^3/(mol*s)'), n=0, Ea=(2800,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 27,
#     label = "EL + CH3O <=> EL4J + CH3OH",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(3.8e+10,'cm^3/(mol*s)'), n=0, Ea=(2800,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 28,
#     label = "EL + CH3O <=> EL6J + CH3OH",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(3.8e+10,'cm^3/(mol*s)'), n=0, Ea=(2800,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 29,
#     label = "EL + CH3O <=> EL7J + CH3OH",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1.6e+11,'cm^3/(mol*s)'), n=0, Ea=(7000,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 30,
#     label = "EL + CH3O2 <=> EL1J + CH3O2H",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(410,'cm^3/(mol*s)'), n=3.12, Ea=(13190,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 31,
#     label = "EL + CH3O2 <=> EL3J + CH3O2H",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(273,'cm^3/(mol*s)'), n=3.12, Ea=(13190,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 32,
#     label = "EL + CH3O2 <=> EL4J + CH3O2H",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(273,'cm^3/(mol*s)'), n=3.12, Ea=(13190,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 33,
#     label = "EL + CH3O2 <=> EL6J + CH3O2H",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(273,'cm^3/(mol*s)'), n=3.12, Ea=(13190,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 34,
#     label = "EL + CH3O2 <=> EL7J + CH3O2H",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(0.693,'cm^3/(mol*s)'), n=3.97, Ea=(18280,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 35,
#     label = "EL + HO2 <=> EL1J + H2O2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1300,'cm^3/(mol*s)'), n=3.01, Ea=(12090,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 36,
#     label = "EL + HO2 <=> EL3J + H2O2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(866,'cm^3/(mol*s)'), n=3.01, Ea=(12090,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 37,
#     label = "EL + HO2 <=> EL4J + H2O2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(866,'cm^3/(mol*s)'), n=3.01, Ea=(12090,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 38,
#     label = "EL + HO2 <=> EL6J + H2O2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(866,'cm^3/(mol*s)'), n=3.01, Ea=(12090,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 39,
#     label = "EL + HO2 <=> EL7J + H2O2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(20.4,'cm^3/(mol*s)'), n=3.59, Ea=(17160,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 40,
#     label = "EL + O <=> EL1J + OH",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(590000,'cm^3/(mol*s)'), n=2.4, Ea=(1150,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 41,
#     label = "EL + O <=> EL3J + OH",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(394000,'cm^3/(mol*s)'), n=2.4, Ea=(1150,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 42,
#     label = "EL + O <=> EL4J + OH",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(394000,'cm^3/(mol*s)'), n=2.4, Ea=(1150,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 43,
#     label = "EL + O <=> EL6J + OH",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(394000,'cm^3/(mol*s)'), n=2.4, Ea=(1150,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 44,
#     label = "EL + O <=> EL7J + OH",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(1.35e+07,'cm^3/(mol*s)'), n=2.03, Ea=(5136,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 45,
#     label = "EL + O2 <=> EL1J + HO2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(48200,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 46,
#     label = "EL + O2 <=> EL3J + HO2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(48200,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 47,
#     label = "EL + O2 <=> EL4J + HO2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(48200,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 48,
#     label = "EL + O2 <=> EL6J + HO2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(48200,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

# entry(
#     index = 49,
#     label = "EL + O2 <=> EL7J + HO2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(52290,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )

entry(
    index = 50,
    label = "CH2CO + EP3J <=> EL1J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(6000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 51,
    label = "CH3 + COCHCH2CO2CH2CH3 <=> EL3J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(6000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 52,
    label = "C2H3COCH3 + EFF <=> EL3J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(13200,'cm^3/(mol*s)'), n=2.48, Ea=(6130,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 53,
    label = "CH3CO + EP1D <=> EL4J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(8420,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 54,
    label = "CH3COCH2CHCO + C2H5O <=> EL4J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.23e+11,'cm^3/(mol*s)'), n=0, Ea=(7800,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 55,
    label = "CH3CHO + CH3COCH2CH2COJ <=> EL6J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.002e+12,'cm^3/(mol*s)'), n=0, Ea=(24000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 56,
    label = "C2H4 + C5H7O3-OJ <=> EL7J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(13200,'cm^3/(mol*s)'), n=2.48, Ea=(6130,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 57,
    label = "CH2CO + EE2J <=> ELCOJ",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(10000,'cm^3/(mol*s)'), n=2.48, Ea=(6130,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 58,
    label = "CH3COCH2 + CH2CO <=> CH3COCH2CH2COJ",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(6000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 59,
    label = "EL1J <=> EL3J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 60,
    label = "EL1J <=> EL4J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 61,
    label = "EL1J <=> EL6J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 62,
    label = "EL1J <=> EL7J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 63,
    label = "EL3J <=> EL4J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 64,
    label = "EL3J <=> EL6J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 65,
    label = "EL3J <=> EL7J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 66,
    label = "EL4J <=> EL6J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 67,
    label = "EL4J <=> EL7J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 68,
    label = "EL6J <=> EL7J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 69,
    label = "CH3 + CH2OCHO <=> EF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 70,
    label = "EF + H <=> EFP + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(188000,'cm^3/(mol*s)'), n=2.8, Ea=(6280,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 71,
    label = "EF + O2 <=> EFP + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(47500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 72,
    label = "EF + O <=> EFP + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.03e+14,'cm^3/(mol*s)'), n=0, Ea=(7850,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 73,
    label = "EF + OH <=> EFP + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.05e+10,'cm^3/(mol*s)'), n=1, Ea=(1586,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 74,
    label = "EF + HO2 <=> EFP + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.68e+13,'cm^3/(mol*s)'), n=0, Ea=(20430,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 75,
    label = "EF + CH3 <=> EFP + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.29e+12,'cm^3/(mol*s)'), n=0, Ea=(11600,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 76,
    label = "EF + C2H3 <=> EFP + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(10400,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 77,
    label = "EF + C2H5 <=> EFP + C2H6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(10400,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 78,
    label = "EF + CH3O <=> EFP + CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(7000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 79,
    label = "EF + CH3O2 <=> EFP + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.7e+13,'cm^3/(mol*s)'), n=0, Ea=(20460,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 80,
    label = "EFP <=> C2H4 + OCHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.34e+13,'s^-1'), n=-0.4, Ea=(24610,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 81,
    label = "EF + O2 <=> EFS + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4e+13,'cm^3/(mol*s)'), n=0, Ea=(47500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 82,
    label = "EF + H <=> EFS + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(325000,'cm^3/(mol*s)'), n=2.4, Ea=(4471,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 83,
    label = "EF + O <=> EFS + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.81e+13,'cm^3/(mol*s)'), n=0, Ea=(5200,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 84,
    label = "EF + OH <=> EFS + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.16e+07,'cm^3/(mol*s)'), n=1.6, Ea=(-35,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 85,
    label = "EF + HO2 <=> EFS + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.6e+12,'cm^3/(mol*s)'), n=0, Ea=(17700,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 86,
    label = "EF + CH3 <=> EFS + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.98e+11,'cm^3/(mol*s)'), n=0, Ea=(9500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 87,
    label = "EF + C2H3 <=> EFS + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(10400,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 88,
    label = "EF + C2H5 <=> EFS + C2H6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(10400,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 89,
    label = "EF + CH3O <=> EFS + CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(7000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 90,
    label = "EF + CH3O2 <=> EFS + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+12,'cm^3/(mol*s)'), n=0, Ea=(17000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 91,
    label = "EFS <=> CH3CHO + HCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.17e+15,'s^-1'), n=-0.9, Ea=(14040,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 92,
    label = "EF + H <=> EFF + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(650000,'cm^3/(mol*s)'), n=2.4, Ea=(4471,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 93,
    label = "EF + O <=> EFF + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(551000,'cm^3/(mol*s)'), n=2.5, Ea=(2830,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 94,
    label = "EF + OH <=> EFF + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.33e+07,'cm^3/(mol*s)'), n=1.6, Ea=(-35,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 95,
    label = "EF + CH3 <=> EFF + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.51,'cm^3/(mol*s)'), n=3.5, Ea=(5481,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 96,
    label = "EF + HO2 <=> EFF + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9640,'cm^3/(mol*s)'), n=2.6, Ea=(13910,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 97,
    label = "EF + O2 <=> EFF + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(49700,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 98,
    label = "EF + CH3O <=> EFF + CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.48e+11,'cm^3/(mol*s)'), n=0, Ea=(5000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 99,
    label = "EF + CH3O2 <=> EFF + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4820,'cm^3/(mol*s)'), n=2.6, Ea=(13910,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 100,
    label = "C2H5 + CO2 <=> EFF",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(4.76e+07,'cm^3/(mol*s)'), n=1.5, Ea=(37410,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 101,
    label = "C2H5O + CO <=> EFF",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.55e+06,'cm^3/(mol*s)'), n=2, Ea=(5734,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 102,
    label = "EFP + H <=> EF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 103,
    label = "EFS + H <=> EF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 104,
    label = "EFF + H <=> EF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 105,
    label = "OCHO + C2H5 <=> EF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 106,
    label = "HCO + C2H5O <=> EF",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 107,
    label = "EF <=> HOCHO + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.6e+13,'s^-1'), n=0, Ea=(50000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 108,
    label = "C2H4 + CH3CO <=> CH2CH2COCH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(8420,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 109,
    label = "C5H7O3-OJ <=> C5H7O3-2J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 110,
    label = "C5H7O3-OJ <=> C5H7O3-3J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 111,
    label = "C5H7O3-OJ <=> C5H7O3-5J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 112,
    label = "C5H7O3-2J <=> C5H7O3-3J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 113,
    label = "C5H7O3-2J <=> C5H7O3-5J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 114,
    label = "C5H7O3-3J <=> C5H7O3-5J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 115,
    label = "C5H7O3-OJ + H <=> C5H8O3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 116,
    label = "C5H7O3-2J + H <=> C5H8O3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 117,
    label = "C5H7O3-3J + H <=> C5H8O3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 118,
    label = "C5H7O3-5J + H <=> C5H8O3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 119,
    label = "CH3 + COJCH2CH2CO2H <=> C5H8O3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 120,
    label = "CH3CO + CH2CH2COOH <=> C5H8O3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 121,
    label = "CH3COCH2 + CH2COOH <=> C5H8O3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 122,
    label = "CH2CH2COCH3 + OCHO <=> C5H8O3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 123,
    label = "CH3COCH2CH2COJ + OH <=> C5H8O3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 124,
    label = "C5H8O3 + H <=> C5H7O3-OJ + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(201000,'cm^3/(mol*s)'), n=2.54, Ea=(6756,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 125,
    label = "C5H8O3 + H <=> C5H7O3-2J + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+06,'cm^3/(mol*s)'), n=2.4, Ea=(2583,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 126,
    label = "C5H8O3 + H <=> C5H7O3-3J + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+06,'cm^3/(mol*s)'), n=2.4, Ea=(2583,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 127,
    label = "C5H8O3 + H <=> C5H7O3-5J + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.8e+06,'cm^3/(mol*s)'), n=2.4, Ea=(2583,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 128,
    label = "C5H8O3 + OH <=> C5H7O3-OJ + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.76e+09,'cm^3/(mol*s)'), n=0.97, Ea=(1586,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 129,
    label = "C5H8O3 + OH <=> C5H7O3-2J + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.73e+10,'cm^3/(mol*s)'), n=0.51, Ea=(63,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 130,
    label = "C5H8O3 + OH <=> C5H7O3-3J + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+07,'cm^3/(mol*s)'), n=1.61, Ea=(-35,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 131,
    label = "C5H8O3 + OH <=> C5H7O3-5J + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.76e+09,'cm^3/(mol*s)'), n=0.97, Ea=(1586,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 132,
    label = "C5H8O3 + CH3 <=> C5H7O3-OJ + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.151,'cm^3/(mol*s)'), n=3.65, Ea=(7154,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 133,
    label = "C5H8O3 + CH3 <=> C5H7O3-2J + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81,'cm^3/(mol*s)'), n=3.46, Ea=(4598,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 134,
    label = "C5H8O3 + CH3 <=> C5H7O3-3J + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81,'cm^3/(mol*s)'), n=3.46, Ea=(4598,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 135,
    label = "C5H8O3 + CH3 <=> C5H7O3-5J + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.71,'cm^3/(mol*s)'), n=3.46, Ea=(4598,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 136,
    label = "C5H8O3 + CH3O <=> C5H7O3-OJ + CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.33e+10,'cm^3/(mol*s)'), n=0, Ea=(7000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 137,
    label = "C5H8O3 + CH3O <=> C5H7O3-2J + CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.8e+10,'cm^3/(mol*s)'), n=0, Ea=(2800,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 138,
    label = "C5H8O3 + CH3O <=> C5H7O3-3J + CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.8e+10,'cm^3/(mol*s)'), n=0, Ea=(2800,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 139,
    label = "C5H8O3 + CH3O <=> C5H7O3-5J + CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.7e+10,'cm^3/(mol*s)'), n=0, Ea=(2800,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 140,
    label = "C5H8O3 + CH3O2 <=> C5H7O3-OJ + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.231,'cm^3/(mol*s)'), n=3.97, Ea=(18280,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 141,
    label = "C5H8O3 + CH3O2 <=> C5H7O3-2J + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(273,'cm^3/(mol*s)'), n=3.12, Ea=(13190,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 142,
    label = "C5H8O3 + CH3O2 <=> C5H7O3-3J + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(273,'cm^3/(mol*s)'), n=3.12, Ea=(13190,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 143,
    label = "C5H8O3 + CH3O2 <=> C5H7O3-5J + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(410,'cm^3/(mol*s)'), n=3.12, Ea=(13190,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 144,
    label = "C5H8O3 + HO2 <=> C5H7O3-OJ + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.8,'cm^3/(mol*s)'), n=3.59, Ea=(17160,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 145,
    label = "C5H8O3 + HO2 <=> C5H7O3-2J + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(866,'cm^3/(mol*s)'), n=3.01, Ea=(12090,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 146,
    label = "C5H8O3 + HO2 <=> C5H7O3-3J + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(866,'cm^3/(mol*s)'), n=3.01, Ea=(12090,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 147,
    label = "C5H8O3 + HO2 <=> C5H7O3-5J + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1300,'cm^3/(mol*s)'), n=3.01, Ea=(12090,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 148,
    label = "C5H8O3 + O <=> C5H7O3-OJ + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+06,'cm^3/(mol*s)'), n=2.03, Ea=(5136,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 149,
    label = "C5H8O3 + O <=> C5H7O3-2J + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(394000,'cm^3/(mol*s)'), n=2.4, Ea=(1150,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 150,
    label = "C5H8O3 + O <=> C5H7O3-3J + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(394000,'cm^3/(mol*s)'), n=2.4, Ea=(1150,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 151,
    label = "C5H8O3 + O <=> C5H7O3-5J + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(590000,'cm^3/(mol*s)'), n=2.4, Ea=(1150,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

# entry(
#     index = 152,
#     label = "C5H8O3 + O2 <=> C5H7O3-OJ + HO2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(4.5e+06,'cm^3/(mol*s)'), n=2.03, Ea=(5136,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )
#coll. rate violator

entry(
    index = 153,
    label = "C5H8O3 + O2 <=> C5H7O3-2J + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(48200,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 154,
    label = "C5H8O3 + O2 <=> C5H7O3-3J + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(48200,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 155,
    label = "C5H8O3 + O2 <=> C5H7O3-5J + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(48200,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 156,
    label = "CH2CH2COCH3 + CO2 <=> C5H7O3-OJ",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1e+11,'cm^6/(mol^2*s)'), n=0, Ea=(39360,'cal/mol'), T0=(1,'K')), efficiencies={}),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 157,
    label = "CH3CO + C2H3COOH <=> C5H7O3-2J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(8420,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 158,
    label = "OH + CH3COCH2CHCO <=> C5H7O3-2J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.6e+12,'cm^3/(mol*s)'), n=0, Ea=(-614,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 159,
    label = "OCHO + C2H3COCH3 <=> C5H7O3-3J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(13200,'cm^3/(mol*s)'), n=2.48, Ea=(6130,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 160,
    label = "CH3 + COCHCH2COOH <=> C5H7O3-3J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(13200,'cm^3/(mol*s)'), n=2.48, Ea=(6130,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 161,
    label = "CH2CO + CH2CH2COOH <=> C5H7O3-5J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(13200,'cm^3/(mol*s)'), n=2.48, Ea=(6130,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 162,
    label = "CH3 + COCHCH2COOH <=> C5H7O3-5J",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(6000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 163,
    label = "COCHCH2COOH + H <=> COCHCHCOOH + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+06,'cm^3/(mol*s)'), n=2.4, Ea=(2583,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 164,
    label = "COCHCH2COOH + O <=> COCHCHCOOH + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(394000,'cm^3/(mol*s)'), n=2.4, Ea=(1150,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 165,
    label = "COCHCH2COOH + OH <=> COCHCHCOOH + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(58500,'cm^3/(mol*s)'), n=2.53, Ea=(-1659,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

# entry(
#     index = 166,
#     label = "COCHCH2COOH + HO2 <=> COCHCHCOOH + H2O2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(866,'cm^3/(mol*s)'), n=3.01, Ea=(12090,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )
#coll. rate violator

entry(
    index = 167,
    label = "COCHCH2COOH + CH3 <=> COCHCHCOOH + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81,'cm^3/(mol*s)'), n=3.46, Ea=(4598,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

# entry(
#     index = 168,
#     label = "COCHCH2COOH + CH3O2 <=> COCHCHCOOH + CH3O2H",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(273,'cm^3/(mol*s)'), n=3.12, Ea=(13190,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )
#coll. rate violator

# entry(
#     index = 169,
#     label = "COCHCH2COOH + O2 <=> COCHCHCOOH + HO2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(48200,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )
#coll. rate violator

entry(
    index = 170,
    label = "C2H3COOH <=> C2H3 + OCHO",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(3.752e+21,'cm^3/(mol*s)'), n=-1.89, Ea=(112900,'cal/mol'), T0=(1,'K')), efficiencies={}, comment="""Chemkin file stated explicit reverse rate: REV/ 1.510E+11 0.00 4.810E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.510E+11 0.00 4.810E+03 /
""",
)

entry(
    index = 171,
    label = "C2H3COOH <=> C2H3CO + OH",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(5.206e+20,'cm^3/(mol*s)'), n=-1.16, Ea=(100900,'cal/mol'), T0=(1,'K')), efficiencies={}, comment="""Chemkin file stated explicit reverse rate: REV/ 5.000E+13 0.00 0.000E+00 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 5.000E+13 0.00 0.000E+00 /
""",
)

entry(
    index = 172,
    label = "C2H3COOH + H <=> C2H2COOH + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+06,'cm^3/(mol*s)'), n=2.4, Ea=(2583,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 173,
    label = "C2H3COOH + O <=> C2H2COOH + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(394000,'cm^3/(mol*s)'), n=2.4, Ea=(1150,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 174,
    label = "C2H3COOH + OH <=> C2H2COOH + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(58500,'cm^3/(mol*s)'), n=2.53, Ea=(-1659,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

# entry(
#     index = 175,
#     label = "C2H3COOH + HO2 <=> C2H2COOH + H2O2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(866,'cm^3/(mol*s)'), n=3.01, Ea=(12090,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )
#CRV

entry(
    index = 176,
    label = "C2H3COOH + CH3 <=> C2H2COOH + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81,'cm^3/(mol*s)'), n=3.46, Ea=(4598,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

# entry(
#     index = 177,
#     label = "C2H3COOH + CH3O2 <=> C2H2COOH + CH3O2H",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(273,'cm^3/(mol*s)'), n=3.12, Ea=(13190,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )
#CRV

# entry(
#     index = 178,
#     label = "C2H3COOH + O2 <=> C2H2COOH + HO2",
#     degeneracy = 1.0,
#     kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(48200,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )
#CRV

entry(
    index = 179,
    label = "OCHO + C2H2 <=> C2H2COOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(13200,'cm^3/(mol*s)'), n=2.48, Ea=(6130,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 180,
    label = "OCHO <=> CO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.186e+14,'s^-1'), n=0.13, Ea=(36460,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.253E+08 1.41 5.918E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.253E+08 1.41 5.918E+03 /
""",
)

entry(
    index = 181,
    label = "OCHO <=> CO2 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.22e+11,'s^-1'), n=0.41, Ea=(35340,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 2.297E+12 0.50 3.022E+04 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 2.297E+12 0.50 3.022E+04 /
""",
)

entry(
    index = 182,
    label = "C2H5CO2 <=> C2H5 + CO2",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(4.4e+15,'cm^3/(mol*s)'), n=0, Ea=(10500,'cal/mol'), T0=(1,'K')), efficiencies={}, comment="""Chemkin file stated explicit reverse rate: REV/ 1.361E+08 1.78 2.429E+04 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.361E+08 1.78 2.429E+04 /
""",
)

entry(
    index = 183,
    label = "CH2CHCO + OH <=> C2H4 + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 2.261E+11 0.80 1.029E+05 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 2.261E+11 0.80 1.029E+05 /
""",
)

entry(
    index = 184,
    label = "CH2CHCO + HO2 => C2H3 + CO2 + OH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.03e+09,'cm^3/(mol*s)'), n=0, Ea=(7949,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 0.000E+00 0.00 0.000E+00 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 0.000E+00 0.00 0.000E+00 /
""",
)

entry(
    index = 185,
    label = "CH2CHCO + CH3O2 => C2H3 + CO2 + CH3O",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3.97e+11,'cm^3/(mol*s)'), n=0, Ea=(17050,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 0.000E+00 0.00 0.000E+00 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 0.000E+00 0.00 0.000E+00 /
""",
)

entry(
    index = 186,
    label = "C2H3COCH3 + OH => CH3CHO + CH3CO",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 187,
    label = "C2H3COCH3 + OH => CH2CO + C2H3 + H2O",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(5.1e+11,'cm^3/(mol*s)'), n=0, Ea=(1192,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 188,
    label = "C2H3COCH3 + HO2 => CH2CHO + CH3CO + OH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.03e+09,'cm^3/(mol*s)'), n=0, Ea=(7949,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

# entry(
#     index = 189,
#     label = "C2H3COCH3 + HO2 => CH2CO + C2H3 + H2O2",
#     degeneracy = 1.0,
#     reversible = False,
#     kinetics = Arrhenius(A=(8.5e+12,'cm^3/(mol*s)'), n=0, Ea=(20460,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )
#coll. rate violator

entry(
    index = 190,
    label = "C2H3COCH3 + CH3O2 => CH2CHO + CH3CO + CH3O",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(3.97e+11,'cm^3/(mol*s)'), n=0, Ea=(17050,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

# entry(
#     index = 191,
#     label = "C2H3COCH3 + CH3O2 => CH2CO + C2H3 + CH3O2H",
#     degeneracy = 1.0,
#     reversible = False,
#     kinetics = Arrhenius(A=(3.01e+12,'cm^3/(mol*s)'), n=0, Ea=(17580,'cal/mol'), T0=(1,'K')),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# """,
# )
#coll. rate violator

# entry(
#     index = 192,
#     label = "C2H3COCH3 + H => CH2CO + C2H3 + H2",
#     degeneracy = 1.0,
#     reversible = False,
#     kinetics = Arrhenius(A=(325000,'cm^3/(mol*s)'), n=2.4, Ea=(4471,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 0.000E+00 0.00 0.000E+00 /"""),
#     longDesc = 
# """
# Originally from reaction library: Unclassified
# Chemkin file stated explicit reverse rate: REV/ 0.000E+00 0.00 0.000E+00 /
# """,
# )
#coll. rate violator

entry(
    index = 193,
    label = "EP1D <=> C2H3 + C2H5OCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.28e+22,'s^-1'), n=-1.66, Ea=(107800,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.000E+13 0.00 0.000E+00 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.000E+13 0.00 0.000E+00 /
""",
)

entry(
    index = 194,
    label = "EP1D <=> C2H3CO + C2H5O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.379e+23,'s^-1'), n=-1.83, Ea=(90230,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 2.000E+13 0.00 0.000E+00 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 2.000E+13 0.00 0.000E+00 /
""",
)

entry(
    index = 195,
    label = "EP1D <=> MP1DMJ + CH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.515e+20,'s^-1'), n=-1.02, Ea=(92230,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.000E+13 0.00 0.000E+00 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.000E+13 0.00 0.000E+00 /
""",
)

entry(
    index = 196,
    label = "EP1D + O2 <=> EP1DEJ + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(48200,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.767E+12 -0.29 -4.790E+02 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.767E+12 -0.29 -4.790E+02 /
""",
)

entry(
    index = 197,
    label = "EP1D + O2 <=> EP1DMJ + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+13,'cm^3/(mol*s)'), n=0, Ea=(52290,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.135E+10 0.38 -1.819E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.135E+10 0.38 -1.819E+03 /
""",
)

entry(
    index = 198,
    label = "EP1D + H <=> EP1DEJ + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.204e+06,'cm^3/(mol*s)'), n=2.4, Ea=(2583,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 2.027E+04 2.46 8.593E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 2.027E+04 2.46 8.593E+03 /
""",
)

entry(
    index = 199,
    label = "EP1D + H <=> EP1DMJ + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(666000,'cm^3/(mol*s)'), n=2.54, Ea=(6756,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 4.802E+01 3.27 7.336E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 4.802E+01 3.27 7.336E+03 /
""",
)

entry(
    index = 200,
    label = "EP1D + O <=> EP1DEJ + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(766000,'cm^3/(mol*s)'), n=2.41, Ea=(1140,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 6.770E+03 2.44 5.738E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 6.770E+03 2.44 5.738E+03 /
""",
)

entry(
    index = 201,
    label = "EP1D + O <=> EP1DMJ + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(981000,'cm^3/(mol*s)'), n=2.43, Ea=(4750,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 3.713E+01 3.14 3.918E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 3.713E+01 3.14 3.918E+03 /
""",
)

entry(
    index = 202,
    label = "EP1D + OH <=> EP1DEJ + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.146e+11,'cm^3/(mol*s)'), n=0.51, Ea=(63,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 2.053E+10 0.46 2.096E+04 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 2.053E+10 0.46 2.096E+04 /
""",
)

entry(
    index = 203,
    label = "EP1D + OH <=> EP1DMJ + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.28e+09,'cm^3/(mol*s)'), n=0.97, Ea=(1586,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 4.051E+06 1.59 1.706E+04 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 4.051E+06 1.59 1.706E+04 /
""",
)

entry(
    index = 204,
    label = "EP1D + CH3 <=> EP1DEJ + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.202e-09,'cm^3/(mol*s)'), n=6.36, Ea=(893,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.847E-08 5.97 8.443E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.847E-08 5.97 8.443E+03 /
""",
)

entry(
    index = 205,
    label = "EP1D + CH3 <=> EP1DMJ + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.453,'cm^3/(mol*s)'), n=3.65, Ea=(7154,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 2.981E-02 3.93 9.274E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 2.981E-02 3.93 9.274E+03 /
""",
)

entry(
    index = 206,
    label = "EP1D + HO2 <=> EP1DEJ + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7220,'cm^3/(mol*s)'), n=2.55, Ea=(10530,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 7.037E+04 1.91 5.390E+02 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 7.037E+04 1.91 5.390E+02 /
""",
)

entry(
    index = 207,
    label = "EP1D + HO2 <=> EP1DMJ + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(23790,'cm^3/(mol*s)'), n=2.55, Ea=(16490,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 9.930E+02 2.58 1.069E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 9.930E+02 2.58 1.069E+03 /
""",
)

entry(
    index = 208,
    label = "EP1D + CH3O2 <=> EP1DEJ + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7220,'cm^3/(mol*s)'), n=2.55, Ea=(10530,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.369E+06 1.47 -1.056E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.369E+06 1.47 -1.056E+03 /
""",
)

entry(
    index = 209,
    label = "EP1D + CH3O2 <=> EP1DMJ + CH3O2H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(23790,'cm^3/(mol*s)'), n=2.55, Ea=(16490,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.932E+04 2.14 -5.260E+02 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.932E+04 2.14 -5.260E+02 /
""",
)

entry(
    index = 210,
    label = "EP1D + C2H5 <=> EP1DEJ + C2H6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.084,'cm^3/(mol*s)'), n=3.46, Ea=(5962,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.977E+02 2.83 9.742E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.977E+02 2.83 9.742E+03 /
""",
)

entry(
    index = 211,
    label = "EP1D + C2H5 <=> EP1DMJ + C2H6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.452,'cm^3/(mol*s)'), n=3.65, Ea=(9141,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 3.530E-01 3.69 7.491E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 3.530E-01 3.69 7.491E+03 /
""",
)

entry(
    index = 212,
    label = "EP1D + C2H3 <=> EP1DEJ + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.808,'cm^3/(mol*s)'), n=3.46, Ea=(2611,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 9.642E+01 3.01 1.638E+04 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 9.642E+01 3.01 1.638E+04 /
""",
)

entry(
    index = 213,
    label = "EP1D + C2H3 <=> EP1DMJ + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(301.5,'cm^3/(mol*s)'), n=3.3, Ea=(10500,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 6.886E+01 3.52 1.884E+04 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 6.886E+01 3.52 1.884E+04 /
""",
)

entry(
    index = 214,
    label = "EP1D + CH3O <=> EP1DEJ + CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.58e+10,'cm^3/(mol*s)'), n=0, Ea=(2873,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.656E+10 -0.16 9.110E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.656E+10 -0.16 9.110E+03 /
""",
)

entry(
    index = 215,
    label = "EP1D + CH3O <=> EP1DMJ + CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.169e+11,'cm^3/(mol*s)'), n=0, Ea=(6458,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 6.310E+08 0.39 8.993E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 6.310E+08 0.39 8.993E+03 /
""",
)

entry(
    index = 216,
    label = "EP1DEJ <=> CH3CHO + CH2CHCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.422e+23,'s^-1'), n=-2.69, Ea=(33270,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 2.002E+12 0.00 2.400E+04 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 2.002E+12 0.00 2.400E+04 /
""",
)

entry(
    index = 217,
    label = "EP1DMJ <=> C2H4 + C2H3CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.497e+12,'s^-1'), n=0.44, Ea=(32020,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.320E+04 2.48 6.130E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.320E+04 2.48 6.130E+03 /
""",
)

entry(
    index = 218,
    label = "C2H3CO2 <=> C2H3 + CO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(10000,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 9.311E+04 1.82 9.890E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 9.311E+04 1.82 9.890E+03 /
""",
)

entry(
    index = 219,
    label = "C2H5OCO <=> C2H5O + CO",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(5.059e+14,'s^-1'), n=0.17, Ea=(25520,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.550E+06 2.02 5.730E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.550E+06 2.02 5.730E+03 /
""",
)

entry(
    index = 220,
    label = "C2H5OCO <=> C2H5 + CO2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.805e+16,'s^-1'), n=-0.56, Ea=(20170,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 4.760E+07 1.54 3.470E+04 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 4.760E+07 1.54 3.470E+04 /
""",
)

entry(
    index = 221,
    label = "EE2J <=> CH2CO + C2H5O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.364e+19,'s^-1'), n=-1.88, Ea=(56420,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.000E+11 0.00 1.290E+04 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.000E+11 0.00 1.290E+04 /
""",
)

entry(
    index = 222,
    label = "MPMJ <=> CH2O + C2H5CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.949e+20,'s^-1'), n=-1.82, Ea=(44530,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 2.002E+12 0.00 2.400E+04 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 2.002E+12 0.00 2.400E+04 /
""",
)

entry(
    index = 223,
    label = "MP1DMJ <=> CH2O + C2H3CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.418e+23,'s^-1'), n=-2.82, Ea=(36410,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 2.002E+12 0.00 2.400E+04 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 2.002E+12 0.00 2.400E+04 /
""",
)

entry(
    index = 224,
    label = "CH2COOH <=> CH2CO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.638e+18,'s^-1'), n=-1.28, Ea=(53860,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 2.600E+12 0.00 -6.140E+02 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 2.600E+12 0.00 -6.140E+02 /
""",
)

entry(
    index = 225,
    label = "EP3J <=> C2H4 + C2H5OCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.827e+15,'s^-1'), n=-0.67, Ea=(35550,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 226,
    label = "CO + CH2CH2COOH <=> COJCH2CH2CO2H",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(1.51e+11,'cm^6/(mol^2*s)'), n=0, Ea=(4810,'cal/mol'), T0=(1,'K')), efficiencies={}),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 227,
    label = "CH2CH2COOH <=> C2H4 + OCHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.217e+14,'s^-1'), n=-0.32, Ea=(34860,'cal/mol'), T0=(1,'K'), comment="""Chemkin file stated explicit reverse rate: REV/ 1.320E+04 2.48 6.130E+03 /"""),
    longDesc = 
"""
Originally from reaction library: Unclassified
Chemkin file stated explicit reverse rate: REV/ 1.320E+04 2.48 6.130E+03 /
""",
)

