#!/usr/bin/env python
# encoding: utf-8

name = "Tran_DEE_submech"
shortDesc = "The diethyl ether submechanism of Tran et al. (2019), extracted and converted to an RMG reaction library."
longDesc = """
Luc-Sy Tran, Olivier Herbinet, Yuyang Li, Julia Wullenkord, Meirong Zeng, Eike Bräuer, Fei Qi, Katharina Kohse-Höinghaus, Frédérique Battin-Leclerc,
Low-temperature gas-phase oxidation of diethyl ether: Fuel reactivity and fuel-specific products,
Proceedings of the Combustion Institute,
Volume 37, Issue 1,
2019,
Pages 511-519,
ISSN 1540-7489,
https://doi.org/10.1016/j.proci.2018.05.135
"""
autoGenerated=False
entry(
    index = 0,
    label = "DEE <=> C2H5OH + C2H4",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(1e+14,'s^-1'), n=0, Ea=(65200,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(5.7202e+96,'cm^3/(mol*s)'), n=-23.04, Ea=(80813,'cal/mol'), T0=(1,'K')), alpha=0.0011757, T3=(379.12,'K'), T1=(1.5812e+07,'K'), T2=(4727.9,'K'), efficiencies={}),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 1,
    label = "DEE <=> C2H5 + C2H5O",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(1.24e+25,'s^-1'), n=-2.29, Ea=(85330,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(3.5533e+83,'cm^3/(mol*s)'), n=-18.724, Ea=(96839,'cal/mol'), T0=(1,'K')), alpha=9.0353e-06, T3=(505.71,'K'), T1=(1.4142e+10,'K'), T2=(2471.3,'K'), efficiencies={}),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 2,
    label = "DEE <=> CH3 + R52C3H7OE",
    degeneracy = 1.0,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(2.81e+22,'s^-1'), n=-1.59, Ea=(88408,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(7.9502e+78,'cm^3/(mol*s)'), n=-17.506, Ea=(99510,'cal/mol'), T0=(1,'K')), alpha=0.09413, T3=(436.65,'K'), T1=(2.6334e+07,'K'), T2=(2833.3,'K'), efficiencies={}),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 6,
    label = "DEE + H <=> H2 + C2H5OC2H4-B",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.5e+07,'cm^3/(mol*s)'), n=1.98, Ea=(9200,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
!Calculation!CBS-QB3
""",
)

entry(
    index = 7,
    label = "DEE + H <=> H2 + C2H5OC2H4-A",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+07,'cm^3/(mol*s)'), n=2.17, Ea=(3600,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
!Calculation!CBS-QB3
""",
)

entry(
    index = 8,
    label = "DEE + OH <=> H2O + C2H5OC2H4-B",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3510,'cm^3/(mol*s)'), n=2.85, Ea=(-1580,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Calculation!Zhou et al. 2010
""",
)

entry(
    index = 9,
    label = "DEE + OH <=> H2O + C2H5OC2H4-A",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2260,'cm^3/(mol*s)'), n=2.93, Ea=(-4040,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Calculation!Zhou et al. 2010
""",
)

entry(
    index = 10,
    label = "DEE + HO2 <=> H2O2 + C2H5OC2H4-B",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.000731,'cm^3/(mol*s)'), n=4.7, Ea=(13032,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Calculation!Hu et al.2017
""",
)

entry(
    index = 11,
    label = "DEE + HO2 <=> H2O2 + C2H5OC2H4-A",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.000895,'cm^3/(mol*s)'), n=4.6, Ea=(4320,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Calculation!Hu et al.2017
""",
)

entry(
    index = 12,
    label = "DEE + O2 <=> HO2 + C2H5OC2H4-B",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.2e+13,'cm^3/(mol*s)'), n=0, Ea=(54175.2,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Correlation Ingham et al.
""",
)

entry(
    index = 13,
    label = "DEE + O2 <=> HO2 + C2H5OC2H4-A",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.8e+13,'cm^3/(mol*s)'), n=0, Ea=(46661.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Correlation Ingham et al.
""",
)

entry(
    index = 14,
    label = "DEE + O <=> OH + C2H5OC2H4-B",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1940,'cm^3/(mol*s)'), n=3.23, Ea=(4658,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Analogy to C2H5OHx2!CBS-QB3!
""",
)

entry(
    index = 15,
    label = "DEE + O <=> OH + C2H5OC2H4-A",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(290000,'cm^3/(mol*s)'), n=2.47, Ea=(876,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Analogy to C2H5OHx2!CBS-QB3!
""",
)

entry(
    index = 16,
    label = "DEE + CH3 <=> CH4 + C2H5OC2H4-B",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(660,'cm^3/(mol*s)'), n=3.3, Ea=(12291,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Analogy to C2H5OHx2!CBS-QB3!
""",
)

entry(
    index = 17,
    label = "DEE + CH3 <=> CH4 + C2H5OC2H4-A",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(39.8,'cm^3/(mol*s)'), n=3.37, Ea=(7635,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Analogy to C2H5OHx2!CBS-QB3!
""",
)

entry(
    index = 41,
    label = "DEE + CH3CO2 <=> C2H5OC2H4-A + CH3COOH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(17690,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Eble et al. 2017
""",
)

entry(
    index = 53,
    label = "C2H5OC2H4-B <=> C2H5OC2H4-A",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(12000,'s^-1'), n=2.22, Ea=(15200,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
!CBS-QB3
""",
)

entry(
    index = 54,
    label = "C2H5OC2H4-B <=> C2H5O + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.6e+12,'s^-1'), n=0.41, Ea=(24300,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
!CBS-QB3
""",
)

entry(
    index = 55,
    label = "C2H5OC2H4-B <=> H + EVE",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.5e+07,'s^-1'), n=1.78, Ea=(30700,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
!CBS-QB3
""",
)

entry(
    index = 56,
    label = "C2H5OC2H4-A <=> C2H5 + CH3CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.4e+13,'s^-1'), n=0.1, Ea=(22800,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
!CBS-QB3
""",
)

entry(
    index = 57,
    label = "C2H5OC2H4-A <=> H + EVE",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.8e+07,'s^-1'), n=1.77, Ea=(35700,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
!CBS-QB3
""",
)

#Reverse of original Sakai rate - replace with original Sakai calculation to remove source of error
entry(
    index = 74,
    label = "C2H5OC2H4-B + O2 <=> C2OC2H4OO-B",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.301e+23,'cm^3/(mol*s)'), n=-3.36, Ea=(3034.9,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 75,
    label = "C2H5OC2H4-A + O2 <=> C2OC2H4OO-A",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.641e+16,'cm^3/(mol*s)'), n=-0.99, Ea=(2765.58,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

#entry(
#    index = 74,
#    label = "C2OC2H4OO-B <=> C2H5OC2H4-B + O2",
#    degeneracy = 1.0,
#    kinetics = Arrhenius(A=(1.39E+26,'s^-1'), n=-3.36, Ea=(36067.8,'cal/mol'), T0=(1,'K')),
#    longDesc = 
#"""
#!Sakai:PCI35(2015)161-169:pRO2:*dis, A*2 for symmetry
#""",
#)

#entry(
#    index = 75,
#    label = "C2OC2H4OO-A <=> C2H5OC2H4-A + O2",
#    degeneracy = 1.0,
#    kinetics = Arrhenius(A=(4.9E+18,'s^-1'), n=-0.99, Ea=(38595.5,'cal/mol'), T0=(1,'K')),
#    longDesc = 
#"""
#Sakai:PCI35(2015)161-169:sRO2:*dis, A*2 for symmetry
#""",
#)

entry(
    index = 109,
    label = "C2OC2H4OO-B <=> HO2 + EVE",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.15e+09,'s^-1'), n=1.06, Ea=(31276.6,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
!Sakai:PCI35(2015)161-169:pRO2:*ho2 
""",
)

entry(
    index = 110,
    label = "C2OC2H4OO-A <=> HO2 + EVE",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.46e+11,'s^-1'), n=0.56, Ea=(29573.6,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
!Sakai:PCI35(2015)161-169:sRO2:*ho2
""",
)

entry(
    index = 111,
    label = "C2OC2H4OO-B <=> C2OC2-BO2H-A",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(668000,'s^-1'), n=1.69, Ea=(22886.6,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:pRO2:*14hs
""",
)

entry(
    index = 112,
    label = "C2OC2H4OO-B <=> C2OC2-BO2H-1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.24e+06,'s^-1'), n=1.28, Ea=(14623.8,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:pRO2:*16hs
""",
)

entry(
    index = 113,
    label = "C2OC2H4OO-B <=> C2OC2-BO2H-2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(208000,'s^-1'), n=1.42, Ea=(20871.6,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:pRO2:*17hs
""",
)

entry(
    index = 114,
    label = "C2OC2H4OO-A <=> C2OC2-AO2H-B",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(481000,'s^-1'), n=1.92, Ea=(30857.3,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:sRO2:*14hs
""",
)

entry(
    index = 115,
    label = "C2OC2H4OO-A <=> C2OC2-AO2H-1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.83e+06,'s^-1'), n=1.38, Ea=(13882.6,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:sRO2:*15hs
""",
)

entry(
    index = 116,
    label = "C2OC2H4OO-A <=> C2OC2-AO2H-2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.14e+06,'s^-1'), n=1.4, Ea=(20164.2,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:sRO2:*16hs
""",
)

entry(
    index = 117,
    label = "C2OC2H4OO-B <=> C2H5OCH2CHO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+06,'s^-1'), n=1.96, Ea=(38057,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:pRO2:*13hs
""",
)

entry(
    index = 118,
    label = "C2OC2H4OO-A <=> EA + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.44e+07,'s^-1'), n=1.46, Ea=(33826.7,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:sRO2:*13hs
""",
)

entry(
    index = 119,
    label = "C2OC2-AO2H-B <=> C2OC2-AO2H-1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(29700,'s^-1'), n=2.04, Ea=(12583.7,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169: sQOOH14hs:*14hs
""",
)

entry(
    index = 125,
    label = "C2OC2-BO2H-A <=> C2H5OCH2CHO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.01e+09,'s^-1'), n=1.1, Ea=(18767.2,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169: pQOOH14hs: *12hs
""",
)

entry(
    index = 126,
    label = "C2OC2-BO2H-1 <=> C2H5OCH2CHO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.98e+06,'s^-1'), n=1.82, Ea=(19409,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169: pQOOH16hs: *14hs
""",
)

entry(
    index = 127,
    label = "C2OC2-BO2H-2 <=> C2H5OCH2CHO + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.14e+06,'s^-1'), n=1.41, Ea=(11882.3,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169: pQOOH16hs: *15hs
""",
)

entry(
    index = 130,
    label = "C2OC2-AO2H-2 <=> EA + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(715000,'s^-1'), n=1.68, Ea=(13006.9,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169: sQOOH16hs:*14hs
""",
)

entry(
    index = 131,
    label = "C2OC2-BO2H-A <=> C2OC2OA-B + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.12e+10,'s^-1'), n=0.6, Ea=(10003.6,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:pQOOH14hs:*rc
""",
)

entry(
    index = 132,
    label = "C2OC2-BO2H-1 <=> C2OC2OA-2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.97e+09,'s^-1'), n=0.73, Ea=(9377.6,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:pQOOH16hs:*rc
""",
)

entry(
    index = 133,
    label = "C2OC2-BO2H-2 <=> C2OC2OB-2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.59e+08,'s^-1'), n=0.68, Ea=(12213.4,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:pQOOH17hs:*rc
""",
)

entry(
    index = 134,
    label = "C2OC2-AO2H-B <=> C2OC2OA-B + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.07e+10,'s^-1'), n=0.63, Ea=(12036.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:sQOOH14hs:*rc
""",
)

entry(
    index = 135,
    label = "C2OC2-AO2H-1 <=> C2OC2OA-1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.14e+11,'s^-1'), n=0.2, Ea=(19927.7,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:sQOOH15hs:*rc
""",
)

entry(
    index = 136,
    label = "C2OC2-AO2H-2 <=> C2OC2OA-2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.68e+10,'s^-1'), n=0.27, Ea=(14927.9,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:sQOOH16hs:*rc
""",
)

entry(
    index = 137,
    label = "C2OC2-BO2H-A <=> EVE + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.13e+10,'s^-1'), n=0.69, Ea=(14604.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:pQOOH14hs:*co
""",
)

entry(
    index = 138,
    label = "C2OC2-AO2H-B <=> EVE + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.02e+11,'s^-1'), n=0.48, Ea=(16810,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI35(2015)161-169:sQOOH14hs:*co
""",
)

entry(
    index = 139,
    label = "C2OC2-AO2H-1 => CH3CHO + CH3CHO + OH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.15e+11,'s^-1'), n=0.49, Ea=(17404.2,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
AVREAGED BETWEEN SAKAI AND EBLE
""",
)

entry(
    index = 144,
    label = "C4O-BO2H-AO2 <=> C2OC2-BO2H-A + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.9E+18,'s^-1'), n=-0.99, Ea=(38595.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 145,
    label = "C4O-BO2H-1O2 <=> C2OC2-BO2H-1 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.9E+18,'s^-1'), n=-0.99, Ea=(38595.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 146,
    label = "C4O-BO2H-2O2 <=> C2OC2-BO2H-2 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.394E+26,'s^-1'), n=-3.36, Ea=(36067.8,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 147,
    label = "C4O-AO2H-BO2 <=> C2OC2-AO2H-B + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.394E+26,'s^-1'), n=-3.36, Ea=(36067.8,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 148,
    label = "C4O-AO2H-1O2 <=> C2OC2-AO2H-1 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.9E+18,'s^-1'), n=-0.99, Ea=(38595.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 149,
    label = "C4O-AO2H-2O2 <=> C2OC2-AO2H-2 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.394E+26,'s^-1'), n=-3.36, Ea=(36067.8,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 150,
    label = "C4O-BO2H-AO2 <=> C2OC2KETB-A + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.23e+09,'s^-1'), n=1.05, Ea=(28600,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
approach proposed by Thion et al.CnF2017
""",
)

entry(
    index = 151,
    label = "C4O-BO2H-1O2 <=> C2OC2KETB-1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86e+06,'s^-1'), n=1.27, Ea=(17000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
approach proposed by Thion et al.CnF2017
""",
)

entry(
    index = 152,
    label = "C4O-BO2H-2O2 <=> C2OC2KETB-2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(534000,'s^-1'), n=1.12, Ea=(15700,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
approach proposed by Thion et al.CnF2017
""",
)

entry(
    index = 153,
    label = "C4O-AO2H-BO2 <=> C2OC2KETA-B + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86e+07,'s^-1'), n=1.38, Ea=(22600,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
approach proposed by Thion et al.CnF2017
""",
)

entry(
    index = 154,
    label = "C4O-AO2H-1O2 <=> C2OC2KETA-1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.11e+09,'s^-1'), n=0.51, Ea=(13300,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
approach proposed by Thion et al.CnF2017
""",
)

entry(
    index = 155,
    label = "C4O-AO2H-2O2 <=> C2OC2KETA-2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.63e+07,'s^-1'), n=0.91, Ea=(11700,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
approach proposed by Thion et al.CnF2017
""",
)

entry(
    index = 160,
    label = "C2OC2KETB-1 => CH3COOH + CH3COOH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(2.1e+08,'s^-1'), n=0, Ea=(28000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Jalan et al. JACS 135 (2013) 11100-1114
""",
)

entry(
    index = 161,
    label = "C2OC2KETA-1 => CH3COOH + CH3COOH",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(2.1e+08,'s^-1'), n=0, Ea=(28000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Jalan et al. JACS 135 (2013) 11100-1114
""",
)

entry(
    index = 162,
    label = "C2OC2KETB-1R <=> CH3COOH + CH2CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+10,'s^-1'), n=0.72, Ea=(11200,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Wang et al. CnF 162 (2015) 1113-1125! Ea-2kcal because of tertiary H-atom
""",
)

entry(
    index = 163,
    label = "C2OC2KETA-1R <=> CH3COOH + CH3CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+10,'s^-1'), n=0.72, Ea=(11200,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Wang et al. CnF 162 (2015) 1113-1125! Ea-2kcal because of tertiary H-atom
""",
)

entry(
    index = 177,
    label = "C4O-BO2H-AO2 <=> C4O-BO2H-AO2H-1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.83e+06,'s^-1'), n=1.38, Ea=(13882.6,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 178,
    label = "C4O-BO2H-1O2 <=> C4O-BO2H-1O2H-A",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.83e+06,'s^-1'), n=1.38, Ea=(13882.6,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 179,
    label = "C4O-BO2H-2O2 <=> C4O-BO2H-2O2H-A",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.24e+06,'s^-1'), n=1.28, Ea=(14623.8,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 180,
    label = "C4O-AO2H-BO2 <=> C4O-BO2H-AO2H-1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.24e+06,'s^-1'), n=1.28, Ea=(14623.8,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 181,
    label = "C4O-AO2H-1O2 <=> C4O-AO2H-1O2H-B",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(2.14e+06,'s^-1'), n=1.4, Ea=(20164.2,'cal/mol'), T0=(1,'K')), Arrhenius(A=(481000,'s^-1'), n=1.92, Ea=(30857.3,'cal/mol'), T0=(1,'K'))]),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 182,
    label = "C4O-AO2H-1O2 <=> C4O-AO2H-1O2H-B",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(4.810E+05,'s^-1'), n=1.92, Ea=(30857.3,'cal/mol'), T0=(1,'K')), Arrhenius(A=(481000,'s^-1'), n=1.92, Ea=(30857.3,'cal/mol'), T0=(1,'K'))]),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 183,
    label = "C4O-AO2H-2O2 <=> C4O-BO2H-1O2H-A",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(668000,'s^-1'), n=1.69, Ea=(22886.6,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 184,
    label = "C4O-BO2H-AO2 <=> C4O-AO2H-BO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.34e+09,'s^-1'), n=0, Ea=(14129.1,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI36(2017)195-202
""",
)

entry(
    index = 185,
    label = "C4O-AO2H-2O2 <=> C4O-BO2H-1O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.22e+08,'s^-1'), n=0, Ea=(14844.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Sakai:PCI36(2017)195-202
""",
)

entry(
    index = 186,
    label = "C4O-BO2H-AO2H-1 => CH3CHO + OH + HO2CH2CHO",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.15e+11,'s^-1'), n=0.49, Ea=(17404.2,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
as C2OC2-AO2H-1=>CH3CHO+CH3CHO+OH
""",
)

entry(
    index = 187,
    label = "C4O-BO2H-1O2H-A => CH3CHO + OH + HO2CH2CHO",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(6.15e+11,'s^-1'), n=0.49, Ea=(17404.2,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
C2OC2-AO2H-1=>CH3CHO+CH3CHO+OH
""",
)

#As other O2 additions
entry(
    index = 188,
    label = "C4O-BO2H-AO2H1O2 <=> C4O-BO2H-AO2 + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.9E+18,'s^-1'), n=-0.99, Ea=(38595.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 189,
    label = "C4O-BO2H-1O2HAO2 <=> C4O-BO2H-1O2H-A + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.9E+18,'s^-1'), n=-0.99, Ea=(38595.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 190,
    label = "C4O-BO2H-2O2HAO2 <=> C4O-BO2H-2O2H-A + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.9E+18,'s^-1'), n=-0.99, Ea=(38595.5,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 191,
    label = "C4O-AO2H-1O2HBO2 <=> C4O-AO2H-1O2H-B + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.394E+26,'s^-1'), n=-3.36, Ea=(36067.8,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 192,
    label = "C4O-BO2H-AO2H1O2 <=> C2OC2KETA-B-1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.11e+09,'s^-1'), n=0.51, Ea=(13300,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
approach proposed by Thion et al.CnF2017
""",
)

entry(
    index = 193,
    label = "C4O-BO2H-1O2HAO2 <=> C2OC2KET1-A-B + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.11e+09,'s^-1'), n=0.51, Ea=(13300,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
approach proposed by Thion et al.CnF2017
""",
)

entry(
    index = 194,
    label = "C4O-BO2H-2O2HAO2 <=> C2OC2KET2-A-B + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.86e+06,'s^-1'), n=1.27, Ea=(17000,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
approach proposed by Thion et al.CnF2017
""",
)

entry(
    index = 195,
    label = "C4O-AO2H-1O2HBO2 <=> C2OC2KET1-A-B + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.63e+07,'s^-1'), n=0.91, Ea=(11700,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
approach proposed by Thion et al.CnF2017
""",
)

entry(
    index = 198,
    label = "C2H5OC2H4O-B <=> R52C3H7OE + CH2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Sakai:PCI36(2017)195-202
""",
)

entry(
    index = 199,
    label = "C2H5OC2H4O-A <=> C2H5OCHO + CH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Sakai:PCI36(2017)195-202
""",
)

entry(
    index = 200,
    label = "C2H5OC2H4O-A <=> CH3CHO + C2H5O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+11,'s^-1'), n=0, Ea=(11900,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Sakai:PCI36(2017)195-202
""",
)

entry(
    index = 203,
    label = "CH3CO + O2 <=> CH3CO3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.3e+12,'cm^3/(mol*s)'), n=0.2, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: 2011CAR/GLO1069-1085
""",
)
