#!/usr/bin/env python
# encoding: utf-8

name = "Michelbach_nBL"
shortDesc = "RMG version of michelbach_nBL_submech.inp - see the original file for sources."
longDesc = """

"""
autoGenerated=False
entry(
    index = 0,
    label = "[CH2]C(=O)CCC(=O)OCCCC + H <=> CCCCOC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.17499e+13,'cm^3/(mol*s)'), n=0.12, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 1,
    label = "CCCCOC(=O)C[CH]C(C)=O + H <=> CCCCOC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.76637e+13,'cm^3/(mol*s)'), n=0.15, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 2,
    label = "CCCCOC(=O)[CH]CC(C)=O + H <=> CCCCOC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.76637e+13,'cm^3/(mol*s)'), n=0.15, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 3,
    label = "CCC[CH]OC(=O)CCC(C)=O + H <=> CCCCOC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.17499e+13,'cm^3/(mol*s)'), n=0.12, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 4,
    label = "CC[CH]COC(=O)CCC(C)=O + H <=> CCCCOC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.76637e+13,'cm^3/(mol*s)'), n=0.15, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 5,
    label = "C[CH]CCOC(=O)CCC(C)=O + H <=> CCCCOC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.76637e+13,'cm^3/(mol*s)'), n=0.15, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 6,
    label = "[CH2]CCCOC(=O)CCC(C)=O + H <=> CCCCOC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.17499e+13,'cm^3/(mol*s)'), n=0.12, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 7,
    label = "[CH2]C(=O)CCC(=O)OCCCC <=> CCCCOC(=O)[CH]CC(C)=O",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(4.39e+10,'s^-1'), n=0.58, Ea=(22.31,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 8,
    label = "CCCCOC(=O)C[CH]C(C)=O <=> CCC[CH]OC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.22e+09,'s^-1'), n=0.52, Ea=(22.59,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 9,
    label = "CCCCOC(=O)[CH]CC(C)=O <=> CCC[CH]OC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.13e+10,'s^-1'), n=0.6, Ea=(28.03,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 10,
    label = "CCCCOC(=O)[CH]CC(C)=O <=> [CH2]C(=O)CCC(=O)OCCCC",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(3.54e+10,'s^-1'), n=0.54, Ea=(23.37,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 11,
    label = "CCC[CH]OC(=O)CCC(C)=O <=> [CH2]CCCOC(=O)CCC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.88e+10,'s^-1'), n=0.57, Ea=(25.9,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 12,
    label = "CCCCOC(=O)CCC(C)=O + H <=> [CH2]C(=O)CCC(=O)OCCCC + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.205e+07,'cm^3/(mol*s)'), n=2.225, Ea=(6.94,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 13,
    label = "CCCCOC(=O)CCC(C)=O + H <=> CCCCOC(=O)C[CH]C(C)=O + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.988e+06,'cm^3/(mol*s)'), n=2.256, Ea=(4.08,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 14,
    label = "CCCCOC(=O)CCC(C)=O + H <=> CCCCOC(=O)[CH]CC(C)=O + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.12e+09,'cm^3/(mol*s)'), n=1.22, Ea=(4.77,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 15,
    label = "CCCCOC(=O)CCC(C)=O + H <=> CCC[CH]OC(=O)CCC(C)=O + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.07e+06,'cm^3/(mol*s)'), n=2.35, Ea=(6.24,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 16,
    label = "CCCCOC(=O)CCC(C)=O + H <=> CC[CH]COC(=O)CCC(C)=O + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.04e+06,'cm^3/(mol*s)'), n=2.13, Ea=(7.28,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 17,
    label = "CCCCOC(=O)CCC(C)=O + H <=> C[CH]CCOC(=O)CCC(C)=O + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(614000,'cm^3/(mol*s)'), n=2.46, Ea=(5.73,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 18,
    label = "CCCCOC(=O)CCC(C)=O + H <=> [CH2]CCCOC(=O)CCC(C)=O + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.15e+06,'cm^3/(mol*s)'), n=2.43, Ea=(8.08,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 19,
    label = "CCCCOC(=O)CCC(C)=O + HO2 <=> [CH2]C(=O)CCC(=O)OCCCC + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.00558,'cm^3/(mol*s)'), n=4.32, Ea=(13.4,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 20,
    label = "CCCCOC(=O)CCC(C)=O + HO2 <=> CCCCOC(=O)C[CH]C(C)=O + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.0842,'cm^3/(mol*s)'), n=3.93, Ea=(10.4,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 21,
    label = "CCCCOC(=O)CCC(C)=O + HO2 <=> CCCCOC(=O)[CH]CC(C)=O + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.00153,'cm^3/(mol*s)'), n=4.22, Ea=(11.05,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 22,
    label = "CCCCOC(=O)CCC(C)=O + HO2 <=> CCC[CH]OC(=O)CCC(C)=O + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.284,'cm^3/(mol*s)'), n=4.54, Ea=(11.9,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 23,
    label = "CCCCOC(=O)CCC(C)=O + HO2 <=> CC[CH]COC(=O)CCC(C)=O + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.63,'cm^3/(mol*s)'), n=4.35, Ea=(13.5,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 24,
    label = "CCCCOC(=O)CCC(C)=O + HO2 <=> C[CH]CCOC(=O)CCC(C)=O + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.0433,'cm^3/(mol*s)'), n=4.52, Ea=(10.27,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 25,
    label = "CCCCOC(=O)CCC(C)=O + HO2 <=> [CH2]CCCOC(=O)CCC(C)=O + H2O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(11.5,'cm^3/(mol*s)'), n=4.3, Ea=(15.05,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 26,
    label = "CCCCOC(=O)CCC(C)=O + OH <=> [CH2]C(=O)CCC(=O)OCCCC + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4060,'cm^3/(mol*s)'), n=2.84, Ea=(0.07,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 27,
    label = "CCCCOC(=O)CCC(C)=O + OH <=> CCCCOC(=O)C[CH]C(C)=O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3250,'cm^3/(mol*s)'), n=2.89, Ea=(-1.5,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 28,
    label = "CCCCOC(=O)CCC(C)=O + OH <=> CCCCOC(=O)[CH]CC(C)=O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(287,'cm^3/(mol*s)'), n=3.06, Ea=(-2.32,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 29,
    label = "CCCCOC(=O)CCC(C)=O + OH <=> CCC[CH]OC(=O)CCC(C)=O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(782,'cm^3/(mol*s)'), n=2.91, Ea=(-2.55,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 30,
    label = "CCCCOC(=O)CCC(C)=O + OH <=> CC[CH]COC(=O)CCC(C)=O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(728,'cm^3/(mol*s)'), n=3.18, Ea=(-0.68,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 31,
    label = "CCCCOC(=O)CCC(C)=O + OH <=> C[CH]CCOC(=O)CCC(C)=O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3420,'cm^3/(mol*s)'), n=2.96, Ea=(-1.43,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 32,
    label = "CCCCOC(=O)CCC(C)=O + OH <=> [CH2]CCCOC(=O)CCC(C)=O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7020,'cm^3/(mol*s)'), n=3.07, Ea=(1.04,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 33,
    label = "CCCCOC(=O)CCC(C)=O + CH3 <=> [CH2]C(=O)CCC(=O)OCCCC + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(37.1,'cm^3/(mol*s)'), n=3.12, Ea=(9.98,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 34,
    label = "CCCCOC(=O)CCC(C)=O + CH3 <=> CCCCOC(=O)C[CH]C(C)=O + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(14.1,'cm^3/(mol*s)'), n=3.29, Ea=(8.33,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 35,
    label = "CCCCOC(=O)CCC(C)=O + CH3 <=> CCCCOC(=O)[CH]CC(C)=O + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(54.6,'cm^3/(mol*s)'), n=3.13, Ea=(8.68,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 36,
    label = "CCCCOC(=O)CCC(C)=O + CH3 <=> CCC[CH]OC(=O)CCC(C)=O + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.7e-25,'cm^3/(mol*s)'), n=11.28, Ea=(-3.62,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 37,
    label = "CCCCOC(=O)CCC(C)=O + O <=> CCCCOC(=O)[CH]CC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(45.5,'cm^3/(mol*s)'), n=3.6, Ea=(1.97,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 38,
    label = "CCCCOC(=O)CCC(C)=O + O <=> CCC[CH]OC(=O)CCC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(290.6,'cm^3/(mol*s)'), n=3.6, Ea=(3.89,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 39,
    label = "[CH2]C(=O)CCC(=O)OCCCC + O2 <=> CCCCOC(=O)CCC(=O)CO[O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 40,
    label = "CCCCOC(=O)C[CH]C(C)=O + O2 <=> CCCCOC(=O)CC(O[O])C(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 41,
    label = "CCCCOC(=O)[CH]CC(C)=O + O2 <=> CCCCOC(=O)C(CC(C)=O)O[O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.48e+12,'cm^3/(mol*s)'), n=0, Ea=(-0.61,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 42,
    label = "CCCC(O[O])OC(=O)CCC(C)=O <=> CCC[CH]OC(=O)CCC(C)=O + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.45e+18,'s^-1'), n=-0.99, Ea=(38.6,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 43,
    label = "CCCCOC(=O)CC(O[O])C(C)=O <=> CCCCOC(=O)C=CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 44,
    label = "CCCCOC(=O)C(CC(C)=O)O[O] <=> CCCCOC(=O)C=CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 45,
    label = "CCCC(O[O])OC(=O)CCC(C)=O <=> CCC=COC(=O)CCC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(36900,'s^-1'), n=2.61, Ea=(29.01,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 46,
    label = "CCCCOC(=O)CCC(=O)CO[O] <=> C(=O)C(=O)CCC(=O)OCCCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.25e+17,'s^-1'), n=-3.58, Ea=(44.55,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 47,
    label = "CCCCOC(=O)CCC(=O)CO[O] <=> C([O])C(=O)CCC(=O)OCCCC + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.42e+16,'s^-1'), n=-2.97, Ea=(47.78,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 48,
    label = "CCCCOC(=O)CC(O[O])C(C)=O <=> CC(=O)C(=O)CC(=O)OCCCC + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.69e+12,'s^-1'), n=-0.08, Ea=(39.2,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 49,
    label = "CCCCOC(=O)CC(O[O])C(C)=O <=> CC(=O)C([O])CC(=O)OCCCC + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.02e+14,'s^-1'), n=0, Ea=(58.5,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 50,
    label = "CCCCOC(=O)C(CC(C)=O)O[O] <=> CCCCOC(=O)C(=O)CC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.11e-09,'s^-1'), n=6.19, Ea=(27.2,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 51,
    label = "CCCCOC(=O)CCC(=O)CO[O] <=> CCCCOC(=O)C[CH]C(=O)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.7e+11,'s^-1'), n=0, Ea=(17.72,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 52,
    label = "CCCCOC(=O)CCC(=O)CO[O] <=> CCCCOC(=O)[CH]CC(=O)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.18e+11,'s^-1'), n=0, Ea=(11.27,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 53,
    label = "CCCCOC(=O)CC(O[O])C(C)=O <=> [CH2]C(=O)C(CC(=O)OCCCC)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.83e+11,'s^-1'), n=0, Ea=(33.38,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 54,
    label = "CCCCOC(=O)CC(O[O])C(C)=O <=> CCCCOC(=O)[CH]C(OO)C(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.19e+11,'s^-1'), n=0, Ea=(19.87,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 55,
    label = "CCCCOC(=O)C(CC(C)=O)O[O] <=> [CH2]C(=O)CC(OO)C(=O)OCCCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.09e+11,'s^-1'), n=0, Ea=(11.29,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 56,
    label = "CCCCOC(=O)C(CC(C)=O)O[O] <=> CCCCOC(=O)C([CH]C(C)=O)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.9e-06,'s^-1'), n=5, Ea=(21.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 57,
    label = "CCCCOC(=O)C(CC(C)=O)O[O] <=> CCC[CH]OC(=O)C(CC(C)=O)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.878,'s^-1'), n=3.39, Ea=(24.1,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 58,
    label = "CCCC(O[O])OC(=O)CCC(C)=O <=> CCCC(OO)OC(=O)C[CH]C(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(52.5,'s^-1'), n=2.64, Ea=(17.6,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 59,
    label = "CCCC(O[O])OC(=O)CCC(C)=O <=> CCCC(OO)OC(=O)[CH]CC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.68,'s^-1'), n=3.33, Ea=(20.4,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 60,
    label = "CCCCOC(=O)[CH]C(OO)C(C)=O <=> CCCCOC(=O)C=CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 61,
    label = "CCCCOC(=O)C([CH]C(C)=O)OO <=> CCCCOC(=O)C=CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 62,
    label = "CCC[CH]OC(=O)C(CC(C)=O)OO <=> CCCC1OC(=O)C1CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.88e+09,'s^-1'), n=0.74, Ea=(48.8,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 63,
    label = "CCCC(OO)OC(=O)C[CH]C(C)=O <=> CCCC1OC(=O)CC1C(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.38e+08,'s^-1'), n=0.91, Ea=(43.6,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 64,
    label = "CCCC(OO)OC(=O)[CH]CC(C)=O <=> CCCC1OC(=O)C1CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.41e+09,'s^-1'), n=1.18, Ea=(59.1,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 65,
    label = "CCCCOC(=O)C([CH]C(C)=O)OO <=> CCCCOC(=O)C(=O)CC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.27e+10,'s^-1'), n=0.87, Ea=(29.5,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 66,
    label = "CCC[CH]OC(=O)C(CC(C)=O)OO <=> CCCCOC(=O)C(=O)CC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.686,'s^-1'), n=3.63, Ea=(17.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 67,
    label = "CCCC(OO)OC(=O)C[CH]C(C)=O <=> CCCC(=O)OC(=O)CCC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(138,'s^-1'), n=2.66, Ea=(12.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 68,
    label = "CCCC(OO)OC(=O)[CH]CC(C)=O <=> CCCC(=O)OC(=O)CCC(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.0021,'s^-1'), n=4.67, Ea=(22,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 69,
    label = "CCCCOC(=O)C[CH]C(=O)COO <=> CCCCOC(=O)CC1OCC1=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.14e+09,'s^-1'), n=0.76, Ea=(30.39,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 70,
    label = "CCCCOC(=O)[CH]CC(=O)COO <=> CCCCOC(=O)C1CC(=O)CO1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.22e+12,'s^-1'), n=-0.08, Ea=(17.72,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 71,
    label = "[CH2]C(=O)C(CC(=O)OCCCC)OO <=> CCCCOC(=O)CC1OCC1=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.37e+39,'s^-1'), n=-8.55, Ea=(35.68,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 72,
    label = "CCCCOC(=O)[CH]C(OO)C(C)=O <=> CCCCOC(=O)C1OC1C(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.29e+32,'s^-1'), n=-6.6, Ea=(20.39,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 73,
    label = "[CH2]C(=O)CC(OO)C(=O)OCCCC <=> CCCCOC(=O)C1CC(=O)CO1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.22e+12,'s^-1'), n=-0.08, Ea=(17.72,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 74,
    label = "CCCCOC(=O)C([CH]C(C)=O)OO <=> CCCCOC(=O)C1OC1C(C)=O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.23e+11,'s^-1'), n=0.45, Ea=(14.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 75,
    label = "CCC[CH]OC(=O)C(CC(C)=O)OO <=> CCCC1OC(=O)C(CC(C)=O)O1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.62e+11,'s^-1'), n=0.4, Ea=(25.3,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 76,
    label = "CCCC(OO)OC(=O)C[CH]C(C)=O <=> CCCC1OC(=O)CC(C(C)=O)O1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.59e+10,'s^-1'), n=0.35, Ea=(19.9,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 77,
    label = "CCCC(OO)OC(=O)[CH]CC(C)=O <=> CCCC1OC(=O)C(CC(C)=O)O1 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.17e+11,'s^-1'), n=0.6, Ea=(25.4,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 78,
    label = "CCCCOC(=O)C[CH]C(=O)COO + O2 <=> CCCCOC(=O)CC(O[O])C(=O)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 79,
    label = "CCCCOC(=O)[CH]CC(=O)COO + O2 <=> CCCCOC(=O)C(O[O])CC(=O)COO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.48e+12,'cm^3/(mol*s)'), n=0, Ea=(-0.61,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 80,
    label = "[CH2]C(=O)C(CC(=O)OCCCC)OO + O2 <=> CCCCOC(=O)CC(OO)C(=O)CO[O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 81,
    label = "CCCCOC(=O)[CH]C(OO)C(C)=O + O2 <=> CCCCOC(=O)C(O[O])C(OO)C(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.48e+12,'cm^3/(mol*s)'), n=0, Ea=(-0.61,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 82,
    label = "[CH2]C(=O)CC(OO)C(=O)OCCCC + O2 <=> CCCCOC(=O)C(CC(=O)CO[O])OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 83,
    label = "CCCCOC(=O)C([CH]C(C)=O)OO + O2 <=> CCCCOC(=O)C(OO)C(O[O])C(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 84,
    label = "CCCC(O[O])OC(=O)C(OO)CC(C)=O <=> CCC[CH]OC(=O)C(CC(C)=O)OO + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.45e+18,'s^-1'), n=-0.99, Ea=(38.6,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 85,
    label = "CCCC(OO)OC(=O)C[CH]C(C)=O + O2 <=> CCCC(OO)OC(=O)CC(O[O])C(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 86,
    label = "CCCC(OO)OC(=O)[CH]CC(C)=O + O2 <=> CCCC(OO)OC(=O)C(O[O])CC(C)=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.48e+12,'cm^3/(mol*s)'), n=0, Ea=(-0.61,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 87,
    label = "CCC(C(O[O])OC(=O)CCC(C)=O)OO <=> CCC([CH]OC(=O)CCC(C)=O)OO + O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.45e+18,'s^-1'), n=-0.99, Ea=(38.6,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 88,
    label = "CCCCOC(=O)CC(O[O])C(=O)COO <=> CCCCOC(=O)C=CC(=O)COO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 89,
    label = "CCCCOC(=O)C(O[O])CC(=O)COO <=> CCCCOC(=O)C=CC(=O)COO + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 90,
    label = "CCCCOC(=O)C(O[O])C(OO)C(C)=O <=> CCCCOC(=O)C=C(OO)C(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 91,
    label = "CCCCOC(=O)C(OO)C(O[O])C(C)=O <=> CCCCOC(=O)C(OO)=CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 92,
    label = "CCCC(OO)OC(=O)CC(O[O])C(C)=O <=> CCCC(OO)OC(=O)C=CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.78e+13,'s^-1'), n=0, Ea=(18.46,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

entry(
    index = 93,
    label = "CCCC(OO)OC(=O)C(O[O])CC(C)=O <=> CCCC(OO)OC(=O)C=CC(C)=O + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.34e+09,'s^-1'), n=1.13, Ea=(26.63,'kcal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: Unclassified
""",
)

